#include "mylite_execution_catalog_system_tables_internal.h"

static const char mysql_system_table_default_column_privileges[] =
    "select,insert,update,references";

static const struct mylite_execution_catalog_column_definition mysql_slave_master_info_columns[] = {
    {"Number_of_lines", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"Master_log_name",
     NULL,
     "NO",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Master_log_pos",
     NULL,
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"Host",
     NULL,
     "YES",
     "varchar",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "varchar(255)"},
    {"User_name",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"User_password",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Port", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"Connect_retry", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"Enabled_ssl", NULL, "NO", "tinyint", NULL, NULL, "3", "0", NULL, NULL, NULL, "tinyint(1)"},
    {"Ssl_ca",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Ssl_capath",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Ssl_cert",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Ssl_cipher",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Ssl_key",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Ssl_verify_server_cert",
     NULL,
     "NO",
     "tinyint",
     NULL,
     NULL,
     "3",
     "0",
     NULL,
     NULL,
     NULL,
     "tinyint(1)"},
    {"Heartbeat", NULL, "NO", "float", NULL, NULL, "12", NULL, NULL, NULL, NULL, "float"},
    {"Bind",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Ignored_server_ids",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Uuid",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Retry_count",
     NULL,
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"Ssl_crl",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Ssl_crlpath",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Enabled_auto_position",
     NULL,
     "NO",
     "tinyint",
     NULL,
     NULL,
     "3",
     "0",
     NULL,
     NULL,
     NULL,
     "tinyint(1)"},
    {"Channel_name",
     NULL,
     "NO",
     "varchar",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(64)"},
    {"Tls_version",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Public_key_path",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Get_public_key", NULL, "NO", "tinyint", NULL, NULL, "3", "0", NULL, NULL, NULL, "tinyint(1)"},
    {"Network_namespace",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Master_compression_algorithm",
     NULL,
     "NO",
     "varchar",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "varchar(64)"},
    {"Master_zstd_compression_level",
     NULL,
     "NO",
     "int",
     NULL,
     NULL,
     "10",
     "0",
     NULL,
     NULL,
     NULL,
     "int unsigned"},
    {"Tls_ciphersuites",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Source_connection_auto_failover",
     "0",
     "NO",
     "tinyint",
     NULL,
     NULL,
     "3",
     "0",
     NULL,
     NULL,
     NULL,
     "tinyint(1)"},
    {"Gtid_only", "0", "NO", "tinyint", NULL, NULL, "3", "0", NULL, NULL, NULL, "tinyint(1)"},
};

static const char *const mysql_slave_master_info_column_keys[] = {
    "", "", "", "", "", "", "",    "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "PRI", "", "", "", "", "", "", "", "", "",
};

static const char *const mysql_slave_master_info_column_extras[] = {
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
};

static const char *const mysql_slave_master_info_column_privileges[] = {
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges, mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
};

static const char *const mysql_slave_master_info_column_comments[] = {
    "Number of lines in the file.",
    "The name of the master binary log currently being read from the master.",
    "The master log position of the last read event.",
    "The host name of the source.",
    "The user name used to connect to the master.",
    "The password used to connect to the master.",
    "The network port used to connect to the master.",
    "The period (in seconds) that the slave will wait before trying to reconnect to the master.",
    "Indicates whether the server supports SSL connections.",
    "The file used for the Certificate Authority (CA) certificate.",
    "The path to the Certificate Authority (CA) certificates.",
    "The name of the SSL certificate file.",
    "The name of the cipher in use for the SSL connection.",
    "The name of the SSL key file.",
    "Whether to verify the server certificate.",
    "",
    "Displays which interface is employed when connecting to the MySQL server",
    "The number of server IDs to be ignored, followed by the actual server IDs",
    "The master server uuid.",
    "Number of reconnect attempts, to the master, before giving up.",
    "The file used for the Certificate Revocation List (CRL)",
    "The path used for Certificate Revocation List (CRL) files",
    "Indicates whether GTIDs will be used to retrieve events from the master.",
    "The channel on which the replica is connected to a source. Used in Multisource Replication",
    "Tls version",
    "The file containing public key of master server.",
    "Preference to get public key from master.",
    "Network namespace used for communication with the master server.",
    "Compression algorithm supported for data transfer between source and replica.",
    "Compression level associated with zstd compression algorithm.",
    "Ciphersuites used for TLS 1.3 communication with the master server.",
    "Indicates whether the channel connection failover is enabled.",
    "Indicates if this channel only uses GTIDs and does not persist positions.",
};

static const struct mylite_execution_catalog_column_definition
    mysql_slave_relay_log_info_columns[] = {
        {"Number_of_lines",
         NULL,
         "NO",
         "int",
         NULL,
         NULL,
         "10",
         "0",
         NULL,
         NULL,
         NULL,
         "int unsigned"},
        {"Relay_log_name",
         NULL,
         "YES",
         "text",
         "65535",
         "65535",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "text"},
        {"Relay_log_pos",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"Master_log_name",
         NULL,
         "YES",
         "text",
         "65535",
         "65535",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "text"},
        {"Master_log_pos",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"Sql_delay", NULL, "YES", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
        {"Number_of_workers",
         NULL,
         "YES",
         "int",
         NULL,
         NULL,
         "10",
         "0",
         NULL,
         NULL,
         NULL,
         "int unsigned"},
        {"Id", NULL, "YES", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
        {"Channel_name",
         NULL,
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(64)"},
        {"Privilege_checks_username",
         NULL,
         "YES",
         "varchar",
         "32",
         "96",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(32)"},
        {"Privilege_checks_hostname",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"Require_row_format",
         NULL,
         "NO",
         "tinyint",
         NULL,
         NULL,
         "3",
         "0",
         NULL,
         NULL,
         NULL,
         "tinyint(1)"},
        {"Require_table_primary_key_check",
         "STREAM",
         "NO",
         "enum",
         "8",
         "24",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "enum('STREAM','ON','OFF','GENERATE')"},
        {"Assign_gtids_to_anonymous_transactions_type",
         "OFF",
         "NO",
         "enum",
         "5",
         "15",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "enum('OFF','LOCAL','UUID')"},
        {"Assign_gtids_to_anonymous_transactions_value",
         NULL,
         "YES",
         "text",
         "65535",
         "65535",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "text"},
};

static const char *const mysql_slave_relay_log_info_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "PRI",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_slave_relay_log_info_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_slave_relay_log_info_column_privileges[] = {
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
};

static const char *const mysql_slave_relay_log_info_column_comments[] = {
    "Number of lines in the file or rows in the table. Used to version table definitions.",
    "The name of the current relay log file.",
    "The relay log position of the last executed event.",
    "The name of the master binary log file from which the events in the relay log file were read.",
    "The master log position of the last executed event.",
    "The number of seconds that the slave must lag behind the master.",
    "",
    "Internal Id that uniquely identifies this record.",
    "The channel on which the replica is connected to a source. Used in Multisource Replication",
    "Username part of PRIVILEGE_CHECKS_USER.",
    "Hostname part of PRIVILEGE_CHECKS_USER.",
    "Indicates whether the channel shall only accept row based events.",
    ("Indicates what is the channel policy regarding tables without primary keys on create and "
     "alter table queries"),
    ("Indicates whether the channel will generate a new GTID for anonymous transactions. OFF means "
     "that anonymous transactions will remain anonymous. LOCAL means that anonymous transactions "
     "will be assigned a newly generated GTID based on server_uuid. UUID indicates that anonymous "
     "transactions will be assigned a newly generated GTID based on "
     "Assign_gtids_to_anonymous_transactions_value"),
    "Indicates the UUID used while generating GTIDs for anonymous transactions",
};

static const struct mylite_execution_catalog_column_definition mysql_slave_worker_info_columns[] = {
    {"Id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"Relay_log_name",
     NULL,
     "NO",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Relay_log_pos",
     NULL,
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"Master_log_name",
     NULL,
     "NO",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Master_log_pos",
     NULL,
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"Checkpoint_relay_log_name",
     NULL,
     "NO",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Checkpoint_relay_log_pos",
     NULL,
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"Checkpoint_master_log_name",
     NULL,
     "NO",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"Checkpoint_master_log_pos",
     NULL,
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"Checkpoint_seqno",
     NULL,
     "NO",
     "int",
     NULL,
     NULL,
     "10",
     "0",
     NULL,
     NULL,
     NULL,
     "int unsigned"},
    {"Checkpoint_group_size",
     NULL,
     "NO",
     "int",
     NULL,
     NULL,
     "10",
     "0",
     NULL,
     NULL,
     NULL,
     "int unsigned"},
    {"Checkpoint_group_bitmap",
     NULL,
     "NO",
     "blob",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     "blob"},
    {"Channel_name",
     NULL,
     "NO",
     "varchar",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(64)"},
};

static const char *const mysql_slave_worker_info_column_keys[] = {
    "PRI",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "PRI",
};

static const char *const mysql_slave_worker_info_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_slave_worker_info_column_privileges[] = {
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
    mysql_system_table_default_column_privileges,
};

static const char *const mysql_slave_worker_info_column_comments[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "The channel on which the replica is connected to a source. Used in Multisource Replication",
};

static const size_t mysql_slave_worker_info_primary_key_column_indexes[] = {
    12U,
    0U,
};

static const struct mylite_execution_catalog_mysql_system_table
    mysql_replication_system_table_definitions[] = {
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_SLAVE_MASTER_INFO,
          "slave_master_info",
          mysql_slave_master_info_columns,
          sizeof(mysql_slave_master_info_columns) / sizeof(mysql_slave_master_info_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_master_info_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_master_info_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_master_info_column_privileges),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_master_info_column_comments),
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_SLAVE_RELAY_LOG_INFO,
          "slave_relay_log_info",
          mysql_slave_relay_log_info_columns,
          sizeof(mysql_slave_relay_log_info_columns) /
              sizeof(mysql_slave_relay_log_info_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_relay_log_info_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_relay_log_info_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_relay_log_info_column_privileges),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_relay_log_info_column_comments),
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_SLAVE_WORKER_INFO,
          "slave_worker_info",
          mysql_slave_worker_info_columns,
          sizeof(mysql_slave_worker_info_columns) / sizeof(mysql_slave_worker_info_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_worker_info_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_worker_info_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_worker_info_column_privileges),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_slave_worker_info_column_comments),
         mysql_slave_worker_info_primary_key_column_indexes,
         sizeof(mysql_slave_worker_info_primary_key_column_indexes) /
             sizeof(mysql_slave_worker_info_primary_key_column_indexes[0]),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
};

size_t mylite_execution_catalog_mysql_replication_system_table_definition_count(void) {
    return sizeof(mysql_replication_system_table_definitions) /
           sizeof(mysql_replication_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_mysql_replication_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_mysql_replication_system_table_definition_count()) {
        return NULL;
    }
    return &mysql_replication_system_table_definitions[index];
}
