#ifndef MYLITE_EXECUTION_SYSTEM_VARIABLES_H
#define MYLITE_EXECUTION_SYSTEM_VARIABLES_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

enum mylite_execution_system_variable_kind {
    MYLITE_EXECUTION_SYSTEM_VARIABLE_NONE = 0,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_WARNING_COUNT = 1,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ERROR_COUNT = 2,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CHARACTER_SET_CLIENT = 3,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CHARACTER_SET_CONNECTION = 4,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CHARACTER_SET_RESULTS = 5,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_COLLATION_CONNECTION = 6,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_VERSION = 7,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_VERSION_COMMENT = 8,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CHARACTER_SET_SERVER = 9,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_COLLATION_SERVER = 10,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CHARACTER_SET_DATABASE = 11,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_COLLATION_DATABASE = 12,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_DEFAULT_STORAGE_ENGINE = 13,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CHARACTER_SET_SYSTEM = 14,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CHARACTER_SET_FILESYSTEM = 15,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_AUTOCOMMIT = 16,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_QUOTE_SHOW_CREATE = 17,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_FOREIGN_KEY_CHECKS = 18,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_UNIQUE_CHECKS = 19,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_UPDATABLE_VIEWS_WITH_LIMIT = 20,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_AUTO_IS_NULL = 21,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_BIG_SELECTS = 22,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_GENERATE_INVISIBLE_PRIMARY_KEY = 23,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_SAFE_UPDATES = 24,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_WARNINGS = 25,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_SELECT_LIMIT = 26,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_NOTES = 27,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_BUFFER_RESULT = 28,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_LOG_BIN = 29,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_LOG_OFF = 30,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_MODE = 31,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_REQUIRE_PRIMARY_KEY = 32,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_REPLICA_SKIP_COUNTER = 33,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SQL_SLAVE_SKIP_COUNTER = 34,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_TIMESTAMP = 35,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SYSTEM_TIME_ZONE = 36,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_TIME_ZONE = 37,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_GTID_EXECUTED = 38,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_GTID_MODE = 39,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_GTID_OWNED = 40,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_GTID_PURGED = 41,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOWER_CASE_TABLE_NAMES = 42,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOWER_CASE_FILE_SYSTEM = 43,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MAX_ALLOWED_PACKET = 44,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_TRANSACTION_ISOLATION = 45,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_TRANSACTION_READ_ONLY = 46,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_AUTO_INCREMENT_INCREMENT = 47,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_AUTO_INCREMENT_OFFSET = 48,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_INTERACTIVE_TIMEOUT = 49,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_WAIT_TIMEOUT = 50,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_EXPLICIT_DEFAULTS_FOR_TIMESTAMP = 51,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_GROUP_CONCAT_MAX_LEN = 52,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_READ_ONLY = 53,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SUPER_READ_ONLY = 54,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_INNODB_READ_ONLY = 55,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_INFORMATION_SCHEMA_STATS_EXPIRY = 56,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_BIG_TABLES = 57,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_BIN = 58,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_BIN_BASENAME = 59,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_BIN_INDEX = 60,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_BIN_TRUST_FUNCTION_CREATORS = 61,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SERVER_ID = 62,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SERVER_ID_BITS = 63,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SERVER_UUID = 64,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_BASEDIR = 65,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_DATADIR = 66,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_HOSTNAME = 67,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LICENSE = 68,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_PID_FILE = 69,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_PLUGIN_DIR = 70,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_PORT = 71,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SOCKET = 72,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_PROTOCOL_VERSION = 73,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_VERSION_COMPILE_MACHINE = 74,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_VERSION_COMPILE_OS = 75,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_VERSION_COMPILE_ZLIB = 76,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_DEFAULT_TMP_STORAGE_ENGINE = 77,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_DEFAULT_COLLATION_FOR_UTF8MB4 = 78,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_END_MARKERS_IN_JSON = 79,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_KEEP_FILES_ON_CREATE = 80,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_OLD_ALTER_TABLE = 81,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_PRINT_IDENTIFIED_WITH_AS_HEX = 82,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_REQUIRE_ROW_FORMAT = 83,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_RESULTSET_METADATA = 84,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SELECT_INTO_DISK_SYNC = 85,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SESSION_TRACK_GTIDS = 86,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SESSION_TRACK_SCHEMA = 87,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SESSION_TRACK_STATE_CHANGE = 88,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SESSION_TRACK_TRANSACTION_INFO = 89,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SHOW_CREATE_TABLE_SKIP_SECONDARY_ENGINE = 90,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SHOW_CREATE_TABLE_VERBOSITY = 91,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_USE_SECONDARY_ENGINE = 92,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_REQUIRE_SECURE_TRANSPORT = 93,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SECURE_FILE_PRIV = 94,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SKIP_EXTERNAL_LOCKING = 95,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SKIP_NAME_RESOLVE = 96,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SKIP_NETWORKING = 97,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SKIP_SHOW_DATABASE = 98,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SSL_FIPS_MODE = 99,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SSL_SESSION_CACHE_MODE = 100,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SSL_SESSION_CACHE_TIMEOUT = 101,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_THREAD_HANDLING = 102,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_TLS_CERTIFICATES_ENFORCED_VALIDATION = 103,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_TLS_VERSION = 104,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_TMPDIR = 105,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_AUTHENTICATION_POLICY = 106,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CACHING_SHA2_PASSWORD_AUTO_GENERATE_RSA_KEYS = 107,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CACHING_SHA2_PASSWORD_DIGEST_ROUNDS = 108,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CACHING_SHA2_PASSWORD_PRIVATE_KEY_PATH = 109,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CACHING_SHA2_PASSWORD_PUBLIC_KEY_PATH = 110,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_DEFAULT_PASSWORD_LIFETIME = 111,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_DISCONNECT_ON_EXPIRED_PASSWORD = 112,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQL_NATIVE_PASSWORD_PROXY_USERS = 113,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_PASSWORD_HISTORY = 114,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_PASSWORD_REQUIRE_CURRENT = 115,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_PASSWORD_REUSE_INTERVAL = 116,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SHA256_PASSWORD_AUTO_GENERATE_RSA_KEYS = 117,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SHA256_PASSWORD_PRIVATE_KEY_PATH = 118,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SHA256_PASSWORD_PROXY_USERS = 119,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SHA256_PASSWORD_PUBLIC_KEY_PATH = 120,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_HAVE_COMPRESS = 121,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_HAVE_DYNAMIC_LOADING = 122,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_HAVE_GEOMETRY = 123,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_HAVE_PROFILING = 124,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_HAVE_QUERY_CACHE = 125,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_HAVE_RTREE_KEYS = 126,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_HAVE_STATEMENT_TIMEOUT = 127,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_HAVE_SYMLINK = 128,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MAX_ERROR_COUNT = 129,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_ADDRESS = 130,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_PORT = 131,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_SSL_CA = 132,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_SSL_CAPATH = 133,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_SSL_CERT = 134,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_SSL_CIPHER = 135,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_SSL_CRL = 136,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_SSL_CRLPATH = 137,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_SSL_KEY = 138,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_TLS_CIPHERSUITES = 139,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_ADMIN_TLS_VERSION = 140,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_CREATE_ADMIN_LISTENER_THREAD = 141,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_BIND_ADDRESS = 142,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_COMPRESSION_ALGORITHMS = 143,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_CONNECT_TIMEOUT = 144,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_DEFLATE_DEFAULT_COMPRESSION_LEVEL = 145,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_DEFLATE_MAX_CLIENT_COMPRESSION_LEVEL = 146,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_DOCUMENT_ID_UNIQUE_PREFIX = 147,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_ENABLE_HELLO_NOTICE = 148,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_IDLE_WORKER_THREAD_TIMEOUT = 149,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_INTERACTIVE_TIMEOUT = 150,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_LZ4_DEFAULT_COMPRESSION_LEVEL = 151,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_LZ4_MAX_CLIENT_COMPRESSION_LEVEL = 152,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_MAX_ALLOWED_PACKET = 153,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_MAX_CONNECTIONS = 154,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_MIN_WORKER_THREADS = 155,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_PORT = 156,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_PORT_OPEN_TIMEOUT = 157,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_READ_TIMEOUT = 158,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_SOCKET = 159,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_SSL_CA = 160,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_SSL_CAPATH = 161,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_SSL_CERT = 162,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_SSL_CIPHER = 163,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_SSL_CRL = 164,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_SSL_CRLPATH = 165,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_SSL_KEY = 166,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_WAIT_TIMEOUT = 167,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_WRITE_TIMEOUT = 168,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_ZSTD_DEFAULT_COMPRESSION_LEVEL = 169,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_MYSQLX_ZSTD_MAX_CLIENT_COMPRESSION_LEVEL = 170,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SSL_CA = 171,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SSL_CAPATH = 172,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SSL_CERT = 173,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SSL_CIPHER = 174,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SSL_CRL = 175,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SSL_CRLPATH = 176,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SSL_KEY = 177,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_TLS_CIPHERSUITES = 178,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_GENERAL_LOG = 179,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_GENERAL_LOG_FILE = 180,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_ERROR = 181,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_ERROR_SERVICES = 182,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_ERROR_SUPPRESSION_LIST = 183,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_ERROR_VERBOSITY = 184,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_OUTPUT = 185,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_QUERIES_NOT_USING_INDEXES = 186,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_RAW = 187,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_REPLICA_UPDATES = 188,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_SLAVE_UPDATES = 189,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_SLOW_ADMIN_STATEMENTS = 190,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_SLOW_EXTRA = 191,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_SLOW_REPLICA_STATEMENTS = 192,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_SLOW_SLAVE_STATEMENTS = 193,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_STATEMENTS_UNSAFE_FOR_BINLOG = 194,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_THROTTLE_QUERIES_NOT_USING_INDEXES = 195,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LOG_TIMESTAMPS = 196,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_LONG_QUERY_TIME = 197,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SLOW_QUERY_LOG = 198,
    MYLITE_EXECUTION_SYSTEM_VARIABLE_SLOW_QUERY_LOG_FILE = 199,
};

struct mylite_execution_system_variable_descriptor {
    const char *name;
    enum mylite_execution_system_variable_kind kind;
    bool show_session;
    bool show_global;
};

struct mylite_execution_show_status_descriptor {
    const char *name;
    const char *value;
    bool show_session;
    bool show_global;
};

size_t mylite_execution_system_variable_descriptor_count(void);
const struct mylite_execution_system_variable_descriptor *mylite_execution_system_variable_descriptor_at(
    size_t index
);
const struct mylite_execution_system_variable_descriptor *mylite_execution_system_variable_descriptor_by_name(
    const char *name
);
const struct mylite_execution_system_variable_descriptor *mylite_execution_system_variable_descriptor_by_kind(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_allows_global_scope(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_allows_session_scope(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_warns_on_scalar_read(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_fixed_boolean_value(
    enum mylite_execution_system_variable_kind kind,
    bool *out_value
);
bool mylite_execution_system_variable_is_global_read_only_toggle(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_read_only_server_identity_binary_log(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_read_only_server_build(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_read_only_server_environment(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_read_only_authentication_password(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_read_only_server_capability(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_read_only_admin_listener(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_read_only_mysqlx(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_read_only_server_logging(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_fixed_global_server_security(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_fixed_global_authentication_password(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_fixed_global_admin_listener(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_fixed_global_mysqlx(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_fixed_global_server_tls(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_fixed_global_server_logging(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_timeout(enum mylite_execution_system_variable_kind kind);
bool mylite_execution_system_variable_is_session_placeholder(
    enum mylite_execution_system_variable_kind kind
);
bool mylite_execution_system_variable_is_boolean_session_placeholder(
    enum mylite_execution_system_variable_kind kind
);
const char *mylite_execution_system_variable_default_value(
    enum mylite_execution_system_variable_kind kind
);

size_t mylite_execution_show_status_descriptor_count(void);
const struct mylite_execution_show_status_descriptor *mylite_execution_show_status_descriptor_at(
    size_t index
);

bool mylite_execution_sql_mode_token_matches(const char *text, size_t length, const char *expected);
int mylite_execution_sql_mode_parse(
    const char *text,
    uint64_t *out_modes,
    const char **out_invalid_token,
    size_t *out_invalid_token_length
);
int mylite_execution_sql_mode_format(uint64_t modes, char *buffer, size_t buffer_size);

#endif
