#include "mylite_execution_catalog_sys_summary_tables_internal.h"

static const struct mylite_execution_catalog_column_definition
    sys_innodb_buffer_stats_by_schema_columns[] = {
        {"object_schema",
         NULL,
         "YES",
         "text",
         "65535",
         "65535",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "text"},
        {"allocated",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"data",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"pages", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"pages_hashed", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"pages_old", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"rows_cached",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "45",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(45,0)"},
};

static const struct mylite_execution_catalog_column_definition
    sys_x_innodb_buffer_stats_by_schema_columns[] = {
        {"object_schema",
         NULL,
         "YES",
         "text",
         "65535",
         "65535",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "text"},
        {"allocated",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "44",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(44,0)"},
        {"data", NULL, "YES", "decimal", NULL, NULL, "44", "0", NULL, NULL, NULL, "decimal(44,0)"},
        {"pages", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"pages_hashed", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"pages_old", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"rows_cached",
         "0",
         "NO",
         "decimal",
         NULL,
         NULL,
         "45",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(45,0)"},
};

static const struct mylite_execution_catalog_column_definition
    sys_innodb_buffer_stats_by_table_columns[] = {
        {"object_schema",
         NULL,
         "YES",
         "text",
         "65535",
         "65535",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "text"},
        {"object_name",
         NULL,
         "YES",
         "text",
         "65535",
         "65535",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "text"},
        {"allocated",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"data",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"pages", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"pages_hashed", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"pages_old", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"rows_cached",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "45",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(45,0)"},
};

static const struct mylite_execution_catalog_column_definition
    sys_x_innodb_buffer_stats_by_table_columns[] = {
        {"object_schema",
         NULL,
         "YES",
         "text",
         "65535",
         "65535",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "text"},
        {"object_name",
         NULL,
         "YES",
         "text",
         "65535",
         "65535",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "text"},
        {"allocated",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "44",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(44,0)"},
        {"data", NULL, "YES", "decimal", NULL, NULL, "44", "0", NULL, NULL, NULL, "decimal(44,0)"},
        {"pages", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"pages_hashed", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"pages_old", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"rows_cached",
         "0",
         "NO",
         "decimal",
         NULL,
         NULL,
         "45",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(45,0)"},
};

static const char *const sys_innodb_buffer_stats_by_schema_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_innodb_buffer_stats_by_schema_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_innodb_buffer_stats_by_schema_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const char *const sys_innodb_buffer_stats_by_table_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_innodb_buffer_stats_by_table_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_innodb_buffer_stats_by_table_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition sys_innodb_lock_waits_columns[] = {
    {"wait_started", NULL, "YES", "datetime", NULL, NULL, NULL, NULL, "0", NULL, NULL, "datetime"},
    {"wait_age", NULL, "YES", "time", NULL, NULL, NULL, NULL, "0", NULL, NULL, "time"},
    {"wait_age_secs", NULL, "YES", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
    {"locked_table",
     NULL,
     "YES",
     "mediumtext",
     "16777215",
     "16777215",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "mediumtext"},
    {"locked_table_schema",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"locked_table_name",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"locked_table_partition",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"locked_table_subpartition",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"locked_index",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"locked_type",
     NULL,
     "NO",
     "varchar",
     "32",
     "128",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(32)"},
    {"waiting_trx_id",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"waiting_trx_started",
     "0000-00-00 00:00:00",
     "NO",
     "datetime",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "datetime"},
    {"waiting_trx_age", NULL, "YES", "time", NULL, NULL, NULL, NULL, "0", NULL, NULL, "time"},
    {"waiting_trx_rows_locked",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"waiting_trx_rows_modified",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"waiting_pid",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"waiting_query",
     NULL,
     "YES",
     "longtext",
     "4294967295",
     "4294967295",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "longtext"},
    {"waiting_lock_id",
     NULL,
     "NO",
     "varchar",
     "128",
     "512",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(128)"},
    {"waiting_lock_mode",
     NULL,
     "NO",
     "varchar",
     "32",
     "128",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(32)"},
    {"blocking_trx_id",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"blocking_pid",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"blocking_query",
     NULL,
     "YES",
     "longtext",
     "4294967295",
     "4294967295",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "longtext"},
    {"blocking_lock_id",
     NULL,
     "NO",
     "varchar",
     "128",
     "512",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(128)"},
    {"blocking_lock_mode",
     NULL,
     "NO",
     "varchar",
     "32",
     "128",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(32)"},
    {"blocking_trx_started",
     "0000-00-00 00:00:00",
     "NO",
     "datetime",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "datetime"},
    {"blocking_trx_age", NULL, "YES", "time", NULL, NULL, NULL, NULL, "0", NULL, NULL, "time"},
    {"blocking_trx_rows_locked",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"blocking_trx_rows_modified",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"sql_kill_blocking_query",
     "",
     "NO",
     "varchar",
     "33",
     "132",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(33)"},
    {"sql_kill_blocking_connection",
     "",
     "NO",
     "varchar",
     "27",
     "108",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(27)"},
};

static const struct mylite_execution_catalog_column_definition sys_x_innodb_lock_waits_columns[] = {
    {"wait_started", NULL, "YES", "datetime", NULL, NULL, NULL, NULL, "0", NULL, NULL, "datetime"},
    {"wait_age", NULL, "YES", "time", NULL, NULL, NULL, NULL, "0", NULL, NULL, "time"},
    {"wait_age_secs", NULL, "YES", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
    {"locked_table",
     NULL,
     "YES",
     "mediumtext",
     "16777215",
     "16777215",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "mediumtext"},
    {"locked_table_schema",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"locked_table_name",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"locked_table_partition",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"locked_table_subpartition",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"locked_index",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"locked_type",
     NULL,
     "NO",
     "varchar",
     "32",
     "128",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(32)"},
    {"waiting_trx_id",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"waiting_trx_started",
     "0000-00-00 00:00:00",
     "NO",
     "datetime",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "datetime"},
    {"waiting_trx_age", NULL, "YES", "time", NULL, NULL, NULL, NULL, "0", NULL, NULL, "time"},
    {"waiting_trx_rows_locked",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"waiting_trx_rows_modified",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"waiting_pid",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"waiting_query",
     NULL,
     "YES",
     "varchar",
     "1024",
     "3072",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(1024)"},
    {"waiting_lock_id",
     NULL,
     "NO",
     "varchar",
     "128",
     "512",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(128)"},
    {"waiting_lock_mode",
     NULL,
     "NO",
     "varchar",
     "32",
     "128",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(32)"},
    {"blocking_trx_id",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"blocking_pid",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"blocking_query",
     NULL,
     "YES",
     "varchar",
     "1024",
     "3072",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(1024)"},
    {"blocking_lock_id",
     NULL,
     "NO",
     "varchar",
     "128",
     "512",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(128)"},
    {"blocking_lock_mode",
     NULL,
     "NO",
     "varchar",
     "32",
     "128",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(32)"},
    {"blocking_trx_started",
     "0000-00-00 00:00:00",
     "NO",
     "datetime",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "datetime"},
    {"blocking_trx_age", NULL, "YES", "time", NULL, NULL, NULL, NULL, "0", NULL, NULL, "time"},
    {"blocking_trx_rows_locked",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"blocking_trx_rows_modified",
     "0",
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"sql_kill_blocking_query",
     "",
     "NO",
     "varchar",
     "33",
     "132",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(33)"},
    {"sql_kill_blocking_connection",
     "",
     "NO",
     "varchar",
     "27",
     "108",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(27)"},
};

static const char *const sys_innodb_lock_waits_column_keys[] = {
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
};

static const char *const sys_innodb_lock_waits_column_extras[] = {
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
};

static const char *const sys_innodb_lock_waits_column_privileges[] = {
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_table
    sys_summary_innodb_system_table_definitions[] = {
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_INNODB_BUFFER_STATS_BY_SCHEMA,
          "innodb_buffer_stats_by_schema",
          sys_innodb_buffer_stats_by_schema_columns,
          sizeof(sys_innodb_buffer_stats_by_schema_columns) /
              sizeof(sys_innodb_buffer_stats_by_schema_columns[0])},
         sys_innodb_buffer_stats_by_schema_column_keys,
         sys_innodb_buffer_stats_by_schema_column_extras,
         sys_innodb_buffer_stats_by_schema_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_INNODB_BUFFER_STATS_BY_TABLE,
          "innodb_buffer_stats_by_table",
          sys_innodb_buffer_stats_by_table_columns,
          sizeof(sys_innodb_buffer_stats_by_table_columns) /
              sizeof(sys_innodb_buffer_stats_by_table_columns[0])},
         sys_innodb_buffer_stats_by_table_column_keys,
         sys_innodb_buffer_stats_by_table_column_extras,
         sys_innodb_buffer_stats_by_table_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_INNODB_LOCK_WAITS,
          "innodb_lock_waits",
          sys_innodb_lock_waits_columns,
          sizeof(sys_innodb_lock_waits_columns) / sizeof(sys_innodb_lock_waits_columns[0])},
         sys_innodb_lock_waits_column_keys,
         sys_innodb_lock_waits_column_extras,
         sys_innodb_lock_waits_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
};

size_t mylite_execution_catalog_sys_summary_innodb_system_table_definition_count(void) {
    return sizeof(sys_summary_innodb_system_table_definitions) /
           sizeof(sys_summary_innodb_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_sys_summary_innodb_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_sys_summary_innodb_system_table_definition_count()) {
        return NULL;
    }
    return &sys_summary_innodb_system_table_definitions[index];
}

static const struct mylite_execution_catalog_mysql_system_table
    sys_summary_innodb_x_system_table_definitions[] = {
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_INNODB_BUFFER_STATS_BY_SCHEMA,
          "x$innodb_buffer_stats_by_schema",
          sys_x_innodb_buffer_stats_by_schema_columns,
          sizeof(sys_x_innodb_buffer_stats_by_schema_columns) /
              sizeof(sys_x_innodb_buffer_stats_by_schema_columns[0])},
         sys_innodb_buffer_stats_by_schema_column_keys,
         sys_innodb_buffer_stats_by_schema_column_extras,
         sys_innodb_buffer_stats_by_schema_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_INNODB_BUFFER_STATS_BY_TABLE,
          "x$innodb_buffer_stats_by_table",
          sys_x_innodb_buffer_stats_by_table_columns,
          sizeof(sys_x_innodb_buffer_stats_by_table_columns) /
              sizeof(sys_x_innodb_buffer_stats_by_table_columns[0])},
         sys_innodb_buffer_stats_by_table_column_keys,
         sys_innodb_buffer_stats_by_table_column_extras,
         sys_innodb_buffer_stats_by_table_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_INNODB_LOCK_WAITS,
          "x$innodb_lock_waits",
          sys_x_innodb_lock_waits_columns,
          sizeof(sys_x_innodb_lock_waits_columns) / sizeof(sys_x_innodb_lock_waits_columns[0])},
         sys_innodb_lock_waits_column_keys,
         sys_innodb_lock_waits_column_extras,
         sys_innodb_lock_waits_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
};

size_t mylite_execution_catalog_sys_summary_innodb_x_system_table_definition_count(void) {
    return sizeof(sys_summary_innodb_x_system_table_definitions) /
           sizeof(sys_summary_innodb_x_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_sys_summary_innodb_x_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_sys_summary_innodb_x_system_table_definition_count()) {
        return NULL;
    }
    return &sys_summary_innodb_x_system_table_definitions[index];
}
