#include "mylite_execution_catalog_sys_summary_tables_internal.h"

static const struct mylite_execution_catalog_column_definition sys_host_summary_columns[] = {
    {"host",
     NULL,
     "YES",
     "varchar",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "varchar(255)"},
    {"statements", NULL, "YES", "decimal", NULL, NULL, "64", "0", NULL, NULL, NULL, "decimal(64,0)"
    },
    {"statement_latency",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
    {"statement_avg_latency",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
    {"table_scans", NULL, "YES", "decimal", NULL, NULL, "65", "0", NULL, NULL, NULL, "decimal(65,0)"
    },
    {"file_ios", NULL, "YES", "decimal", NULL, NULL, "64", "0", NULL, NULL, NULL, "decimal(64,0)"},
    {"file_io_latency",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
    {"current_connections",
     NULL,
     "YES",
     "decimal",
     NULL,
     NULL,
     "41",
     "0",
     NULL,
     NULL,
     NULL,
     "decimal(41,0)"},
    {"total_connections",
     NULL,
     "YES",
     "decimal",
     NULL,
     NULL,
     "41",
     "0",
     NULL,
     NULL,
     NULL,
     "decimal(41,0)"},
    {"unique_users", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
    {"current_memory",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
    {"total_memory_allocated",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
};

static const struct mylite_execution_catalog_column_definition sys_x_host_summary_columns[] = {
    {"host",
     NULL,
     "YES",
     "varchar",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "varchar(255)"},
    {"statements", NULL, "YES", "decimal", NULL, NULL, "64", "0", NULL, NULL, NULL, "decimal(64,0)"
    },
    {"statement_latency",
     NULL,
     "YES",
     "decimal",
     NULL,
     NULL,
     "64",
     "0",
     NULL,
     NULL,
     NULL,
     "decimal(64,0)"},
    {"statement_avg_latency",
     NULL,
     "YES",
     "decimal",
     NULL,
     NULL,
     "65",
     "4",
     NULL,
     NULL,
     NULL,
     "decimal(65,4)"},
    {"table_scans", NULL, "YES", "decimal", NULL, NULL, "65", "0", NULL, NULL, NULL, "decimal(65,0)"
    },
    {"file_ios", NULL, "YES", "decimal", NULL, NULL, "64", "0", NULL, NULL, NULL, "decimal(64,0)"},
    {"file_io_latency",
     NULL,
     "YES",
     "decimal",
     NULL,
     NULL,
     "64",
     "0",
     NULL,
     NULL,
     NULL,
     "decimal(64,0)"},
    {"current_connections",
     NULL,
     "YES",
     "decimal",
     NULL,
     NULL,
     "41",
     "0",
     NULL,
     NULL,
     NULL,
     "decimal(41,0)"},
    {"total_connections",
     NULL,
     "YES",
     "decimal",
     NULL,
     NULL,
     "41",
     "0",
     NULL,
     NULL,
     NULL,
     "decimal(41,0)"},
    {"unique_users", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
    {"current_memory",
     NULL,
     "YES",
     "decimal",
     NULL,
     NULL,
     "63",
     "0",
     NULL,
     NULL,
     NULL,
     "decimal(63,0)"},
    {"total_memory_allocated",
     NULL,
     "YES",
     "decimal",
     NULL,
     NULL,
     "64",
     "0",
     NULL,
     NULL,
     NULL,
     "decimal(64,0)"},
};

static const char *const sys_host_summary_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_host_summary_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_host_summary_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    sys_host_summary_by_file_io_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"ios", NULL, "YES", "decimal", NULL, NULL, "42", "0", NULL, NULL, NULL, "decimal(42,0)"},
        {"io_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
};

static const struct mylite_execution_catalog_column_definition
    sys_x_host_summary_by_file_io_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"ios", NULL, "YES", "decimal", NULL, NULL, "42", "0", NULL, NULL, NULL, "decimal(42,0)"},
        {"io_latency",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
};

static const char *const sys_host_summary_by_file_io_column_keys[] = {
    "",
    "",
    "",
};

static const char *const sys_host_summary_by_file_io_column_extras[] = {
    "",
    "",
    "",
};

static const char *const sys_host_summary_by_file_io_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    sys_host_summary_by_file_io_type_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"event_name",
         NULL,
         "NO",
         "varchar",
         "128",
         "512",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(128)"},
        {"total", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
        {"total_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"max_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
};

static const struct mylite_execution_catalog_column_definition
    sys_x_host_summary_by_file_io_type_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"event_name",
         NULL,
         "NO",
         "varchar",
         "128",
         "512",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(128)"},
        {"total", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
        {"total_latency",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"max_latency",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const char *const sys_host_summary_by_file_io_type_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_host_summary_by_file_io_type_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_host_summary_by_file_io_type_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    sys_host_summary_by_stages_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"event_name",
         NULL,
         "NO",
         "varchar",
         "128",
         "512",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(128)"},
        {"total", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
        {"total_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"avg_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
};

static const struct mylite_execution_catalog_column_definition
    sys_x_host_summary_by_stages_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"event_name",
         NULL,
         "NO",
         "varchar",
         "128",
         "512",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(128)"},
        {"total", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
        {"total_latency",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"avg_latency",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const char *const sys_host_summary_by_stages_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_host_summary_by_stages_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_host_summary_by_stages_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    sys_host_summary_by_statement_latency_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"total", NULL, "YES", "decimal", NULL, NULL, "42", "0", NULL, NULL, NULL, "decimal(42,0)"},
        {"total_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"max_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"lock_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"cpu_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"rows_sent",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
        {"rows_examined",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
        {"rows_affected",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
        {"full_scans",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "43",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(43,0)"},
};

static const struct mylite_execution_catalog_column_definition
    sys_x_host_summary_by_statement_latency_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"total", NULL, "YES", "decimal", NULL, NULL, "42", "0", NULL, NULL, NULL, "decimal(42,0)"},
        {"total_latency",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
        {"max_latency",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"lock_latency",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
        {"cpu_latency",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
        {"rows_sent",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
        {"rows_examined",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
        {"rows_affected",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
        {"full_scans",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "43",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(43,0)"},
};

static const char *const sys_host_summary_by_statement_latency_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_host_summary_by_statement_latency_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_host_summary_by_statement_latency_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    sys_host_summary_by_statement_type_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"statement",
         NULL,
         "YES",
         "varchar",
         "128",
         "512",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(128)"},
        {"total", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
        {"total_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"max_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"lock_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"cpu_latency",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"rows_sent",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"rows_examined",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"rows_affected",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"full_scans",
         "0",
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const struct mylite_execution_catalog_column_definition
    sys_x_host_summary_by_statement_type_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"statement",
         NULL,
         "YES",
         "varchar",
         "128",
         "512",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(128)"},
        {"total", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
        {"total_latency",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"max_latency",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"lock_latency",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"cpu_latency",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"rows_sent",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"rows_examined",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"rows_affected",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"full_scans",
         "0",
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const char *const sys_host_summary_by_statement_type_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_host_summary_by_statement_type_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_host_summary_by_statement_type_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_table
    sys_summary_host_system_table_definitions[] = {
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_HOST_SUMMARY,
          "host_summary",
          sys_host_summary_columns,
          sizeof(sys_host_summary_columns) / sizeof(sys_host_summary_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_HOST_SUMMARY_BY_FILE_IO,
          "host_summary_by_file_io",
          sys_host_summary_by_file_io_columns,
          sizeof(sys_host_summary_by_file_io_columns) /
              sizeof(sys_host_summary_by_file_io_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_HOST_SUMMARY_BY_FILE_IO_TYPE,
          "host_summary_by_file_io_type",
          sys_host_summary_by_file_io_type_columns,
          sizeof(sys_host_summary_by_file_io_type_columns) /
              sizeof(sys_host_summary_by_file_io_type_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_type_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_type_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_type_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_HOST_SUMMARY_BY_STAGES,
          "host_summary_by_stages",
          sys_host_summary_by_stages_columns,
          sizeof(sys_host_summary_by_stages_columns) / sizeof(sys_host_summary_by_stages_columns[0])
         },
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_stages_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_stages_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_stages_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_HOST_SUMMARY_BY_STATEMENT_LATENCY,
          "host_summary_by_statement_latency",
          sys_host_summary_by_statement_latency_columns,
          sizeof(sys_host_summary_by_statement_latency_columns) /
              sizeof(sys_host_summary_by_statement_latency_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_latency_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_latency_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_latency_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_HOST_SUMMARY_BY_STATEMENT_TYPE,
          "host_summary_by_statement_type",
          sys_host_summary_by_statement_type_columns,
          sizeof(sys_host_summary_by_statement_type_columns) /
              sizeof(sys_host_summary_by_statement_type_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_type_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_type_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_type_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
};

size_t mylite_execution_catalog_sys_summary_host_system_table_definition_count(void) {
    return sizeof(sys_summary_host_system_table_definitions) /
           sizeof(sys_summary_host_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_sys_summary_host_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_sys_summary_host_system_table_definition_count()) {
        return NULL;
    }
    return &sys_summary_host_system_table_definitions[index];
}

static const struct mylite_execution_catalog_mysql_system_table
    sys_summary_host_x_system_table_definitions[] = {
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_HOST_SUMMARY,
          "x$host_summary",
          sys_x_host_summary_columns,
          sizeof(sys_x_host_summary_columns) / sizeof(sys_x_host_summary_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_HOST_SUMMARY_BY_FILE_IO,
          "x$host_summary_by_file_io",
          sys_x_host_summary_by_file_io_columns,
          sizeof(sys_x_host_summary_by_file_io_columns) /
              sizeof(sys_x_host_summary_by_file_io_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_HOST_SUMMARY_BY_FILE_IO_TYPE,
          "x$host_summary_by_file_io_type",
          sys_x_host_summary_by_file_io_type_columns,
          sizeof(sys_x_host_summary_by_file_io_type_columns) /
              sizeof(sys_x_host_summary_by_file_io_type_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_type_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_type_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_file_io_type_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_HOST_SUMMARY_BY_STAGES,
          "x$host_summary_by_stages",
          sys_x_host_summary_by_stages_columns,
          sizeof(sys_x_host_summary_by_stages_columns) /
              sizeof(sys_x_host_summary_by_stages_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_stages_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_stages_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_stages_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_HOST_SUMMARY_BY_STATEMENT_LATENCY,
          "x$host_summary_by_statement_latency",
          sys_x_host_summary_by_statement_latency_columns,
          sizeof(sys_x_host_summary_by_statement_latency_columns) /
              sizeof(sys_x_host_summary_by_statement_latency_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_latency_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_latency_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_latency_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_HOST_SUMMARY_BY_STATEMENT_TYPE,
          "x$host_summary_by_statement_type",
          sys_x_host_summary_by_statement_type_columns,
          sizeof(sys_x_host_summary_by_statement_type_columns) /
              sizeof(sys_x_host_summary_by_statement_type_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_type_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_type_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(sys_host_summary_by_statement_type_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
};

size_t mylite_execution_catalog_sys_summary_host_x_system_table_definition_count(void) {
    return sizeof(sys_summary_host_x_system_table_definitions) /
           sizeof(sys_summary_host_x_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_sys_summary_host_x_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_sys_summary_host_x_system_table_definition_count()) {
        return NULL;
    }
    return &sys_summary_host_x_system_table_definitions[index];
}
