#include "mylite_execution_catalog_system_tables_internal.h"

static const struct mylite_execution_catalog_column_definition mysql_user_columns[] = {
    {"Host",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"User", "", "NO", "char", "32", "96", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(32)"},
    {"Select_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Insert_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Update_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Delete_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Drop_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Reload_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Shutdown_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Process_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"File_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Grant_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"References_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Index_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Alter_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Show_db_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Super_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_tmp_table_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Lock_tables_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Execute_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Repl_slave_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Repl_client_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_view_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Show_view_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_routine_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Alter_routine_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_user_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Event_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Trigger_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_tablespace_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"ssl_type",
     "",
     "NO",
     "enum",
     "9",
     "27",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('','ANY','X509','SPECIFIED')"},
    {"ssl_cipher", NULL, "NO", "blob", "65535", "65535", NULL, NULL, NULL, NULL, NULL, "blob"},
    {"x509_issuer", NULL, "NO", "blob", "65535", "65535", NULL, NULL, NULL, NULL, NULL, "blob"},
    {"x509_subject", NULL, "NO", "blob", "65535", "65535", NULL, NULL, NULL, NULL, NULL, "blob"},
    {"max_questions", "0", "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"max_updates", "0", "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"max_connections", "0", "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"max_user_connections",
     "0",
     "NO",
     "int",
     NULL,
     NULL,
     "10",
     "0",
     NULL,
     NULL,
     NULL,
     "int unsigned"},
    {"plugin",
     "caching_sha2_password",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "char(64)"},
    {"authentication_string",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
    {"password_expired",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"password_last_changed",
     NULL,
     "YES",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "timestamp"},
    {"password_lifetime",
     NULL,
     "YES",
     "smallint",
     NULL,
     NULL,
     "5",
     "0",
     NULL,
     NULL,
     NULL,
     "smallint unsigned"},
    {"account_locked",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_role_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Drop_role_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Password_reuse_history",
     NULL,
     "YES",
     "smallint",
     NULL,
     NULL,
     "5",
     "0",
     NULL,
     NULL,
     NULL,
     "smallint unsigned"},
    {"Password_reuse_time",
     NULL,
     "YES",
     "smallint",
     NULL,
     NULL,
     "5",
     "0",
     NULL,
     NULL,
     NULL,
     "smallint unsigned"},
    {"Password_require_current",
     NULL,
     "YES",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"User_attributes", NULL, "YES", "json", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "json"},
};

static const char *const mysql_user_column_keys[] = {
    "PRI", "PRI", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "",    "",    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "",    "",    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
};

static const char *const mysql_user_column_extras[] = {
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
};

static const char *const mysql_user_column_privileges[] = {
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_global_grants_columns[] = {
    {"USER", "", "NO", "char", "32", "96", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(32)"},
    {"HOST",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"PRIV",
     "",
     "NO",
     "char",
     "32",
     "96",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(32)"},
    {"WITH_GRANT_OPTION",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
};

static const char *const mysql_global_grants_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "",
};

static const char *const mysql_global_grants_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const mysql_global_grants_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_db_columns[] = {
    {"Host",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"Db", "", "NO", "char", "64", "192", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(64)"},
    {"User", "", "NO", "char", "32", "96", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(32)"},
    {"Select_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Insert_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Update_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Delete_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Drop_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Grant_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"References_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Index_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Alter_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_tmp_table_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Lock_tables_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_view_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Show_view_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Create_routine_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Alter_routine_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Execute_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Event_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
    {"Trigger_priv",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
};

static const char *const mysql_db_column_keys[] = {
    "PRI", "PRI", "PRI", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
};

static const char *const mysql_db_column_extras[] = {
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
};

static const char *const mysql_db_column_privileges[] = {
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
};

static const size_t mysql_db_primary_key_column_indexes[] = {
    0U,
    2U,
    1U,
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    mysql_db_secondary_indexes[] = {
        {"User", 2U, "2", "1", false, "A", "BTREE"},
};

static const struct mylite_execution_catalog_column_definition mysql_tables_priv_columns[] = {
    {"Host",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"Db", "", "NO", "char", "64", "192", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(64)"},
    {"User", "", "NO", "char", "32", "96", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(32)"},
    {"Table_name",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "char(64)"},
    {"Grantor",
     "",
     "NO",
     "varchar",
     "288",
     "864",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "varchar(288)"},
    {"Timestamp",
     "CURRENT_TIMESTAMP",
     "NO",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "timestamp"},
    {"Table_priv",
     "",
     "NO",
     "set",
     "98",
     "294",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "set('Select','Insert','Update','Delete','Create','Drop','Grant','References','Index','Alter',"
     "'Create View','Show view','Trigger')"},
    {"Column_priv",
     "",
     "NO",
     "set",
     "31",
     "93",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "set('Select','Insert','Update','References')"},
};

static const char *const mysql_tables_priv_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "PRI",
    "MUL",
    "",
    "",
    "",
};

static const char *const mysql_tables_priv_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
    "",
    "",
};

static const char *const mysql_tables_priv_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t mysql_tables_priv_primary_key_column_indexes[] = {
    0U,
    2U,
    1U,
    3U,
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    mysql_tables_priv_secondary_indexes[] = {
        {"Grantor", 4U, "2", "1", false, "A", "BTREE"},
};

static const struct mylite_execution_catalog_column_definition mysql_columns_priv_columns[] = {
    {"Host",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"Db", "", "NO", "char", "64", "192", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(64)"},
    {"User", "", "NO", "char", "32", "96", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(32)"},
    {"Table_name",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "char(64)"},
    {"Column_name",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "char(64)"},
    {"Timestamp",
     "CURRENT_TIMESTAMP",
     "NO",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "timestamp"},
    {"Column_priv",
     "",
     "NO",
     "set",
     "31",
     "93",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "set('Select','Insert','Update','References')"},
};

static const char *const mysql_columns_priv_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "PRI",
    "PRI",
    "",
    "",
};

static const char *const mysql_columns_priv_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
    "",
};

static const char *const mysql_columns_priv_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t mysql_columns_priv_primary_key_column_indexes[] = {
    0U,
    2U,
    1U,
    3U,
    4U,
};

static const struct mylite_execution_catalog_column_definition mysql_procs_priv_columns[] = {
    {"Host",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"Db", "", "NO", "char", "64", "192", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(64)"},
    {"User", "", "NO", "char", "32", "96", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(32)"},
    {"Routine_name",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
    {"Routine_type",
     NULL,
     "NO",
     "enum",
     "9",
     "27",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "enum('FUNCTION','PROCEDURE')"},
    {"Grantor",
     "",
     "NO",
     "varchar",
     "288",
     "864",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "varchar(288)"},
    {"Proc_priv",
     "",
     "NO",
     "set",
     "27",
     "81",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "set('Execute','Alter Routine','Grant')"},
    {"Timestamp",
     "CURRENT_TIMESTAMP",
     "NO",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "timestamp"},
};

static const char *const mysql_procs_priv_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "PRI",
    "PRI",
    "MUL",
    "",
    "",
};

static const char *const mysql_procs_priv_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
};

static const char *const mysql_procs_priv_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t mysql_procs_priv_primary_key_column_indexes[] = {
    0U,
    2U,
    1U,
    3U,
    4U,
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    mysql_procs_priv_secondary_indexes[] = {
        {"Grantor", 5U, "0", "1", false, "A", "BTREE"},
};

static const struct mylite_execution_catalog_column_definition mysql_proxies_priv_columns[] = {
    {"Host",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"User", "", "NO", "char", "32", "96", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(32)"},
    {"Proxied_host",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"Proxied_user",
     "",
     "NO",
     "char",
     "32",
     "96",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "char(32)"},
    {"With_grant", "0", "NO", "tinyint", NULL, NULL, "3", "0", NULL, NULL, NULL, "tinyint(1)"},
    {"Grantor",
     "",
     "NO",
     "varchar",
     "288",
     "864",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "varchar(288)"},
    {"Timestamp",
     "CURRENT_TIMESTAMP",
     "NO",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "timestamp"},
};

static const char *const mysql_proxies_priv_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "PRI",
    "",
    "MUL",
    "",
};

static const char *const mysql_proxies_priv_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
};

static const char *const mysql_proxies_priv_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t mysql_proxies_priv_primary_key_column_indexes[] = {
    0U,
    1U,
    2U,
    3U,
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    mysql_proxies_priv_secondary_indexes[] = {
        {"Grantor", 5U, "1", "1", false, "A", "BTREE"},
};

static const struct mylite_execution_catalog_column_definition mysql_default_roles_columns[] = {
    {"HOST",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"USER", "", "NO", "char", "32", "96", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(32)"},
    {"DEFAULT_ROLE_HOST",
     "%",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"DEFAULT_ROLE_USER",
     "",
     "NO",
     "char",
     "32",
     "96",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "char(32)"},
};

static const char *const mysql_default_roles_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "PRI",
};

static const char *const mysql_default_roles_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const mysql_default_roles_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t mysql_default_roles_primary_key_column_indexes[] = {
    0U,
    1U,
    2U,
    3U,
};

static const struct mylite_execution_catalog_column_definition mysql_role_edges_columns[] = {
    {"FROM_HOST",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"FROM_USER",
     "",
     "NO",
     "char",
     "32",
     "96",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "char(32)"},
    {"TO_HOST",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"TO_USER", "", "NO", "char", "32", "96", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(32)"
    },
    {"WITH_ADMIN_OPTION",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('N','Y')"},
};

static const char *const mysql_role_edges_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "PRI",
    "",
};

static const char *const mysql_role_edges_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_role_edges_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t mysql_role_edges_primary_key_column_indexes[] = {
    0U,
    1U,
    2U,
    3U,
};

static const struct mylite_execution_catalog_column_definition mysql_password_history_columns[] = {
    {"Host",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"User", "", "NO", "char", "32", "96", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(32)"},
    {"Password_timestamp",
     "CURRENT_TIMESTAMP(6)",
     "NO",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "6",
     NULL,
     NULL,
     "timestamp(6)"},
    {"Password",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_bin",
     "text"},
};

static const char *const mysql_password_history_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "",
};

static const char *const mysql_password_history_column_extras[] = {
    "",
    "",
    "DEFAULT_GENERATED",
    "",
};

static const char *const mysql_password_history_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t mysql_password_history_primary_key_column_indexes[] = {
    0U,
    1U,
    2U,
};

static const struct mylite_execution_catalog_mysql_system_table
    mysql_auth_system_table_definitions[] = {
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_USER,
          "user",
          mysql_user_columns,
          sizeof(mysql_user_columns) / sizeof(mysql_user_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_user_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_user_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_user_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_GLOBAL_GRANTS,
          "global_grants",
          mysql_global_grants_columns,
          sizeof(mysql_global_grants_columns) / sizeof(mysql_global_grants_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_global_grants_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_global_grants_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_global_grants_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_DB,
          "db",
          mysql_db_columns,
          sizeof(mysql_db_columns) / sizeof(mysql_db_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_db_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_db_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_db_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_db_primary_key_column_indexes,
         sizeof(mysql_db_primary_key_column_indexes) /
             sizeof(mysql_db_primary_key_column_indexes[0]),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_db_secondary_indexes,
         sizeof(mysql_db_secondary_indexes) / sizeof(mysql_db_secondary_indexes[0])},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_TABLES_PRIV,
          "tables_priv",
          mysql_tables_priv_columns,
          sizeof(mysql_tables_priv_columns) / sizeof(mysql_tables_priv_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_tables_priv_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_tables_priv_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_tables_priv_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_tables_priv_primary_key_column_indexes,
         sizeof(mysql_tables_priv_primary_key_column_indexes) /
             sizeof(mysql_tables_priv_primary_key_column_indexes[0]),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_tables_priv_secondary_indexes,
         sizeof(mysql_tables_priv_secondary_indexes) /
             sizeof(mysql_tables_priv_secondary_indexes[0])},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_COLUMNS_PRIV,
          "columns_priv",
          mysql_columns_priv_columns,
          sizeof(mysql_columns_priv_columns) / sizeof(mysql_columns_priv_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_columns_priv_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_columns_priv_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_columns_priv_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_columns_priv_primary_key_column_indexes,
         sizeof(mysql_columns_priv_primary_key_column_indexes) /
             sizeof(mysql_columns_priv_primary_key_column_indexes[0]),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_PROCS_PRIV,
          "procs_priv",
          mysql_procs_priv_columns,
          sizeof(mysql_procs_priv_columns) / sizeof(mysql_procs_priv_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_procs_priv_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_procs_priv_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_procs_priv_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_procs_priv_primary_key_column_indexes,
         sizeof(mysql_procs_priv_primary_key_column_indexes) /
             sizeof(mysql_procs_priv_primary_key_column_indexes[0]),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_procs_priv_secondary_indexes,
         sizeof(mysql_procs_priv_secondary_indexes) / sizeof(mysql_procs_priv_secondary_indexes[0])
        },
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_PROXIES_PRIV,
          "proxies_priv",
          mysql_proxies_priv_columns,
          sizeof(mysql_proxies_priv_columns) / sizeof(mysql_proxies_priv_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_proxies_priv_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_proxies_priv_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_proxies_priv_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_proxies_priv_primary_key_column_indexes,
         sizeof(mysql_proxies_priv_primary_key_column_indexes) /
             sizeof(mysql_proxies_priv_primary_key_column_indexes[0]),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_proxies_priv_secondary_indexes,
         sizeof(mysql_proxies_priv_secondary_indexes) /
             sizeof(mysql_proxies_priv_secondary_indexes[0])},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_DEFAULT_ROLES,
          "default_roles",
          mysql_default_roles_columns,
          sizeof(mysql_default_roles_columns) / sizeof(mysql_default_roles_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_default_roles_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_default_roles_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_default_roles_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_default_roles_primary_key_column_indexes,
         sizeof(mysql_default_roles_primary_key_column_indexes) /
             sizeof(mysql_default_roles_primary_key_column_indexes[0]),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_ROLE_EDGES,
          "role_edges",
          mysql_role_edges_columns,
          sizeof(mysql_role_edges_columns) / sizeof(mysql_role_edges_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_role_edges_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_role_edges_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_role_edges_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_role_edges_primary_key_column_indexes,
         sizeof(mysql_role_edges_primary_key_column_indexes) /
             sizeof(mysql_role_edges_primary_key_column_indexes[0]),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_PASSWORD_HISTORY,
          "password_history",
          mysql_password_history_columns,
          sizeof(mysql_password_history_columns) / sizeof(mysql_password_history_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_password_history_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_password_history_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_password_history_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         mysql_password_history_primary_key_column_indexes,
         sizeof(mysql_password_history_primary_key_column_indexes) /
             sizeof(mysql_password_history_primary_key_column_indexes[0]),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
};

size_t mylite_execution_catalog_mysql_auth_system_table_definition_count(void) {
    return sizeof(mysql_auth_system_table_definitions) /
           sizeof(mysql_auth_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_mysql_auth_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_mysql_auth_system_table_definition_count()) {
        return NULL;
    }
    return &mysql_auth_system_table_definitions[index];
}
