#include "mylite_collation.h"

#include <mylite/mylite.h>

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* Generated by SQLite from the checked-in Unicode 6.1 data files. */
int sqlite3FtsUnicodeFold(int codepoint, int remove_diacritic);

enum mylite_collation_level {
    MYLITE_COLLATION_LEVEL_PRIMARY = 0,
    MYLITE_COLLATION_LEVEL_SECONDARY = 1,
    MYLITE_COLLATION_LEVEL_TERTIARY = 2,
};

enum {
    invalid_utf8_weight_base = 0x110000,
    compatibility_secondary_weight_base = 0x120000,
    ascii_code_point_limit = 0x80,
};

static const uint32_t collation_key_level_separator = UINT32_MAX;

struct mylite_collation_iterator {
    const unsigned char *text;
    size_t size;
    size_t offset;
    uint32_t pending[3];
    size_t pending_count;
    size_t pending_index;
    enum mylite_collation_level level;
};

struct mylite_collation_key_builder {
    unsigned char *bytes;
    size_t size;
    size_t capacity;
};

static int compare_binary(
    const unsigned char *left,
    size_t left_size,
    const unsigned char *right,
    size_t right_size
);
static bool compare_ascii(
    enum mylite_collation_kind kind,
    const unsigned char *left,
    size_t left_size,
    const unsigned char *right,
    size_t right_size,
    int *out_result
);
static int compare_unicode_level(
    enum mylite_collation_level level,
    const unsigned char *left,
    size_t left_size,
    const unsigned char *right,
    size_t right_size
);
static bool collation_iterator_next(
    struct mylite_collation_iterator *iterator,
    uint32_t *out_weight
);
static bool collation_primary_weight(
    struct mylite_collation_iterator *iterator,
    uint32_t codepoint,
    uint32_t *out_weight
);
static bool collation_secondary_weight(
    struct mylite_collation_iterator *iterator,
    uint32_t codepoint,
    uint32_t *out_weight
);
static bool collation_tertiary_weight(uint32_t codepoint, uint32_t *out_weight);
static size_t collation_primary_expansion(uint32_t codepoint, uint32_t out_codepoints[3]);
static uint32_t collation_canonical_accent(uint32_t codepoint);
static bool collation_codepoint_is_combining_mark(uint32_t codepoint);
static bool decode_utf8_codepoint(
    const unsigned char *text,
    size_t size,
    size_t *inout_offset,
    uint32_t *out_codepoint
);
static bool utf8_is_continuation(unsigned char byte);
static int append_collation_level_key(
    struct mylite_collation_key_builder *builder,
    enum mylite_collation_level level,
    const unsigned char *text,
    size_t text_size
);
static int append_collation_key_weight(
    struct mylite_collation_key_builder *builder,
    uint32_t weight
);
static int reserve_collation_key(
    struct mylite_collation_key_builder *builder,
    size_t required_size
);
static bool text_has_ascii_case_insensitive_suffix(const char *text, const char *suffix);
static bool text_equals_ascii_case_insensitive(const char *left, const char *right);
static unsigned char ascii_fold(unsigned char byte);

int mylite_collation_kind_from_name(const char *name, enum mylite_collation_kind *out_kind) {
    if (name == NULL || out_kind == NULL) {
        return MYLITE_MISUSE;
    }
    if (text_equals_ascii_case_insensitive(name, "binary") ||
        text_has_ascii_case_insensitive_suffix(name, "_bin")) {
        *out_kind = MYLITE_COLLATION_BINARY;
    } else if (text_has_ascii_case_insensitive_suffix(name, "_cs")) {
        *out_kind = MYLITE_COLLATION_UTF8MB4_0900_AS_CS;
    } else if (text_has_ascii_case_insensitive_suffix(name, "_as_ci")) {
        *out_kind = MYLITE_COLLATION_UTF8MB4_0900_AS_CI;
    } else {
        *out_kind = MYLITE_COLLATION_UTF8MB4_0900_AI_CI;
    }
    return MYLITE_OK;
}

const char *mylite_collation_sqlite_name(enum mylite_collation_kind kind) {
    switch (kind) {
    case MYLITE_COLLATION_UTF8MB4_0900_AI_CI:
        return "utf8mb4_0900_ai_ci";
    case MYLITE_COLLATION_UTF8MB4_0900_AS_CI:
        return "utf8mb4_0900_as_ci";
    case MYLITE_COLLATION_UTF8MB4_0900_AS_CS:
        return "utf8mb4_0900_as_cs";
    case MYLITE_COLLATION_BINARY:
        return NULL;
    }
    return NULL;
}

int mylite_collation_compare(
    enum mylite_collation_kind kind,
    const void *left,
    size_t left_size,
    const void *right,
    size_t right_size
) {
    const unsigned char *left_bytes = left;
    const unsigned char *right_bytes = right;
    int result = 0;

    if ((left == NULL && left_size != 0U) || (right == NULL && right_size != 0U)) {
        return 0;
    }
    if (kind == MYLITE_COLLATION_BINARY) {
        return compare_binary(left_bytes, left_size, right_bytes, right_size);
    }
    if (compare_ascii(kind, left_bytes, left_size, right_bytes, right_size, &result)) {
        return result;
    }

    result = compare_unicode_level(
        MYLITE_COLLATION_LEVEL_PRIMARY,
        left_bytes,
        left_size,
        right_bytes,
        right_size
    );
    if (result == 0 && kind != MYLITE_COLLATION_UTF8MB4_0900_AI_CI) {
        result = compare_unicode_level(
            MYLITE_COLLATION_LEVEL_SECONDARY,
            left_bytes,
            left_size,
            right_bytes,
            right_size
        );
    }
    if (result == 0 && kind == MYLITE_COLLATION_UTF8MB4_0900_AS_CS) {
        result = compare_unicode_level(
            MYLITE_COLLATION_LEVEL_TERTIARY,
            left_bytes,
            left_size,
            right_bytes,
            right_size
        );
    }
    return result;
}

int mylite_collation_make_key(
    enum mylite_collation_kind kind,
    const void *text,
    size_t text_size,
    unsigned char **out_key,
    size_t *out_key_size
) {
    const unsigned char *bytes = text;
    struct mylite_collation_key_builder builder = {0};
    int rc = MYLITE_OK;

    if (out_key == NULL || out_key_size == NULL || (text == NULL && text_size != 0U)) {
        return MYLITE_MISUSE;
    }
    *out_key = NULL;
    *out_key_size = 0U;

    if (kind == MYLITE_COLLATION_BINARY) {
        if (text_size == 0U) {
            return MYLITE_OK;
        }
        builder.bytes = malloc(text_size);
        if (builder.bytes == NULL) {
            return MYLITE_NOMEM;
        }
        memcpy(builder.bytes, text, text_size);
        builder.size = text_size;
    } else {
        rc = append_collation_level_key(&builder, MYLITE_COLLATION_LEVEL_PRIMARY, bytes, text_size);
        if (rc == MYLITE_OK && kind != MYLITE_COLLATION_UTF8MB4_0900_AI_CI) {
            rc = append_collation_key_weight(&builder, collation_key_level_separator);
        }
        if (rc == MYLITE_OK && kind != MYLITE_COLLATION_UTF8MB4_0900_AI_CI) {
            rc = append_collation_level_key(
                &builder,
                MYLITE_COLLATION_LEVEL_SECONDARY,
                bytes,
                text_size
            );
        }
        if (rc == MYLITE_OK && kind == MYLITE_COLLATION_UTF8MB4_0900_AS_CS) {
            rc = append_collation_key_weight(&builder, collation_key_level_separator);
        }
        if (rc == MYLITE_OK && kind == MYLITE_COLLATION_UTF8MB4_0900_AS_CS) {
            rc = append_collation_level_key(
                &builder,
                MYLITE_COLLATION_LEVEL_TERTIARY,
                bytes,
                text_size
            );
        }
    }
    if (rc != MYLITE_OK) {
        free(builder.bytes);
        return rc;
    }

    *out_key = builder.bytes;
    *out_key_size = builder.size;
    return MYLITE_OK;
}

static int compare_binary(
    const unsigned char *left,
    size_t left_size,
    const unsigned char *right,
    size_t right_size
) {
    size_t shared_size = left_size < right_size ? left_size : right_size;
    int result = shared_size == 0U ? 0 : memcmp(left, right, shared_size);

    if (result < 0) {
        return -1;
    }
    if (result > 0) {
        return 1;
    }
    if (left_size < right_size) {
        return -1;
    }
    return left_size > right_size ? 1 : 0;
}

static bool compare_ascii(
    enum mylite_collation_kind kind,
    const unsigned char *left,
    size_t left_size,
    const unsigned char *right,
    size_t right_size,
    int *out_result
) {
    size_t shared_size = left_size < right_size ? left_size : right_size;

    for (size_t index = 0U; index < shared_size; ++index) {
        unsigned char left_byte = left[index];
        unsigned char right_byte = right[index];
        unsigned char left_folded = 0U;
        unsigned char right_folded = 0U;

        if (left_byte >= ascii_code_point_limit || right_byte >= ascii_code_point_limit) {
            return false;
        }
        left_folded = ascii_fold(left_byte);
        right_folded = ascii_fold(right_byte);
        if (left_folded < right_folded) {
            *out_result = -1;
            return true;
        }
        if (left_folded > right_folded) {
            *out_result = 1;
            return true;
        }
    }
    for (size_t index = shared_size; index < left_size; ++index) {
        if (left[index] >= ascii_code_point_limit) {
            return false;
        }
    }
    for (size_t index = shared_size; index < right_size; ++index) {
        if (right[index] >= ascii_code_point_limit) {
            return false;
        }
    }
    if (left_size != right_size) {
        *out_result = left_size < right_size ? -1 : 1;
        return true;
    }
    if (kind == MYLITE_COLLATION_UTF8MB4_0900_AS_CS) {
        for (size_t index = 0U; index < shared_size; ++index) {
            unsigned int left_weight = ascii_fold(left[index]) == left[index] ? 1U : 2U;
            unsigned int right_weight = ascii_fold(right[index]) == right[index] ? 1U : 2U;

            if (left_weight < right_weight) {
                *out_result = -1;
                return true;
            }
            if (left_weight > right_weight) {
                *out_result = 1;
                return true;
            }
        }
    }
    *out_result = 0;
    return true;
}

static int compare_unicode_level(
    enum mylite_collation_level level,
    const unsigned char *left,
    size_t left_size,
    const unsigned char *right,
    size_t right_size
) {
    struct mylite_collation_iterator left_iterator = {
        .text = left,
        .size = left_size,
        .level = level,
    };
    struct mylite_collation_iterator right_iterator = {
        .text = right,
        .size = right_size,
        .level = level,
    };
    uint32_t left_weight = 0U;
    uint32_t right_weight = 0U;
    bool has_left = false;
    bool has_right = false;

    do {
        has_left = collation_iterator_next(&left_iterator, &left_weight);
        has_right = collation_iterator_next(&right_iterator, &right_weight);
        if (!has_left || !has_right) {
            break;
        }
        if (left_weight < right_weight) {
            return -1;
        }
        if (left_weight > right_weight) {
            return 1;
        }
    } while (has_left && has_right);

    if (has_left) {
        return 1;
    }
    return has_right ? -1 : 0;
}

static bool collation_iterator_next(
    struct mylite_collation_iterator *iterator,
    uint32_t *out_weight
) {
    uint32_t codepoint = 0U;

    if (iterator == NULL || out_weight == NULL) {
        return false;
    }
    while (iterator->pending_index < iterator->pending_count || iterator->offset < iterator->size) {
        if (iterator->pending_index < iterator->pending_count) {
            *out_weight = iterator->pending[iterator->pending_index++];
            return true;
        }
        iterator->pending_count = 0U;
        iterator->pending_index = 0U;
        (void)decode_utf8_codepoint(iterator->text, iterator->size, &iterator->offset, &codepoint);
        if (iterator->level == MYLITE_COLLATION_LEVEL_PRIMARY &&
            collation_primary_weight(iterator, codepoint, out_weight)) {
            return true;
        }
        if (iterator->level == MYLITE_COLLATION_LEVEL_SECONDARY &&
            collation_secondary_weight(iterator, codepoint, out_weight)) {
            return true;
        }
        if (iterator->level == MYLITE_COLLATION_LEVEL_TERTIARY &&
            collation_tertiary_weight(codepoint, out_weight)) {
            return true;
        }
    }
    return false;
}

static bool collation_primary_weight(
    struct mylite_collation_iterator *iterator,
    uint32_t codepoint,
    uint32_t *out_weight
) {
    uint32_t expansion[3] = {0U};
    size_t expansion_count = 0U;

    if (codepoint >= invalid_utf8_weight_base) {
        *out_weight = codepoint;
        return true;
    }
    if (collation_codepoint_is_combining_mark(codepoint)) {
        return false;
    }
    expansion_count = collation_primary_expansion(codepoint, expansion);
    if (expansion_count != 0U) {
        *out_weight = expansion[0];
        for (size_t index = 1U; index < expansion_count; ++index) {
            iterator->pending[iterator->pending_count++] = expansion[index];
        }
        return true;
    }
    *out_weight = (uint32_t)sqlite3FtsUnicodeFold((int)codepoint, 2);
    return true;
}

static bool collation_secondary_weight(
    struct mylite_collation_iterator *iterator,
    uint32_t codepoint,
    uint32_t *out_weight
) {
    uint32_t accent = 0U;
    uint32_t folded = 0U;
    uint32_t accent_folded = 0U;
    uint32_t expansion[3] = {0U};

    if (codepoint >= invalid_utf8_weight_base) {
        *out_weight = codepoint;
        return true;
    }
    if (collation_codepoint_is_combining_mark(codepoint)) {
        *out_weight = codepoint;
        return true;
    }
    accent = collation_canonical_accent(codepoint);
    if (accent != 0U) {
        *out_weight = 1U;
        iterator->pending[iterator->pending_count++] = accent;
        return true;
    }
    if (collation_primary_expansion(codepoint, expansion) != 0U) {
        *out_weight = 1U;
        iterator->pending[iterator->pending_count++] =
            compatibility_secondary_weight_base + codepoint;
        return true;
    }
    folded = (uint32_t)sqlite3FtsUnicodeFold((int)codepoint, 0);
    accent_folded = (uint32_t)sqlite3FtsUnicodeFold((int)codepoint, 2);
    if (folded != accent_folded) {
        iterator->pending[iterator->pending_count++] =
            compatibility_secondary_weight_base + codepoint;
    }
    *out_weight = 1U;
    return true;
}

static bool collation_tertiary_weight(uint32_t codepoint, uint32_t *out_weight) {
    uint32_t folded = 0U;

    if (codepoint >= invalid_utf8_weight_base) {
        *out_weight = codepoint;
        return true;
    }
    if (collation_codepoint_is_combining_mark(codepoint)) {
        return false;
    }
    folded = (uint32_t)sqlite3FtsUnicodeFold((int)codepoint, 0);
    *out_weight = folded == codepoint ? 1U : 2U;
    return true;
}

/* Unicode code points, UTF-8 masks, and encoded key widths are format data. */
// NOLINTBEGIN(readability-magic-numbers)
static size_t collation_primary_expansion(uint32_t codepoint, uint32_t out_codepoints[3]) {
    switch (codepoint) {
    case 0x00c6U:
    case 0x00e6U:
        out_codepoints[0] = 'a';
        out_codepoints[1] = 'e';
        return 2U;
    case 0x00dfU:
    case 0x1e9eU:
        out_codepoints[0] = 's';
        out_codepoints[1] = 's';
        return 2U;
    case 0x0132U:
    case 0x0133U:
        out_codepoints[0] = 'i';
        out_codepoints[1] = 'j';
        return 2U;
    case 0x0152U:
    case 0x0153U:
        out_codepoints[0] = 'o';
        out_codepoints[1] = 'e';
        return 2U;
    case 0xfb00U:
        out_codepoints[0] = 'f';
        out_codepoints[1] = 'f';
        return 2U;
    case 0xfb01U:
        out_codepoints[0] = 'f';
        out_codepoints[1] = 'i';
        return 2U;
    case 0xfb02U:
        out_codepoints[0] = 'f';
        out_codepoints[1] = 'l';
        return 2U;
    case 0xfb03U:
        out_codepoints[0] = 'f';
        out_codepoints[1] = 'f';
        out_codepoints[2] = 'i';
        return 3U;
    case 0xfb04U:
        out_codepoints[0] = 'f';
        out_codepoints[1] = 'f';
        out_codepoints[2] = 'l';
        return 3U;
    case 0xfb05U:
    case 0xfb06U:
        out_codepoints[0] = 's';
        out_codepoints[1] = 't';
        return 2U;
    default:
        return 0U;
    }
}

static uint32_t collation_canonical_accent(uint32_t codepoint) {
    switch (codepoint) {
    case 0x00c0U:
    case 0x00c8U:
    case 0x00ccU:
    case 0x00d2U:
    case 0x00d9U:
    case 0x00e0U:
    case 0x00e8U:
    case 0x00ecU:
    case 0x00f2U:
    case 0x00f9U:
        return 0x0300U;
    case 0x00c1U:
    case 0x00c9U:
    case 0x00cdU:
    case 0x00d3U:
    case 0x00daU:
    case 0x00ddU:
    case 0x00e1U:
    case 0x00e9U:
    case 0x00edU:
    case 0x00f3U:
    case 0x00faU:
    case 0x00fdU:
        return 0x0301U;
    case 0x00c2U:
    case 0x00caU:
    case 0x00ceU:
    case 0x00d4U:
    case 0x00dbU:
    case 0x00e2U:
    case 0x00eaU:
    case 0x00eeU:
    case 0x00f4U:
    case 0x00fbU:
        return 0x0302U;
    case 0x00c3U:
    case 0x00d1U:
    case 0x00d5U:
    case 0x00e3U:
    case 0x00f1U:
    case 0x00f5U:
        return 0x0303U;
    case 0x00c4U:
    case 0x00cbU:
    case 0x00cfU:
    case 0x00d6U:
    case 0x00dcU:
    case 0x00e4U:
    case 0x00ebU:
    case 0x00efU:
    case 0x00f6U:
    case 0x00fcU:
    case 0x00ffU:
        return 0x0308U;
    case 0x00c5U:
    case 0x00e5U:
        return 0x030aU;
    case 0x00c7U:
    case 0x00e7U:
        return 0x0327U;
    default:
        return 0U;
    }
}

static bool collation_codepoint_is_combining_mark(uint32_t codepoint) {
    return (codepoint >= 0x0300U && codepoint <= 0x036fU) ||
           (codepoint >= 0x1ab0U && codepoint <= 0x1affU) ||
           (codepoint >= 0x1dc0U && codepoint <= 0x1dffU) ||
           (codepoint >= 0x20d0U && codepoint <= 0x20ffU) ||
           (codepoint >= 0xfe20U && codepoint <= 0xfe2fU);
}

static bool decode_utf8_codepoint(
    const unsigned char *text,
    size_t size,
    size_t *inout_offset,
    uint32_t *out_codepoint
) {
    size_t offset = 0U;
    unsigned char first = 0U;

    if (text == NULL || inout_offset == NULL || out_codepoint == NULL || *inout_offset >= size) {
        return false;
    }
    offset = *inout_offset;
    first = text[offset++];
    if (first < 0x80U) {
        *out_codepoint = first;
        *inout_offset = offset;
        return true;
    }
    if (first >= 0xc2U && first <= 0xdfU && offset < size && utf8_is_continuation(text[offset])) {
        *out_codepoint = ((uint32_t)(first & 0x1fU) << 6U) | (uint32_t)(text[offset] & 0x3fU);
        *inout_offset = offset + 1U;
        return true;
    }
    if (first >= 0xe0U && first <= 0xefU && offset + 1U < size &&
        utf8_is_continuation(text[offset]) && utf8_is_continuation(text[offset + 1U]) &&
        !(first == 0xe0U && text[offset] < 0xa0U) && !(first == 0xedU && text[offset] >= 0xa0U)) {
        *out_codepoint = ((uint32_t)(first & 0x0fU) << 12U) |
                         ((uint32_t)(text[offset] & 0x3fU) << 6U) |
                         (uint32_t)(text[offset + 1U] & 0x3fU);
        *inout_offset = offset + 2U;
        return true;
    }
    if (first >= 0xf0U && first <= 0xf4U && offset + 2U < size &&
        utf8_is_continuation(text[offset]) && utf8_is_continuation(text[offset + 1U]) &&
        utf8_is_continuation(text[offset + 2U]) && !(first == 0xf0U && text[offset] < 0x90U) &&
        !(first == 0xf4U && text[offset] >= 0x90U)) {
        *out_codepoint =
            ((uint32_t)(first & 0x07U) << 18U) | ((uint32_t)(text[offset] & 0x3fU) << 12U) |
            ((uint32_t)(text[offset + 1U] & 0x3fU) << 6U) | (uint32_t)(text[offset + 2U] & 0x3fU);
        *inout_offset = offset + 3U;
        return true;
    }

    *out_codepoint = invalid_utf8_weight_base + first;
    *inout_offset = *inout_offset + 1U;
    return true;
}

static bool utf8_is_continuation(unsigned char byte) {
    return (byte & 0xc0U) == 0x80U;
}

static int append_collation_level_key(
    struct mylite_collation_key_builder *builder,
    enum mylite_collation_level level,
    const unsigned char *text,
    size_t text_size
) {
    struct mylite_collation_iterator iterator = {
        .text = text,
        .size = text_size,
        .level = level,
    };
    uint32_t weight = 0U;
    int rc = MYLITE_OK;

    while (rc == MYLITE_OK && collation_iterator_next(&iterator, &weight)) {
        rc = append_collation_key_weight(builder, weight);
    }
    return rc;
}

static int append_collation_key_weight(
    struct mylite_collation_key_builder *builder,
    uint32_t weight
) {
    int rc = MYLITE_OK;

    if (builder == NULL || builder->size > SIZE_MAX - 4U) {
        return MYLITE_NOMEM;
    }
    rc = reserve_collation_key(builder, builder->size + 4U);
    if (rc != MYLITE_OK) {
        return rc;
    }
    builder->bytes[builder->size++] = (unsigned char)(weight >> 24U);
    builder->bytes[builder->size++] = (unsigned char)(weight >> 16U);
    builder->bytes[builder->size++] = (unsigned char)(weight >> 8U);
    builder->bytes[builder->size++] = (unsigned char)weight;
    return MYLITE_OK;
}

static int reserve_collation_key(
    struct mylite_collation_key_builder *builder,
    size_t required_size
) {
    size_t capacity = 0U;
    unsigned char *resized = NULL;

    if (builder == NULL) {
        return MYLITE_MISUSE;
    }
    if (required_size <= builder->capacity) {
        return MYLITE_OK;
    }
    capacity = builder->capacity == 0U ? 32U : builder->capacity;
    while (capacity < required_size) {
        if (capacity > SIZE_MAX / 2U) {
            capacity = required_size;
            break;
        }
        capacity *= 2U;
    }
    resized = realloc(builder->bytes, capacity);
    if (resized == NULL) {
        return MYLITE_NOMEM;
    }
    builder->bytes = resized;
    builder->capacity = capacity;
    return MYLITE_OK;
}

// NOLINTEND(readability-magic-numbers)

static bool text_has_ascii_case_insensitive_suffix(const char *text, const char *suffix) {
    size_t text_size = 0U;
    size_t suffix_size = 0U;

    if (text == NULL || suffix == NULL) {
        return false;
    }
    text_size = strlen(text);
    suffix_size = strlen(suffix);
    return suffix_size <= text_size &&
           text_equals_ascii_case_insensitive(text + text_size - suffix_size, suffix);
}

static bool text_equals_ascii_case_insensitive(const char *left, const char *right) {
    if (left == NULL || right == NULL) {
        return false;
    }
    while (*left != '\0' && *right != '\0') {
        if (ascii_fold((unsigned char)*left) != ascii_fold((unsigned char)*right)) {
            return false;
        }
        ++left;
        ++right;
    }
    return *left == *right;
}

static unsigned char ascii_fold(unsigned char byte) {
    return byte >= 'A' && byte <= 'Z' ? (unsigned char)(byte + ('a' - 'A')) : byte;
}
