#ifndef MYLITE_MYSQL_SERVER_IDENTITY_H
#define MYLITE_MYSQL_SERVER_IDENTITY_H

#define MYLITE_MYSQL_SERVER_VERSION_STRING "8.4.9"
#define MYLITE_MYSQL_SERVER_VERSION_COMMENT_STRING "MySQL Community Server - GPL"

#endif
