#ifndef MYLITE_RUNTIME_MYLITE_TABLE_DDL_STATEMENT_H
#define MYLITE_RUNTIME_MYLITE_TABLE_DDL_STATEMENT_H

#include <mylite/mylite.h>

int mylite_table_ddl_execute_rename_table_prepared_statement(mylite_stmt *stmt);
int mylite_table_ddl_execute_truncate_table_prepared_statement(mylite_stmt *stmt);
int mylite_table_ddl_execute_create_index_prepared_statement(mylite_stmt *stmt);
int mylite_table_ddl_execute_drop_index_prepared_statement(mylite_stmt *stmt);

#endif
