#include "mylite_execution_catalog_system_tables_internal.h"

static const struct mylite_execution_catalog_column_definition sys_sys_config_columns[] = {
    {"variable",
     NULL,
     "NO",
     "varchar",
     "128",
     "512",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(128)"},
    {"value",
     NULL,
     "YES",
     "varchar",
     "128",
     "512",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(128)"},
    {"set_time",
     "CURRENT_TIMESTAMP",
     "YES",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "timestamp"},
    {"set_by",
     NULL,
     "YES",
     "varchar",
     "128",
     "512",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(128)"},
};

static const char *const sys_sys_config_column_keys[] = {
    "PRI",
    "",
    "",
    "",
};

static const char *const sys_sys_config_column_extras[] = {
    "",
    "",
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
    "",
};

static const char *const sys_sys_config_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const char sys_sys_config_trigger_action_statement[] =
    "BEGIN\n"
    "    IF @sys.ignore_sys_config_triggers != true AND NEW.set_by IS NULL THEN\n"
    "        SET NEW.set_by = USER();\n"
    "    END IF;\n"
    "END";

static const char sys_sys_config_trigger_sql_mode[] =
    "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,"
    "ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION";

static const struct mylite_execution_catalog_sys_config_trigger sys_sys_config_triggers[] = {
    {"sys_config_insert_set_user", "INSERT"},
    {"sys_config_update_set_user", "UPDATE"},
};

static const struct mylite_execution_catalog_column_definition sys_version_columns[] = {
    {"sys_version",
     "",
     "NO",
     "varchar",
     "5",
     "20",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(5)"},
    {"mysql_version",
     "",
     "NO",
     "varchar",
     "5",
     "15",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(5)"},
};

static const char *const sys_version_column_keys[] = {
    "",
    "",
};

static const char *const sys_version_column_extras[] = {
    "",
    "",
};

static const char *const sys_version_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition sys_metrics_columns[] = {
    {"Variable_name",
     "",
     "NO",
     "varchar",
     "193",
     "772",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(193)"},
    {"Variable_value",
     NULL,
     "YES",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "text"},
    {"Type",
     "",
     "NO",
     "varchar",
     "210",
     "630",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(210)"},
    {"Enabled",
     "",
     "NO",
     "varchar",
     "7",
     "28",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(7)"},
};

static const char *const sys_metrics_column_keys[] = {
    "",
    "",
    "",
    "",
};

static const char *const sys_metrics_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const sys_metrics_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition sys_processlist_columns[] = {
    {"thd_id", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
    {"conn_id", NULL, "YES", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
    {"user",
     NULL,
     "YES",
     "varchar",
     "288",
     "1152",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(288)"},
    {"db",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"command",
     NULL,
     "YES",
     "varchar",
     "16",
     "64",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(16)"},
    {"state",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"time", NULL, "YES", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
    {"current_statement",
     NULL,
     "YES",
     "longtext",
     "4294967295",
     "4294967295",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "longtext"},
    {"execution_engine",
     NULL,
     "YES",
     "enum",
     "9",
     "36",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "enum('PRIMARY','SECONDARY')"},
    {"statement_latency",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
    {"progress", NULL, "YES", "decimal", NULL, NULL, "26", "2", NULL, NULL, NULL, "decimal(26,2)"},
    {"lock_latency",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
    {"cpu_latency",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
    {"rows_examined",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"rows_sent", NULL, "YES", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"
    },
    {"rows_affected",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"tmp_tables", NULL, "YES", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"
    },
    {"tmp_disk_tables",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"full_scan",
     "",
     "NO",
     "varchar",
     "3",
     "12",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(3)"},
    {"last_statement",
     NULL,
     "YES",
     "longtext",
     "4294967295",
     "4294967295",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "longtext"},
    {"last_statement_latency",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
    {"current_memory",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
    {"last_wait",
     NULL,
     "YES",
     "varchar",
     "128",
     "512",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(128)"},
    {"last_wait_latency",
     NULL,
     "YES",
     "varchar",
     "13",
     "52",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(13)"},
    {"source",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"trx_latency",
     NULL,
     "YES",
     "varchar",
     "11",
     "33",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(11)"},
    {"trx_state",
     NULL,
     "YES",
     "enum",
     "11",
     "44",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "enum('ACTIVE','COMMITTED','ROLLED BACK')"},
    {"trx_autocommit",
     NULL,
     "YES",
     "enum",
     "3",
     "12",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "enum('YES','NO')"},
    {"pid",
     NULL,
     "YES",
     "varchar",
     "1024",
     "4096",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_bin",
     "varchar(1024)"},
    {"program_name",
     NULL,
     "YES",
     "varchar",
     "1024",
     "4096",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_bin",
     "varchar(1024)"},
};

static const struct mylite_execution_catalog_column_definition sys_x_processlist_columns[] = {
    {"thd_id", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
    {"conn_id", NULL, "YES", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
    {"user",
     NULL,
     "YES",
     "varchar",
     "288",
     "1152",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(288)"},
    {"db",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"command",
     NULL,
     "YES",
     "varchar",
     "16",
     "64",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(16)"},
    {"state",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"time", NULL, "YES", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
    {"current_statement",
     NULL,
     "YES",
     "longtext",
     "4294967295",
     "4294967295",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "longtext"},
    {"execution_engine",
     NULL,
     "YES",
     "enum",
     "9",
     "36",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "enum('PRIMARY','SECONDARY')"},
    {"statement_latency",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"progress", NULL, "YES", "decimal", NULL, NULL, "26", "2", NULL, NULL, NULL, "decimal(26,2)"},
    {"lock_latency",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"cpu_latency",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"rows_examined",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"rows_sent", NULL, "YES", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"
    },
    {"rows_affected",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"tmp_tables", NULL, "YES", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"
    },
    {"tmp_disk_tables",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"full_scan",
     "",
     "NO",
     "varchar",
     "3",
     "12",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(3)"},
    {"last_statement",
     NULL,
     "YES",
     "longtext",
     "4294967295",
     "4294967295",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "longtext"},
    {"last_statement_latency",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"current_memory",
     NULL,
     "YES",
     "decimal",
     NULL,
     NULL,
     "41",
     "0",
     NULL,
     NULL,
     NULL,
     "decimal(41,0)"},
    {"last_wait",
     NULL,
     "YES",
     "varchar",
     "128",
     "512",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(128)"},
    {"last_wait_latency",
     NULL,
     "YES",
     "varchar",
     "20",
     "80",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(20)"},
    {"source",
     NULL,
     "YES",
     "varchar",
     "64",
     "256",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(64)"},
    {"trx_latency",
     NULL,
     "YES",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"trx_state",
     NULL,
     "YES",
     "enum",
     "11",
     "44",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "enum('ACTIVE','COMMITTED','ROLLED BACK')"},
    {"trx_autocommit",
     NULL,
     "YES",
     "enum",
     "3",
     "12",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "enum('YES','NO')"},
    {"pid",
     NULL,
     "YES",
     "varchar",
     "1024",
     "4096",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_bin",
     "varchar(1024)"},
    {"program_name",
     NULL,
     "YES",
     "varchar",
     "1024",
     "4096",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_bin",
     "varchar(1024)"},
};

static const struct mylite_execution_catalog_column_definition sys_session_ssl_status_columns[] = {
    {"thread_id", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
    {"ssl_version",
     NULL,
     "YES",
     "varchar",
     "1024",
     "4096",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(1024)"},
    {"ssl_cipher",
     NULL,
     "YES",
     "varchar",
     "1024",
     "4096",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(1024)"},
    {"ssl_sessions_reused",
     NULL,
     "YES",
     "varchar",
     "1024",
     "4096",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "varchar(1024)"},
};

static const char *const sys_processlist_column_keys[] = {
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
};

static const char *const sys_processlist_column_extras[] = {
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
};

static const char *const sys_processlist_column_privileges[] = {
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
};

static const char *const sys_session_ssl_status_column_keys[] = {
    "",
    "",
    "",
    "",
};

static const char *const sys_session_ssl_status_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const sys_session_ssl_status_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_table
    sys_core_system_table_definitions[] = {
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_SYS_CONFIG,
          "sys_config",
          sys_sys_config_columns,
          sizeof(sys_sys_config_columns) / sizeof(sys_sys_config_columns[0])},
         sys_sys_config_column_keys,
         sys_sys_config_column_extras,
         sys_sys_config_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_VERSION,
          "version",
          sys_version_columns,
          sizeof(sys_version_columns) / sizeof(sys_version_columns[0])},
         sys_version_column_keys,
         sys_version_column_extras,
         sys_version_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_METRICS,
          "metrics",
          sys_metrics_columns,
          sizeof(sys_metrics_columns) / sizeof(sys_metrics_columns[0])},
         sys_metrics_column_keys,
         sys_metrics_column_extras,
         sys_metrics_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_PROCESSLIST,
          "processlist",
          sys_processlist_columns,
          sizeof(sys_processlist_columns) / sizeof(sys_processlist_columns[0])},
         sys_processlist_column_keys,
         sys_processlist_column_extras,
         sys_processlist_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_PROCESSLIST,
          "x$processlist",
          sys_x_processlist_columns,
          sizeof(sys_x_processlist_columns) / sizeof(sys_x_processlist_columns[0])},
         sys_processlist_column_keys,
         sys_processlist_column_extras,
         sys_processlist_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_SESSION,
          "session",
          sys_processlist_columns,
          sizeof(sys_processlist_columns) / sizeof(sys_processlist_columns[0])},
         sys_processlist_column_keys,
         sys_processlist_column_extras,
         sys_processlist_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_SESSION,
          "x$session",
          sys_x_processlist_columns,
          sizeof(sys_x_processlist_columns) / sizeof(sys_x_processlist_columns[0])},
         sys_processlist_column_keys,
         sys_processlist_column_extras,
         sys_processlist_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_SESSION_SSL_STATUS,
          "session_ssl_status",
          sys_session_ssl_status_columns,
          sizeof(sys_session_ssl_status_columns) / sizeof(sys_session_ssl_status_columns[0])},
         sys_session_ssl_status_column_keys,
         sys_session_ssl_status_column_extras,
         sys_session_ssl_status_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
};

size_t mylite_execution_catalog_sys_core_system_table_definition_count(void) {
    return sizeof(sys_core_system_table_definitions) / sizeof(sys_core_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_sys_core_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_sys_core_system_table_definition_count()) {
        return NULL;
    }
    return &sys_core_system_table_definitions[index];
}

const char *mylite_execution_catalog_sys_sys_config_trigger_action_statement(void) {
    return sys_sys_config_trigger_action_statement;
}

const char *mylite_execution_catalog_sys_sys_config_trigger_sql_mode(void) {
    return sys_sys_config_trigger_sql_mode;
}

size_t mylite_execution_catalog_sys_sys_config_trigger_count(void) {
    return sizeof(sys_sys_config_triggers) / sizeof(sys_sys_config_triggers[0]);
}

const struct mylite_execution_catalog_sys_config_trigger *mylite_execution_catalog_sys_sys_config_trigger_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_sys_sys_config_trigger_count()) {
        return NULL;
    }
    return &sys_sys_config_triggers[index];
}
