#include "mylite_execution_catalog_sys_summary_tables_internal.h"

static const struct mylite_execution_catalog_column_definition
    sys_memory_by_host_by_current_bytes_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"current_count_used",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "41",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(41,0)"},
        {"current_allocated",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"current_avg_alloc",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"current_max_alloc",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"total_allocated",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
};

static const struct mylite_execution_catalog_column_definition
    sys_x_memory_by_host_by_current_bytes_columns[] = {
        {"host",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"current_count_used",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "41",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(41,0)"},
        {"current_allocated",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "41",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(41,0)"},
        {"current_avg_alloc",
         "0.0000",
         "NO",
         "decimal",
         NULL,
         NULL,
         "45",
         "4",
         NULL,
         NULL,
         NULL,
         "decimal(45,4)"},
        {"current_max_alloc",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"total_allocated",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
};

static const char *const sys_memory_by_host_by_current_bytes_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_memory_by_host_by_current_bytes_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_memory_by_host_by_current_bytes_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    sys_memory_by_thread_by_current_bytes_columns[] = {
        {"thread_id",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"user",
         NULL,
         "YES",
         "varchar",
         "288",
         "1152",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(288)"},
        {"current_count_used",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "41",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(41,0)"},
        {"current_allocated",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"current_avg_alloc",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"current_max_alloc",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"total_allocated",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
};

static const struct mylite_execution_catalog_column_definition
    sys_x_memory_by_thread_by_current_bytes_columns[] = {
        {"thread_id",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"user",
         NULL,
         "YES",
         "varchar",
         "288",
         "1152",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(288)"},
        {"current_count_used",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "41",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(41,0)"},
        {"current_allocated",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "41",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(41,0)"},
        {"current_avg_alloc",
         "0.0000",
         "NO",
         "decimal",
         NULL,
         NULL,
         "45",
         "4",
         NULL,
         NULL,
         NULL,
         "decimal(45,4)"},
        {"current_max_alloc",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"total_allocated",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
};

static const char *const sys_memory_by_thread_by_current_bytes_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_memory_by_thread_by_current_bytes_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_memory_by_thread_by_current_bytes_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    sys_memory_by_user_by_current_bytes_columns[] = {
        {"user",
         NULL,
         "YES",
         "varchar",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "varchar(32)"},
        {"current_count_used",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "41",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(41,0)"},
        {"current_allocated",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"current_avg_alloc",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"current_max_alloc",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
        {"total_allocated",
         NULL,
         "YES",
         "varchar",
         "11",
         "33",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(11)"},
};

static const struct mylite_execution_catalog_column_definition
    sys_x_memory_by_user_by_current_bytes_columns[] = {
        {"user",
         NULL,
         "YES",
         "varchar",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "varchar(32)"},
        {"current_count_used",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "41",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(41,0)"},
        {"current_allocated",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "41",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(41,0)"},
        {"current_avg_alloc",
         "0.0000",
         "NO",
         "decimal",
         NULL,
         NULL,
         "45",
         "4",
         NULL,
         NULL,
         NULL,
         "decimal(45,4)"},
        {"current_max_alloc",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"total_allocated",
         NULL,
         "YES",
         "decimal",
         NULL,
         NULL,
         "42",
         "0",
         NULL,
         NULL,
         NULL,
         "decimal(42,0)"},
};

static const char *const sys_memory_by_user_by_current_bytes_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_memory_by_user_by_current_bytes_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const sys_memory_by_user_by_current_bytes_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_table
    sys_summary_memory_system_table_definitions[] = {
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_MEMORY_BY_HOST_BY_CURRENT_BYTES,
          "memory_by_host_by_current_bytes",
          sys_memory_by_host_by_current_bytes_columns,
          sizeof(sys_memory_by_host_by_current_bytes_columns) /
              sizeof(sys_memory_by_host_by_current_bytes_columns[0])},
         sys_memory_by_host_by_current_bytes_column_keys,
         sys_memory_by_host_by_current_bytes_column_extras,
         sys_memory_by_host_by_current_bytes_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_MEMORY_BY_THREAD_BY_CURRENT_BYTES,
          "memory_by_thread_by_current_bytes",
          sys_memory_by_thread_by_current_bytes_columns,
          sizeof(sys_memory_by_thread_by_current_bytes_columns) /
              sizeof(sys_memory_by_thread_by_current_bytes_columns[0])},
         sys_memory_by_thread_by_current_bytes_column_keys,
         sys_memory_by_thread_by_current_bytes_column_extras,
         sys_memory_by_thread_by_current_bytes_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_MEMORY_BY_USER_BY_CURRENT_BYTES,
          "memory_by_user_by_current_bytes",
          sys_memory_by_user_by_current_bytes_columns,
          sizeof(sys_memory_by_user_by_current_bytes_columns) /
              sizeof(sys_memory_by_user_by_current_bytes_columns[0])},
         sys_memory_by_user_by_current_bytes_column_keys,
         sys_memory_by_user_by_current_bytes_column_extras,
         sys_memory_by_user_by_current_bytes_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
};

size_t mylite_execution_catalog_sys_summary_memory_system_table_definition_count(void) {
    return sizeof(sys_summary_memory_system_table_definitions) /
           sizeof(sys_summary_memory_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_sys_summary_memory_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_sys_summary_memory_system_table_definition_count()) {
        return NULL;
    }
    return &sys_summary_memory_system_table_definitions[index];
}

static const struct mylite_execution_catalog_mysql_system_table
    sys_summary_memory_x_system_table_definitions[] = {
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_MEMORY_BY_HOST_BY_CURRENT_BYTES,
          "x$memory_by_host_by_current_bytes",
          sys_x_memory_by_host_by_current_bytes_columns,
          sizeof(sys_x_memory_by_host_by_current_bytes_columns) /
              sizeof(sys_x_memory_by_host_by_current_bytes_columns[0])},
         sys_memory_by_host_by_current_bytes_column_keys,
         sys_memory_by_host_by_current_bytes_column_extras,
         sys_memory_by_host_by_current_bytes_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_MEMORY_BY_THREAD_BY_CURRENT_BYTES,
          "x$memory_by_thread_by_current_bytes",
          sys_x_memory_by_thread_by_current_bytes_columns,
          sizeof(sys_x_memory_by_thread_by_current_bytes_columns) /
              sizeof(sys_x_memory_by_thread_by_current_bytes_columns[0])},
         sys_memory_by_thread_by_current_bytes_column_keys,
         sys_memory_by_thread_by_current_bytes_column_extras,
         sys_memory_by_thread_by_current_bytes_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"sys",
         {MYLITE_EXECUTION_CATALOG_TABLE_SYS_X_MEMORY_BY_USER_BY_CURRENT_BYTES,
          "x$memory_by_user_by_current_bytes",
          sys_x_memory_by_user_by_current_bytes_columns,
          sizeof(sys_x_memory_by_user_by_current_bytes_columns) /
              sizeof(sys_x_memory_by_user_by_current_bytes_columns[0])},
         sys_memory_by_user_by_current_bytes_column_keys,
         sys_memory_by_user_by_current_bytes_column_extras,
         sys_memory_by_user_by_current_bytes_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
};

size_t mylite_execution_catalog_sys_summary_memory_x_system_table_definition_count(void) {
    return sizeof(sys_summary_memory_x_system_table_definitions) /
           sizeof(sys_summary_memory_x_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_sys_summary_memory_x_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_sys_summary_memory_x_system_table_definition_count()) {
        return NULL;
    }
    return &sys_summary_memory_x_system_table_definitions[index];
}
