#include "mylite_execution_catalog_system_tables_internal.h"

static const struct mylite_execution_catalog_column_definition mysql_component_columns[] = {
    {"component_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"component_group_id",
     NULL,
     "NO",
     "int",
     NULL,
     NULL,
     "10",
     "0",
     NULL,
     NULL,
     NULL,
     "int unsigned"},
    {"component_urn",
     NULL,
     "NO",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "text"},
};

static const char *const mysql_component_column_keys[] = {
    "PRI",
    "",
    "",
};

static const char *const mysql_component_column_extras[] = {
    "auto_increment",
    "",
    "",
};

static const char *const mysql_component_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_func_columns[] = {
    {"name", "", "NO", "char", "64", "192", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(64)"},
    {"ret", "0", "NO", "tinyint", NULL, NULL, "3", "0", NULL, NULL, NULL, "tinyint"},
    {"dl", "", "NO", "char", "128", "384", NULL, NULL, NULL, "utf8mb3", "utf8mb3_bin", "char(128)"},
    {"type",
     NULL,
     "NO",
     "enum",
     "9",
     "27",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('function','aggregate')"},
};

static const char *const mysql_func_column_keys[] = {
    "PRI",
    "",
    "",
    "",
};

static const char *const mysql_func_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const mysql_func_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_gtid_executed_columns[] = {
    {"source_uuid",
     NULL,
     "NO",
     "char",
     "36",
     "144",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "char(36)"},
    {"interval_start", NULL, "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
    {"interval_end", NULL, "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
    {"gtid_tag",
     NULL,
     "NO",
     "char",
     "32",
     "128",
     NULL,
     NULL,
     NULL,
     "utf8mb4",
     "utf8mb4_0900_ai_ci",
     "char(32)"},
};

static const char *const mysql_gtid_executed_column_keys[] = {
    "PRI",
    "PRI",
    "",
    "PRI",
};

static const char *const mysql_gtid_executed_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const mysql_gtid_executed_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const char *const mysql_gtid_executed_column_comments[] = {
    "uuid of the source where the transaction was originally executed.",
    "First number of interval.",
    "Last number of interval.",
    "GTID Tag.",
};

static const size_t mysql_gtid_executed_primary_key_column_indexes[] = {
    0U,
    3U,
    1U,
};

static const struct mylite_execution_catalog_column_definition mysql_general_log_columns[] = {
    {"event_time",
     "CURRENT_TIMESTAMP(6)",
     "NO",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "6",
     NULL,
     NULL,
     "timestamp(6)"},
    {"user_host",
     NULL,
     "NO",
     "mediumtext",
     "16777215",
     "16777215",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "mediumtext"},
    {"thread_id", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
    {"server_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"command_type",
     NULL,
     "NO",
     "varchar",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(64)"},
    {"argument",
     NULL,
     "NO",
     "mediumblob",
     "16777215",
     "16777215",
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     "mediumblob"},
};

static const char *const mysql_general_log_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_general_log_column_extras[] = {
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP(6)",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_general_log_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_slow_log_columns[] = {
    {"start_time",
     "CURRENT_TIMESTAMP(6)",
     "NO",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "6",
     NULL,
     NULL,
     "timestamp(6)"},
    {"user_host",
     NULL,
     "NO",
     "mediumtext",
     "16777215",
     "16777215",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "mediumtext"},
    {"query_time", NULL, "NO", "time", NULL, NULL, NULL, NULL, "6", NULL, NULL, "time(6)"},
    {"lock_time", NULL, "NO", "time", NULL, NULL, NULL, NULL, "6", NULL, NULL, "time(6)"},
    {"rows_sent", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
    {"rows_examined", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
    {"db",
     NULL,
     "NO",
     "varchar",
     "512",
     "1536",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(512)"},
    {"last_insert_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
    {"insert_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
    {"server_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"sql_text",
     NULL,
     "NO",
     "mediumblob",
     "16777215",
     "16777215",
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     "mediumblob"},
    {"thread_id", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
};

static const char *const mysql_slow_log_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_slow_log_column_extras[] = {
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP(6)",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_slow_log_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_help_category_columns[] = {
    {"help_category_id",
     NULL,
     "NO",
     "smallint",
     NULL,
     NULL,
     "5",
     "0",
     NULL,
     NULL,
     NULL,
     "smallint unsigned"},
    {"name",
     NULL,
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
    {"parent_category_id",
     NULL,
     "YES",
     "smallint",
     NULL,
     NULL,
     "5",
     "0",
     NULL,
     NULL,
     NULL,
     "smallint unsigned"},
    {"url",
     NULL,
     "NO",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "text"},
};

static const char *const mysql_help_category_column_keys[] = {
    "PRI",
    "UNI",
    "",
    "",
};

static const char *const mysql_help_category_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const mysql_help_category_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    mysql_help_category_secondary_indexes[] = {
        {"name", 1U, "53", "0", true},
};

static const struct mylite_execution_catalog_column_definition mysql_help_keyword_columns[] = {
    {"help_keyword_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"name",
     NULL,
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
};

static const char *const mysql_help_keyword_column_keys[] = {
    "PRI",
    "UNI",
};

static const char *const mysql_help_keyword_column_extras[] = {
    "",
    "",
};

static const char *const mysql_help_keyword_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    mysql_help_keyword_secondary_indexes[] = {
        {"name", 1U, "551", "0", true},
};

static const struct mylite_execution_catalog_column_definition mysql_help_relation_columns[] = {
    {"help_topic_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"help_keyword_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
};

static const char *const mysql_help_relation_column_keys[] = {
    "PRI",
    "PRI",
};

static const char *const mysql_help_relation_column_extras[] = {
    "",
    "",
};

static const char *const mysql_help_relation_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t mysql_help_relation_primary_key_column_indexes[] = {
    1U,
    0U,
};

static const struct mylite_execution_catalog_column_definition mysql_help_topic_columns[] = {
    {"help_topic_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"name",
     NULL,
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
    {"help_category_id",
     NULL,
     "NO",
     "smallint",
     NULL,
     NULL,
     "5",
     "0",
     NULL,
     NULL,
     NULL,
     "smallint unsigned"},
    {"description",
     NULL,
     "NO",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "text"},
    {"example",
     NULL,
     "NO",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "text"},
    {"url",
     NULL,
     "NO",
     "text",
     "65535",
     "65535",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "text"},
};

static const char *const mysql_help_topic_column_keys[] = {
    "PRI",
    "UNI",
    "",
    "",
    "",
    "",
};

static const char *const mysql_help_topic_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_help_topic_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    mysql_help_topic_secondary_indexes[] = {
        {"name", 1U, "596", "0", true},
};

static const struct mylite_execution_catalog_column_definition mysql_ndb_binlog_index_columns[] = {
    {"Position", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
    {"File",
     NULL,
     "NO",
     "varchar",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "latin1",
     "latin1_swedish_ci",
     "varchar(255)"},
    {"epoch", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
    {"inserts", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"updates", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"deletes", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"schemaops", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"orig_server_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"orig_epoch", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"
    },
    {"gci", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"next_position",
     NULL,
     "NO",
     "bigint",
     NULL,
     NULL,
     "20",
     "0",
     NULL,
     NULL,
     NULL,
     "bigint unsigned"},
    {"next_file",
     NULL,
     "NO",
     "varchar",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "latin1",
     "latin1_swedish_ci",
     "varchar(255)"},
};

static const char *const mysql_ndb_binlog_index_column_keys[] = {
    "",
    "",
    "PRI",
    "",
    "",
    "",
    "",
    "PRI",
    "PRI",
    "",
    "",
    "",
};

static const char *const mysql_ndb_binlog_index_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_ndb_binlog_index_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_engine_cost_columns[] = {
    {"engine_name",
     NULL,
     "NO",
     "varchar",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(64)"},
    {"device_type", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
    {"cost_name",
     NULL,
     "NO",
     "varchar",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(64)"},
    {"cost_value", NULL, "YES", "float", NULL, NULL, "12", NULL, NULL, NULL, NULL, "float"},
    {"last_update",
     "CURRENT_TIMESTAMP",
     "NO",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "timestamp"},
    {"comment",
     NULL,
     "YES",
     "varchar",
     "1024",
     "3072",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(1024)"},
    {"default_value", NULL, "YES", "float", NULL, NULL, "12", NULL, NULL, NULL, NULL, "float"},
};

static const char *const mysql_engine_cost_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "",
    "",
    "",
    "",
};

static const char *const mysql_engine_cost_column_extras[] = {
    "",
    "",
    "",
    "",
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
    "",
    "VIRTUAL GENERATED",
};

static const char *const mysql_engine_cost_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const char *const mysql_engine_cost_column_generation_expressions[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    ("(case `cost_name` when _utf8mb4\\'io_block_read_cost\\' then 1.0 when "
     "_utf8mb4\\'memory_block_read_cost\\' then 0.25 else NULL end)"),
};

static const size_t mysql_engine_cost_primary_key_column_indexes[] = {
    2U,
    0U,
    1U,
};

static const struct mylite_execution_catalog_mysql_system_table
    mysql_service_system_table_definitions[] = {
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_COMPONENT,
          "component",
          mysql_component_columns,
          sizeof(mysql_component_columns) / sizeof(mysql_component_columns[0])},
         mysql_component_column_keys,
         mysql_component_column_extras,
         mysql_component_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_ENGINE_COST,
          "engine_cost",
          mysql_engine_cost_columns,
          sizeof(mysql_engine_cost_columns) / sizeof(mysql_engine_cost_columns[0])},
         mysql_engine_cost_column_keys,
         mysql_engine_cost_column_extras,
         mysql_engine_cost_column_privileges,
         NULL,
         mysql_engine_cost_primary_key_column_indexes,
         sizeof(mysql_engine_cost_primary_key_column_indexes) /
             sizeof(mysql_engine_cost_primary_key_column_indexes[0]),
         mysql_engine_cost_column_generation_expressions,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_FUNC,
          "func",
          mysql_func_columns,
          sizeof(mysql_func_columns) / sizeof(mysql_func_columns[0])},
         mysql_func_column_keys,
         mysql_func_column_extras,
         mysql_func_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_GTID_EXECUTED,
          "gtid_executed",
          mysql_gtid_executed_columns,
          sizeof(mysql_gtid_executed_columns) / sizeof(mysql_gtid_executed_columns[0])},
         mysql_gtid_executed_column_keys,
         mysql_gtid_executed_column_extras,
         mysql_gtid_executed_column_privileges,
         mysql_gtid_executed_column_comments,
         mysql_gtid_executed_primary_key_column_indexes,
         sizeof(mysql_gtid_executed_primary_key_column_indexes) /
             sizeof(mysql_gtid_executed_primary_key_column_indexes[0]),
         NULL,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_GENERAL_LOG,
          "general_log",
          mysql_general_log_columns,
          sizeof(mysql_general_log_columns) / sizeof(mysql_general_log_columns[0])},
         mysql_general_log_column_keys,
         mysql_general_log_column_extras,
         mysql_general_log_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_SLOW_LOG,
          "slow_log",
          mysql_slow_log_columns,
          sizeof(mysql_slow_log_columns) / sizeof(mysql_slow_log_columns[0])},
         mysql_slow_log_column_keys,
         mysql_slow_log_column_extras,
         mysql_slow_log_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_HELP_CATEGORY,
          "help_category",
          mysql_help_category_columns,
          sizeof(mysql_help_category_columns) / sizeof(mysql_help_category_columns[0])},
         mysql_help_category_column_keys,
         mysql_help_category_column_extras,
         mysql_help_category_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         mysql_help_category_secondary_indexes,
         sizeof(mysql_help_category_secondary_indexes) /
             sizeof(mysql_help_category_secondary_indexes[0])},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_HELP_KEYWORD,
          "help_keyword",
          mysql_help_keyword_columns,
          sizeof(mysql_help_keyword_columns) / sizeof(mysql_help_keyword_columns[0])},
         mysql_help_keyword_column_keys,
         mysql_help_keyword_column_extras,
         mysql_help_keyword_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         mysql_help_keyword_secondary_indexes,
         sizeof(mysql_help_keyword_secondary_indexes) /
             sizeof(mysql_help_keyword_secondary_indexes[0])},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_HELP_RELATION,
          "help_relation",
          mysql_help_relation_columns,
          sizeof(mysql_help_relation_columns) / sizeof(mysql_help_relation_columns[0])},
         mysql_help_relation_column_keys,
         mysql_help_relation_column_extras,
         mysql_help_relation_column_privileges,
         NULL,
         mysql_help_relation_primary_key_column_indexes,
         sizeof(mysql_help_relation_primary_key_column_indexes) /
             sizeof(mysql_help_relation_primary_key_column_indexes[0]),
         NULL,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_HELP_TOPIC,
          "help_topic",
          mysql_help_topic_columns,
          sizeof(mysql_help_topic_columns) / sizeof(mysql_help_topic_columns[0])},
         mysql_help_topic_column_keys,
         mysql_help_topic_column_extras,
         mysql_help_topic_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         mysql_help_topic_secondary_indexes,
         sizeof(mysql_help_topic_secondary_indexes) / sizeof(mysql_help_topic_secondary_indexes[0])
        },
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_NDB_BINLOG_INDEX,
          "ndb_binlog_index",
          mysql_ndb_binlog_index_columns,
          sizeof(mysql_ndb_binlog_index_columns) / sizeof(mysql_ndb_binlog_index_columns[0])},
         mysql_ndb_binlog_index_column_keys,
         mysql_ndb_binlog_index_column_extras,
         mysql_ndb_binlog_index_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
};

size_t mylite_execution_catalog_mysql_service_system_table_definition_count(void) {
    return sizeof(mysql_service_system_table_definitions) /
           sizeof(mysql_service_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_mysql_service_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_mysql_service_system_table_definition_count()) {
        return NULL;
    }
    return &mysql_service_system_table_definitions[index];
}
