#include "mylite_execution_catalog_system_tables_internal.h"

static const struct mylite_execution_catalog_column_definition
    performance_schema_accounts_columns[] = {
        {"USER",
         NULL,
         "YES",
         "char",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "char(32)"},
        {"HOST",
         NULL,
         "YES",
         "char",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "char(255)"},
        {"CURRENT_CONNECTIONS",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"TOTAL_CONNECTIONS",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"MAX_SESSION_CONTROLLED_MEMORY",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"MAX_SESSION_TOTAL_MEMORY",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const char *const performance_schema_accounts_column_keys[] = {
    "MUL",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_accounts_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_accounts_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    performance_schema_accounts_secondary_indexes[] = {
        {"ACCOUNT", 0U, NULL, "0", true, NULL, "HASH"},
        {"ACCOUNT", 1U, NULL, "0", true, NULL, "HASH"},
};

static const struct mylite_execution_catalog_column_definition performance_schema_hosts_columns[] =
    {
        {"HOST",
         NULL,
         "YES",
         "char",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "char(255)"},
        {"CURRENT_CONNECTIONS",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"TOTAL_CONNECTIONS",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"MAX_SESSION_CONTROLLED_MEMORY",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"MAX_SESSION_TOTAL_MEMORY",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const char *const performance_schema_hosts_column_keys[] = {
    "UNI",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_hosts_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_hosts_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    performance_schema_hosts_secondary_indexes[] = {
        {"HOST", 0U, NULL, "0", true, NULL, "HASH"},
};

static const struct mylite_execution_catalog_column_definition performance_schema_users_columns[] =
    {
        {"USER",
         NULL,
         "YES",
         "char",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "char(32)"},
        {"CURRENT_CONNECTIONS",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"TOTAL_CONNECTIONS",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"MAX_SESSION_CONTROLLED_MEMORY",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"MAX_SESSION_TOTAL_MEMORY",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const char *const performance_schema_users_column_keys[] = {
    "UNI",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_users_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_users_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    performance_schema_users_secondary_indexes[] = {
        {"USER", 0U, NULL, "0", true, NULL, "HASH"},
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_processlist_columns[] = {
        {"ID", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
        {"USER",
         NULL,
         "YES",
         "varchar",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(32)"},
        {"HOST",
         NULL,
         "YES",
         "varchar",
         "261",
         "261",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(261)"},
        {"DB",
         NULL,
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"COMMAND",
         NULL,
         "YES",
         "varchar",
         "16",
         "64",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(16)"},
        {"TIME", NULL, "YES", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"STATE",
         NULL,
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"INFO",
         NULL,
         "YES",
         "longtext",
         "4294967295",
         "4294967295",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "longtext"},
        {"EXECUTION_ENGINE",
         NULL,
         "YES",
         "enum",
         "9",
         "36",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('PRIMARY','SECONDARY')"},
};

static const char *const performance_schema_processlist_column_keys[] = {
    "PRI",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_processlist_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_processlist_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_processlist_primary_key_columns[] = {
    0U,
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_threads_columns[] = {
        {"THREAD_ID",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"NAME",
         NULL,
         "NO",
         "varchar",
         "128",
         "512",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(128)"},
        {"TYPE",
         NULL,
         "NO",
         "varchar",
         "10",
         "40",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(10)"},
        {"PROCESSLIST_ID",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PROCESSLIST_USER",
         NULL,
         "YES",
         "varchar",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(32)"},
        {"PROCESSLIST_HOST",
         NULL,
         "YES",
         "varchar",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "varchar(255)"},
        {"PROCESSLIST_DB",
         NULL,
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"PROCESSLIST_COMMAND",
         NULL,
         "YES",
         "varchar",
         "16",
         "64",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(16)"},
        {"PROCESSLIST_TIME",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"PROCESSLIST_STATE",
         NULL,
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"PROCESSLIST_INFO",
         NULL,
         "YES",
         "longtext",
         "4294967295",
         "4294967295",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "longtext"},
        {"PARENT_THREAD_ID",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"ROLE",
         NULL,
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"INSTRUMENTED",
         NULL,
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
        {"HISTORY",
         NULL,
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
        {"CONNECTION_TYPE",
         NULL,
         "YES",
         "varchar",
         "16",
         "64",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(16)"},
        {"THREAD_OS_ID",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"RESOURCE_GROUP",
         NULL,
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"EXECUTION_ENGINE",
         NULL,
         "YES",
         "enum",
         "9",
         "36",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('PRIMARY','SECONDARY')"},
        {"CONTROLLED_MEMORY",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"MAX_CONTROLLED_MEMORY",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"TOTAL_MEMORY",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"MAX_TOTAL_MEMORY",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"TELEMETRY_ACTIVE",
         NULL,
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
};

static const char *const performance_schema_threads_column_keys[] = {
    "PRI", "MUL", "", "MUL", "MUL", "MUL", "", "", "", "", "", "",
    "",    "",    "", "",    "MUL", "MUL", "", "", "", "", "", "",
};

static const char *const performance_schema_threads_column_extras[] = {
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
};

static const char *const performance_schema_threads_column_privileges[] = {
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
    "select,insert,update,references", "select,insert,update,references",
};

static const size_t performance_schema_threads_primary_key_columns[] = {
    0U,
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    performance_schema_threads_secondary_indexes[] = {
        {"NAME", 1U, NULL, "1", false, NULL, "HASH"},
        {"PROCESSLIST_ACCOUNT", 4U, NULL, "1", false, NULL, "HASH"},
        {"PROCESSLIST_ACCOUNT", 5U, NULL, "1", false, NULL, "HASH"},
        {"PROCESSLIST_HOST", 5U, NULL, "1", false, NULL, "HASH"},
        {"PROCESSLIST_ID", 3U, NULL, "1", false, NULL, "HASH"},
        {"RESOURCE_GROUP", 17U, NULL, "1", false, NULL, "HASH"},
        {"THREAD_OS_ID", 16U, NULL, "1", false, NULL, "HASH"},
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_connection_attribute_columns[] = {
        {"PROCESSLIST_ID",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"ATTR_NAME",
         NULL,
         "NO",
         "varchar",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "varchar(32)"},
        {"ATTR_VALUE",
         NULL,
         "YES",
         "varchar",
         "1024",
         "4096",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "varchar(1024)"},
        {"ORDINAL_POSITION", NULL, "YES", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
};

static const char *const performance_schema_connection_attribute_column_keys[] = {
    "PRI",
    "PRI",
    "",
    "",
};

static const char *const performance_schema_connection_attribute_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_connection_attribute_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_connection_attribute_primary_key_columns[] = {
    0U,
    1U,
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_variable_status_columns[] = {
        {"VARIABLE_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"VARIABLE_VALUE",
         NULL,
         "YES",
         "varchar",
         "1024",
         "4096",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(1024)"},
};

static const char *const performance_schema_variable_status_column_keys[] = {
    "PRI",
    "",
};

static const char *const performance_schema_variable_status_column_extras[] = {
    "",
    "",
};

static const char *const performance_schema_variable_status_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_variable_status_primary_key_columns[] = {
    0U,
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_variables_info_columns[] = {
        {"VARIABLE_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"VARIABLE_SOURCE",
         NULL,
         "YES",
         "enum",
         "12",
         "48",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('COMPILED','GLOBAL','SERVER','EXPLICIT','EXTRA','USER','LOGIN','COMMAND_LINE','"
         "PERSISTED','DYNAMIC')"},
        {"VARIABLE_PATH",
         NULL,
         "YES",
         "varchar",
         "1024",
         "4096",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(1024)"},
        {"MIN_VALUE",
         NULL,
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"MAX_VALUE",
         NULL,
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"SET_TIME",
         NULL,
         "YES",
         "timestamp",
         NULL,
         NULL,
         NULL,
         NULL,
         "6",
         NULL,
         NULL,
         "timestamp(6)"},
        {"SET_USER",
         NULL,
         "YES",
         "char",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "char(32)"},
        {"SET_HOST",
         NULL,
         "YES",
         "char",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "char(255)"},
};

static const char *const performance_schema_variables_info_column_keys[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_variables_info_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_variables_info_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_thread_variable_status_columns[] = {
        {"THREAD_ID",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"VARIABLE_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"VARIABLE_VALUE",
         NULL,
         "YES",
         "varchar",
         "1024",
         "4096",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(1024)"},
};

static const char *const performance_schema_thread_variable_status_column_keys[] = {
    "PRI",
    "PRI",
    "",
};

static const char *const performance_schema_thread_variable_status_column_extras[] = {
    "",
    "",
    "",
};

static const char *const performance_schema_thread_variable_status_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_thread_variable_status_primary_key_columns[] = {
    0U,
    1U,
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_status_by_account_columns[] = {
        {"USER",
         NULL,
         "YES",
         "char",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "char(32)"},
        {"HOST",
         NULL,
         "YES",
         "char",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "char(255)"},
        {"VARIABLE_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"VARIABLE_VALUE",
         NULL,
         "YES",
         "varchar",
         "1024",
         "4096",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(1024)"},
};

static const char *const performance_schema_status_by_account_column_keys[] = {
    "MUL",
    "",
    "",
    "",
};

static const char *const performance_schema_status_by_account_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_status_by_account_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    performance_schema_status_by_account_secondary_indexes[] = {
        {"ACCOUNT", 0U, NULL, "0", true, NULL, "HASH"},
        {"ACCOUNT", 1U, NULL, "0", true, NULL, "HASH"},
        {"ACCOUNT", 2U, NULL, "0", true, NULL, "HASH"},
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_status_by_host_columns[] = {
        {"HOST",
         NULL,
         "YES",
         "char",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "char(255)"},
        {"VARIABLE_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"VARIABLE_VALUE",
         NULL,
         "YES",
         "varchar",
         "1024",
         "4096",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(1024)"},
};

static const char *const performance_schema_status_by_host_column_keys[] = {
    "MUL",
    "",
    "",
};

static const char *const performance_schema_status_by_host_column_extras[] = {
    "",
    "",
    "",
};

static const char *const performance_schema_status_by_host_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    performance_schema_status_by_host_secondary_indexes[] = {
        {"HOST", 0U, NULL, "0", true, NULL, "HASH"},
        {"HOST", 1U, NULL, "0", true, NULL, "HASH"},
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_status_by_user_columns[] = {
        {"USER",
         NULL,
         "YES",
         "char",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "char(32)"},
        {"VARIABLE_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"VARIABLE_VALUE",
         NULL,
         "YES",
         "varchar",
         "1024",
         "4096",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(1024)"},
};

static const char *const performance_schema_status_by_user_column_keys[] = {
    "MUL",
    "",
    "",
};

static const char *const performance_schema_status_by_user_column_extras[] = {
    "",
    "",
    "",
};

static const char *const performance_schema_status_by_user_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    performance_schema_status_by_user_secondary_indexes[] = {
        {"USER", 0U, NULL, "0", true, NULL, "HASH"},
        {"USER", 1U, NULL, "0", true, NULL, "HASH"},
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_performance_timer_columns[] = {
        {"TIMER_NAME",
         NULL,
         "NO",
         "enum",
         "11",
         "44",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('CYCLE','NANOSECOND','MICROSECOND','MILLISECOND','THREAD_CPU')"},
        {"TIMER_FREQUENCY", NULL, "YES", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"
        },
        {"TIMER_RESOLUTION",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "19",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint"},
        {"TIMER_OVERHEAD", NULL, "YES", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"
        },
};

static const char *const performance_schema_performance_timer_column_keys[] = {
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_performance_timer_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_performance_timer_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_setup_actor_columns[] = {
        {"HOST",
         "%",
         "NO",
         "char",
         "255",
         "255",
         NULL,
         NULL,
         NULL,
         "ascii",
         "ascii_general_ci",
         "char(255)"},
        {"USER",
         "%",
         "NO",
         "char",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "char(32)"},
        {"ROLE",
         "%",
         "NO",
         "char",
         "32",
         "128",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_bin",
         "char(32)"},
        {"ENABLED",
         "YES",
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
        {"HISTORY",
         "YES",
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
};

static const char *const performance_schema_setup_actor_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "",
    "",
};

static const char *const performance_schema_setup_actor_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_setup_actor_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_setup_actor_primary_key_columns[] = {
    0U,
    1U,
    2U,
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_setup_consumer_columns[] = {
        {"NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"ENABLED",
         NULL,
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
};

static const char *const performance_schema_setup_consumer_column_keys[] = {
    "PRI",
    "",
};

static const char *const performance_schema_setup_consumer_column_extras[] = {
    "",
    "",
};

static const char *const performance_schema_setup_consumer_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_setup_consumer_primary_key_columns[] = {
    0U,
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_setup_logger_columns[] = {
        {"NAME",
         NULL,
         "NO",
         "varchar",
         "128",
         "512",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(128)"},
        {"LEVEL",
         NULL,
         "NO",
         "enum",
         "5",
         "20",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('none','error','warn','info','debug')"},
        {"DESCRIPTION",
         NULL,
         "YES",
         "varchar",
         "1023",
         "4092",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(1023)"},
};

static const char *const performance_schema_setup_logger_column_keys[] = {
    "",
    "",
    "",
};

static const char *const performance_schema_setup_logger_column_extras[] = {
    "",
    "",
    "",
};

static const char *const performance_schema_setup_logger_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_setup_meter_columns[] = {
        {"NAME",
         NULL,
         "NO",
         "varchar",
         "63",
         "252",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(63)"},
        {"FREQUENCY",
         NULL,
         "NO",
         "mediumint",
         NULL,
         NULL,
         "7",
         "0",
         NULL,
         NULL,
         NULL,
         "mediumint unsigned"},
        {"ENABLED",
         NULL,
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
        {"DESCRIPTION",
         NULL,
         "YES",
         "varchar",
         "1023",
         "4092",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(1023)"},
};

static const char *const performance_schema_setup_meter_column_keys[] = {
    "PRI",
    "",
    "",
    "",
};

static const char *const performance_schema_setup_meter_column_extras[] = {
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_setup_meter_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_setup_meter_primary_key_columns[] = {
    0U,
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_setup_metric_columns[] = {
        {"NAME",
         NULL,
         "NO",
         "varchar",
         "63",
         "252",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(63)"},
        {"METER",
         NULL,
         "NO",
         "varchar",
         "63",
         "252",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(63)"},
        {"METRIC_TYPE",
         NULL,
         "NO",
         "enum",
         "20",
         "80",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('ASYNC COUNTER','ASYNC UPDOWN COUNTER','ASYNC GAUGE COUNTER')"},
        {"NUM_TYPE",
         NULL,
         "NO",
         "enum",
         "7",
         "28",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('INTEGER','DOUBLE')"},
        {"UNIT",
         NULL,
         "YES",
         "varchar",
         "63",
         "252",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(63)"},
        {"DESCRIPTION",
         NULL,
         "YES",
         "varchar",
         "1023",
         "4092",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(1023)"},
};

static const char *const performance_schema_setup_metric_column_keys[] = {
    "PRI",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_setup_metric_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_setup_metric_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_setup_metric_primary_key_columns[] = {
    0U,
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_setup_object_columns[] = {
        {"OBJECT_TYPE",
         "TABLE",
         "NO",
         "enum",
         "9",
         "36",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('EVENT','FUNCTION','PROCEDURE','TABLE','TRIGGER')"},
        {"OBJECT_SCHEMA",
         "%",
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"OBJECT_NAME",
         "%",
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"ENABLED",
         "YES",
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
        {"TIMED",
         "YES",
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
};

static const char *const performance_schema_setup_object_column_keys[] = {
    "MUL",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_setup_object_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_setup_object_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    performance_schema_setup_object_secondary_indexes[] = {
        {"OBJECT", 0U, NULL, "0", true, NULL, "HASH"},
        {"OBJECT", 1U, NULL, "0", true, NULL, "HASH"},
        {"OBJECT", 2U, NULL, "0", true, NULL, "HASH"},
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_setup_thread_columns[] = {
        {"NAME",
         NULL,
         "NO",
         "varchar",
         "128",
         "512",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(128)"},
        {"ENABLED",
         NULL,
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
        {"HISTORY",
         NULL,
         "NO",
         "enum",
         "3",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "enum('YES','NO')"},
        {"PROPERTIES",
         NULL,
         "NO",
         "set",
         "14",
         "56",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "set('singleton','user')"},
        {"VOLATILITY", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
        {"DOCUMENTATION",
         NULL,
         "YES",
         "longtext",
         "4294967295",
         "4294967295",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "longtext"},
};

static const char *const performance_schema_setup_thread_column_keys[] = {
    "PRI",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_setup_thread_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_setup_thread_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_setup_thread_primary_key_columns[] = {
    0U,
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_table_handle_columns[] = {
        {"OBJECT_TYPE",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"OBJECT_SCHEMA",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"OBJECT_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"OBJECT_INSTANCE_BEGIN",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"OWNER_THREAD_ID",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"OWNER_EVENT_ID",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"INTERNAL_LOCK",
         NULL,
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"EXTERNAL_LOCK",
         NULL,
         "YES",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
};

static const char *const performance_schema_table_handle_column_keys[] = {
    "MUL",
    "",
    "",
    "PRI",
    "MUL",
    "",
    "",
    "",
};

static const char *const performance_schema_table_handle_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_table_handle_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_table_handle_primary_key_columns[] = {
    3U,
};

static const struct mylite_execution_catalog_mysql_system_secondary_index
    performance_schema_table_handle_secondary_indexes[] = {
        {"OBJECT_TYPE", 0U, NULL, "1", false, NULL, "HASH"},
        {"OBJECT_TYPE", 1U, NULL, "1", false, NULL, "HASH"},
        {"OBJECT_TYPE", 2U, NULL, "1", false, NULL, "HASH"},
        {"OWNER_THREAD_ID", 4U, NULL, "1", false, NULL, "HASH"},
        {"OWNER_THREAD_ID", 5U, NULL, "1", false, NULL, "HASH"},
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_user_variable_by_thread_columns[] = {
        {"THREAD_ID",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"VARIABLE_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"VARIABLE_VALUE",
         NULL,
         "YES",
         "longblob",
         "4294967295",
         "4294967295",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "longblob"},
};

static const char *const performance_schema_user_variable_by_thread_column_keys[] = {
    "PRI",
    "PRI",
    "",
};

static const char *const performance_schema_user_variable_by_thread_column_extras[] = {
    "",
    "",
    "",
};

static const char *const performance_schema_user_variable_by_thread_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_user_variable_by_thread_primary_key_columns[] = {
    0U,
    1U,
};

static const struct mylite_execution_catalog_column_definition
    performance_schema_user_defined_function_columns[] = {
        {"UDF_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(64)"},
        {"UDF_RETURN_TYPE",
         NULL,
         "NO",
         "varchar",
         "20",
         "80",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(20)"},
        {"UDF_TYPE",
         NULL,
         "NO",
         "varchar",
         "20",
         "80",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(20)"},
        {"UDF_LIBRARY",
         NULL,
         "YES",
         "varchar",
         "1024",
         "4096",
         NULL,
         NULL,
         NULL,
         "utf8mb4",
         "utf8mb4_0900_ai_ci",
         "varchar(1024)"},
        {"UDF_USAGE_COUNT", NULL, "YES", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"
        },
};

static const char *const performance_schema_user_defined_function_column_keys[] = {
    "PRI",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_user_defined_function_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const performance_schema_user_defined_function_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const size_t performance_schema_user_defined_function_primary_key_columns[] = {
    0U,
};

static const struct mylite_execution_catalog_mysql_system_table
    performance_schema_system_table_definitions[] = {
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_ACCOUNTS,
          "accounts",
          performance_schema_accounts_columns,
          sizeof(performance_schema_accounts_columns) /
              sizeof(performance_schema_accounts_columns[0])},
         performance_schema_accounts_column_keys,
         performance_schema_accounts_column_extras,
         performance_schema_accounts_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         performance_schema_accounts_secondary_indexes,
         sizeof(performance_schema_accounts_secondary_indexes) /
             sizeof(performance_schema_accounts_secondary_indexes[0])},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_GLOBAL_STATUS,
          "global_status",
          performance_schema_variable_status_columns,
          sizeof(performance_schema_variable_status_columns) /
              sizeof(performance_schema_variable_status_columns[0])},
         performance_schema_variable_status_column_keys,
         performance_schema_variable_status_column_extras,
         performance_schema_variable_status_column_privileges,
         NULL,
         performance_schema_variable_status_primary_key_columns,
         sizeof(performance_schema_variable_status_primary_key_columns) /
             sizeof(performance_schema_variable_status_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_GLOBAL_VARIABLES,
          "global_variables",
          performance_schema_variable_status_columns,
          sizeof(performance_schema_variable_status_columns) /
              sizeof(performance_schema_variable_status_columns[0])},
         performance_schema_variable_status_column_keys,
         performance_schema_variable_status_column_extras,
         performance_schema_variable_status_column_privileges,
         NULL,
         performance_schema_variable_status_primary_key_columns,
         sizeof(performance_schema_variable_status_primary_key_columns) /
             sizeof(performance_schema_variable_status_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_PERSISTED_VARIABLES,
          "persisted_variables",
          performance_schema_variable_status_columns,
          sizeof(performance_schema_variable_status_columns) /
              sizeof(performance_schema_variable_status_columns[0])},
         performance_schema_variable_status_column_keys,
         performance_schema_variable_status_column_extras,
         performance_schema_variable_status_column_privileges,
         NULL,
         performance_schema_variable_status_primary_key_columns,
         sizeof(performance_schema_variable_status_primary_key_columns) /
             sizeof(performance_schema_variable_status_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_HOSTS,
          "hosts",
          performance_schema_hosts_columns,
          sizeof(performance_schema_hosts_columns) / sizeof(performance_schema_hosts_columns[0])},
         performance_schema_hosts_column_keys,
         performance_schema_hosts_column_extras,
         performance_schema_hosts_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         performance_schema_hosts_secondary_indexes,
         sizeof(performance_schema_hosts_secondary_indexes) /
             sizeof(performance_schema_hosts_secondary_indexes[0])},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_PERFORMANCE_TIMERS,
          "performance_timers",
          performance_schema_performance_timer_columns,
          sizeof(performance_schema_performance_timer_columns) /
              sizeof(performance_schema_performance_timer_columns[0])},
         performance_schema_performance_timer_column_keys,
         performance_schema_performance_timer_column_extras,
         performance_schema_performance_timer_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_PROCESSLIST,
          "processlist",
          performance_schema_processlist_columns,
          sizeof(performance_schema_processlist_columns) /
              sizeof(performance_schema_processlist_columns[0])},
         performance_schema_processlist_column_keys,
         performance_schema_processlist_column_extras,
         performance_schema_processlist_column_privileges,
         NULL,
         performance_schema_processlist_primary_key_columns,
         sizeof(performance_schema_processlist_primary_key_columns) /
             sizeof(performance_schema_processlist_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SETUP_ACTORS,
          "setup_actors",
          performance_schema_setup_actor_columns,
          sizeof(performance_schema_setup_actor_columns) /
              sizeof(performance_schema_setup_actor_columns[0])},
         performance_schema_setup_actor_column_keys,
         performance_schema_setup_actor_column_extras,
         performance_schema_setup_actor_column_privileges,
         NULL,
         performance_schema_setup_actor_primary_key_columns,
         sizeof(performance_schema_setup_actor_primary_key_columns) /
             sizeof(performance_schema_setup_actor_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SETUP_CONSUMERS,
          "setup_consumers",
          performance_schema_setup_consumer_columns,
          sizeof(performance_schema_setup_consumer_columns) /
              sizeof(performance_schema_setup_consumer_columns[0])},
         performance_schema_setup_consumer_column_keys,
         performance_schema_setup_consumer_column_extras,
         performance_schema_setup_consumer_column_privileges,
         NULL,
         performance_schema_setup_consumer_primary_key_columns,
         sizeof(performance_schema_setup_consumer_primary_key_columns) /
             sizeof(performance_schema_setup_consumer_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SETUP_LOGGERS,
          "setup_loggers",
          performance_schema_setup_logger_columns,
          sizeof(performance_schema_setup_logger_columns) /
              sizeof(performance_schema_setup_logger_columns[0])},
         performance_schema_setup_logger_column_keys,
         performance_schema_setup_logger_column_extras,
         performance_schema_setup_logger_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SETUP_METERS,
          "setup_meters",
          performance_schema_setup_meter_columns,
          sizeof(performance_schema_setup_meter_columns) /
              sizeof(performance_schema_setup_meter_columns[0])},
         performance_schema_setup_meter_column_keys,
         performance_schema_setup_meter_column_extras,
         performance_schema_setup_meter_column_privileges,
         NULL,
         performance_schema_setup_meter_primary_key_columns,
         sizeof(performance_schema_setup_meter_primary_key_columns) /
             sizeof(performance_schema_setup_meter_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SETUP_METRICS,
          "setup_metrics",
          performance_schema_setup_metric_columns,
          sizeof(performance_schema_setup_metric_columns) /
              sizeof(performance_schema_setup_metric_columns[0])},
         performance_schema_setup_metric_column_keys,
         performance_schema_setup_metric_column_extras,
         performance_schema_setup_metric_column_privileges,
         NULL,
         performance_schema_setup_metric_primary_key_columns,
         sizeof(performance_schema_setup_metric_primary_key_columns) /
             sizeof(performance_schema_setup_metric_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SETUP_OBJECTS,
          "setup_objects",
          performance_schema_setup_object_columns,
          sizeof(performance_schema_setup_object_columns) /
              sizeof(performance_schema_setup_object_columns[0])},
         performance_schema_setup_object_column_keys,
         performance_schema_setup_object_column_extras,
         performance_schema_setup_object_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         performance_schema_setup_object_secondary_indexes,
         sizeof(performance_schema_setup_object_secondary_indexes) /
             sizeof(performance_schema_setup_object_secondary_indexes[0])},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SETUP_THREADS,
          "setup_threads",
          performance_schema_setup_thread_columns,
          sizeof(performance_schema_setup_thread_columns) /
              sizeof(performance_schema_setup_thread_columns[0])},
         performance_schema_setup_thread_column_keys,
         performance_schema_setup_thread_column_extras,
         performance_schema_setup_thread_column_privileges,
         NULL,
         performance_schema_setup_thread_primary_key_columns,
         sizeof(performance_schema_setup_thread_primary_key_columns) /
             sizeof(performance_schema_setup_thread_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SESSION_ACCOUNT_CONNECT_ATTRS,
          "session_account_connect_attrs",
          performance_schema_connection_attribute_columns,
          sizeof(performance_schema_connection_attribute_columns) /
              sizeof(performance_schema_connection_attribute_columns[0])},
         performance_schema_connection_attribute_column_keys,
         performance_schema_connection_attribute_column_extras,
         performance_schema_connection_attribute_column_privileges,
         NULL,
         performance_schema_connection_attribute_primary_key_columns,
         sizeof(performance_schema_connection_attribute_primary_key_columns) /
             sizeof(performance_schema_connection_attribute_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SESSION_CONNECT_ATTRS,
          "session_connect_attrs",
          performance_schema_connection_attribute_columns,
          sizeof(performance_schema_connection_attribute_columns) /
              sizeof(performance_schema_connection_attribute_columns[0])},
         performance_schema_connection_attribute_column_keys,
         performance_schema_connection_attribute_column_extras,
         performance_schema_connection_attribute_column_privileges,
         NULL,
         performance_schema_connection_attribute_primary_key_columns,
         sizeof(performance_schema_connection_attribute_primary_key_columns) /
             sizeof(performance_schema_connection_attribute_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_STATUS_BY_ACCOUNT,
          "status_by_account",
          performance_schema_status_by_account_columns,
          sizeof(performance_schema_status_by_account_columns) /
              sizeof(performance_schema_status_by_account_columns[0])},
         performance_schema_status_by_account_column_keys,
         performance_schema_status_by_account_column_extras,
         performance_schema_status_by_account_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         performance_schema_status_by_account_secondary_indexes,
         sizeof(performance_schema_status_by_account_secondary_indexes) /
             sizeof(performance_schema_status_by_account_secondary_indexes[0])},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_STATUS_BY_HOST,
          "status_by_host",
          performance_schema_status_by_host_columns,
          sizeof(performance_schema_status_by_host_columns) /
              sizeof(performance_schema_status_by_host_columns[0])},
         performance_schema_status_by_host_column_keys,
         performance_schema_status_by_host_column_extras,
         performance_schema_status_by_host_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         performance_schema_status_by_host_secondary_indexes,
         sizeof(performance_schema_status_by_host_secondary_indexes) /
             sizeof(performance_schema_status_by_host_secondary_indexes[0])},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_STATUS_BY_THREAD,
          "status_by_thread",
          performance_schema_thread_variable_status_columns,
          sizeof(performance_schema_thread_variable_status_columns) /
              sizeof(performance_schema_thread_variable_status_columns[0])},
         performance_schema_thread_variable_status_column_keys,
         performance_schema_thread_variable_status_column_extras,
         performance_schema_thread_variable_status_column_privileges,
         NULL,
         performance_schema_thread_variable_status_primary_key_columns,
         sizeof(performance_schema_thread_variable_status_primary_key_columns) /
             sizeof(performance_schema_thread_variable_status_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_STATUS_BY_USER,
          "status_by_user",
          performance_schema_status_by_user_columns,
          sizeof(performance_schema_status_by_user_columns) /
              sizeof(performance_schema_status_by_user_columns[0])},
         performance_schema_status_by_user_column_keys,
         performance_schema_status_by_user_column_extras,
         performance_schema_status_by_user_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         performance_schema_status_by_user_secondary_indexes,
         sizeof(performance_schema_status_by_user_secondary_indexes) /
             sizeof(performance_schema_status_by_user_secondary_indexes[0])},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_TABLE_HANDLES,
          "table_handles",
          performance_schema_table_handle_columns,
          sizeof(performance_schema_table_handle_columns) /
              sizeof(performance_schema_table_handle_columns[0])},
         performance_schema_table_handle_column_keys,
         performance_schema_table_handle_column_extras,
         performance_schema_table_handle_column_privileges,
         NULL,
         performance_schema_table_handle_primary_key_columns,
         sizeof(performance_schema_table_handle_primary_key_columns) /
             sizeof(performance_schema_table_handle_primary_key_columns[0]),
         NULL,
         performance_schema_table_handle_secondary_indexes,
         sizeof(performance_schema_table_handle_secondary_indexes) /
             sizeof(performance_schema_table_handle_secondary_indexes[0])},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_THREADS,
          "threads",
          performance_schema_threads_columns,
          sizeof(performance_schema_threads_columns) / sizeof(performance_schema_threads_columns[0])
         },
         performance_schema_threads_column_keys,
         performance_schema_threads_column_extras,
         performance_schema_threads_column_privileges,
         NULL,
         performance_schema_threads_primary_key_columns,
         sizeof(performance_schema_threads_primary_key_columns) /
             sizeof(performance_schema_threads_primary_key_columns[0]),
         NULL,
         performance_schema_threads_secondary_indexes,
         sizeof(performance_schema_threads_secondary_indexes) /
             sizeof(performance_schema_threads_secondary_indexes[0])},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_USER_DEFINED_FUNCTIONS,
          "user_defined_functions",
          performance_schema_user_defined_function_columns,
          sizeof(performance_schema_user_defined_function_columns) /
              sizeof(performance_schema_user_defined_function_columns[0])},
         performance_schema_user_defined_function_column_keys,
         performance_schema_user_defined_function_column_extras,
         performance_schema_user_defined_function_column_privileges,
         NULL,
         performance_schema_user_defined_function_primary_key_columns,
         sizeof(performance_schema_user_defined_function_primary_key_columns) /
             sizeof(performance_schema_user_defined_function_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_USERS,
          "users",
          performance_schema_users_columns,
          sizeof(performance_schema_users_columns) / sizeof(performance_schema_users_columns[0])},
         performance_schema_users_column_keys,
         performance_schema_users_column_extras,
         performance_schema_users_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         performance_schema_users_secondary_indexes,
         sizeof(performance_schema_users_secondary_indexes) /
             sizeof(performance_schema_users_secondary_indexes[0])},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_USER_VARIABLES_BY_THREAD,
          "user_variables_by_thread",
          performance_schema_user_variable_by_thread_columns,
          sizeof(performance_schema_user_variable_by_thread_columns) /
              sizeof(performance_schema_user_variable_by_thread_columns[0])},
         performance_schema_user_variable_by_thread_column_keys,
         performance_schema_user_variable_by_thread_column_extras,
         performance_schema_user_variable_by_thread_column_privileges,
         NULL,
         performance_schema_user_variable_by_thread_primary_key_columns,
         sizeof(performance_schema_user_variable_by_thread_primary_key_columns) /
             sizeof(performance_schema_user_variable_by_thread_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SESSION_STATUS,
          "session_status",
          performance_schema_variable_status_columns,
          sizeof(performance_schema_variable_status_columns) /
              sizeof(performance_schema_variable_status_columns[0])},
         performance_schema_variable_status_column_keys,
         performance_schema_variable_status_column_extras,
         performance_schema_variable_status_column_privileges,
         NULL,
         performance_schema_variable_status_primary_key_columns,
         sizeof(performance_schema_variable_status_primary_key_columns) /
             sizeof(performance_schema_variable_status_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_SESSION_VARIABLES,
          "session_variables",
          performance_schema_variable_status_columns,
          sizeof(performance_schema_variable_status_columns) /
              sizeof(performance_schema_variable_status_columns[0])},
         performance_schema_variable_status_column_keys,
         performance_schema_variable_status_column_extras,
         performance_schema_variable_status_column_privileges,
         NULL,
         performance_schema_variable_status_primary_key_columns,
         sizeof(performance_schema_variable_status_primary_key_columns) /
             sizeof(performance_schema_variable_status_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_VARIABLES_BY_THREAD,
          "variables_by_thread",
          performance_schema_thread_variable_status_columns,
          sizeof(performance_schema_thread_variable_status_columns) /
              sizeof(performance_schema_thread_variable_status_columns[0])},
         performance_schema_thread_variable_status_column_keys,
         performance_schema_thread_variable_status_column_extras,
         performance_schema_thread_variable_status_column_privileges,
         NULL,
         performance_schema_thread_variable_status_primary_key_columns,
         sizeof(performance_schema_thread_variable_status_primary_key_columns) /
             sizeof(performance_schema_thread_variable_status_primary_key_columns[0]),
         NULL,
         NULL,
         0U},
        {"performance_schema",
         {MYLITE_EXECUTION_CATALOG_TABLE_PERFORMANCE_SCHEMA_VARIABLES_INFO,
          "variables_info",
          performance_schema_variables_info_columns,
          sizeof(performance_schema_variables_info_columns) /
              sizeof(performance_schema_variables_info_columns[0])},
         performance_schema_variables_info_column_keys,
         performance_schema_variables_info_column_extras,
         performance_schema_variables_info_column_privileges,
         NULL,
         NULL,
         0U,
         NULL,
         NULL,
         0U},
};

size_t mylite_execution_catalog_performance_schema_system_table_definition_count(void) {
    return sizeof(performance_schema_system_table_definitions) /
           sizeof(performance_schema_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_performance_schema_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_performance_schema_system_table_definition_count()) {
        return NULL;
    }
    return &performance_schema_system_table_definitions[index];
}
