#include "mylite_execution_catalog_system_tables_internal.h"

static const struct mylite_execution_catalog_column_definition mysql_plugin_columns[] = {
    {"name",
     "",
     "NO",
     "varchar",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(64)"},
    {"dl",
     "",
     "NO",
     "varchar",
     "128",
     "384",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(128)"},
};

static const char *const mysql_plugin_column_keys[] = {
    "PRI",
    "",
};

static const char *const mysql_plugin_column_extras[] = {
    "",
    "",
};

static const char *const mysql_plugin_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_server_cost_columns[] = {
    {"cost_name",
     NULL,
     "NO",
     "varchar",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(64)"},
    {"cost_value", NULL, "YES", "float", NULL, NULL, "12", NULL, NULL, NULL, NULL, "float"},
    {"last_update",
     "CURRENT_TIMESTAMP",
     "NO",
     "timestamp",
     NULL,
     NULL,
     NULL,
     NULL,
     "0",
     NULL,
     NULL,
     "timestamp"},
    {"comment",
     NULL,
     "YES",
     "varchar",
     "1024",
     "3072",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "varchar(1024)"},
    {"default_value", NULL, "YES", "float", NULL, NULL, "12", NULL, NULL, NULL, NULL, "float"},
};

static const char *const mysql_server_cost_column_keys[] = {
    "PRI",
    "",
    "",
    "",
    "",
};

static const char *const mysql_server_cost_column_extras[] = {
    "",
    "",
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
    "",
    "VIRTUAL GENERATED",
};

static const char *const mysql_server_cost_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const char *const mysql_server_cost_column_generation_expressions[] = {
    "",
    "",
    "",
    "",
    ("(case `cost_name` when _utf8mb4\\'disk_temptable_create_cost\\' then 20.0 "
     "when _utf8mb4\\'disk_temptable_row_cost\\' then 0.5 when "
     "_utf8mb4\\'key_compare_cost\\' then 0.05 when "
     "_utf8mb4\\'memory_temptable_create_cost\\' then 1.0 when "
     "_utf8mb4\\'memory_temptable_row_cost\\' then 0.1 when "
     "_utf8mb4\\'row_evaluate_cost\\' then 0.1 else NULL end)"),
};

static const struct mylite_execution_catalog_column_definition mysql_servers_columns[] = {
    {"Server_name",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
    {"Host",
     "",
     "NO",
     "char",
     "255",
     "255",
     NULL,
     NULL,
     NULL,
     "ascii",
     "ascii_general_ci",
     "char(255)"},
    {"Db",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
    {"Username",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
    {"Password",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
    {"Port", "0", "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
    {"Socket",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
    {"Wrapper",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
    {"Owner",
     "",
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
};

static const char *const mysql_servers_column_keys[] = {
    "PRI",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_servers_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_servers_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_time_zone_columns[] = {
    {"Time_zone_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
    {"Use_leap_seconds",
     "N",
     "NO",
     "enum",
     "1",
     "3",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "enum('Y','N')"},
};

static const char *const mysql_time_zone_column_keys[] = {
    "PRI",
    "",
};

static const char *const mysql_time_zone_column_extras[] = {
    "auto_increment",
    "",
};

static const char *const mysql_time_zone_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    mysql_time_zone_leap_second_columns[] = {
        {"Transition_time", NULL, "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"
        },
        {"Correction", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
};

static const char *const mysql_time_zone_leap_second_column_keys[] = {
    "PRI",
    "",
};

static const char *const mysql_time_zone_leap_second_column_extras[] = {
    "",
    "",
};

static const char *const mysql_time_zone_leap_second_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_time_zone_name_columns[] = {
    {"Name",
     NULL,
     "NO",
     "char",
     "64",
     "192",
     NULL,
     NULL,
     NULL,
     "utf8mb3",
     "utf8mb3_general_ci",
     "char(64)"},
    {"Time_zone_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
};

static const char *const mysql_time_zone_name_column_keys[] = {
    "PRI",
    "",
};

static const char *const mysql_time_zone_name_column_extras[] = {
    "",
    "",
};

static const char *const mysql_time_zone_name_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    mysql_time_zone_transition_columns[] = {
        {"Time_zone_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"
        },
        {"Transition_time", NULL, "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"
        },
        {"Transition_type_id",
         NULL,
         "NO",
         "int",
         NULL,
         NULL,
         "10",
         "0",
         NULL,
         NULL,
         NULL,
         "int unsigned"},
};

static const char *const mysql_time_zone_transition_column_keys[] = {
    "PRI",
    "PRI",
    "",
};

static const char *const mysql_time_zone_transition_column_extras[] = {
    "",
    "",
    "",
};

static const char *const mysql_time_zone_transition_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition
    mysql_time_zone_transition_type_columns[] = {
        {"Time_zone_id", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"
        },
        {"Transition_type_id",
         NULL,
         "NO",
         "int",
         NULL,
         NULL,
         "10",
         "0",
         NULL,
         NULL,
         NULL,
         "int unsigned"},
        {"Offset", "0", "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int"},
        {"Is_DST", "0", "NO", "tinyint", NULL, NULL, "3", "0", NULL, NULL, NULL, "tinyint unsigned"
        },
        {"Abbreviation",
         "",
         "NO",
         "char",
         "8",
         "24",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "char(8)"},
};

static const char *const mysql_time_zone_transition_type_column_keys[] = {
    "PRI",
    "PRI",
    "",
    "",
    "",
};

static const char *const mysql_time_zone_transition_type_column_extras[] = {
    "",
    "",
    "",
    "",
    "",
};

static const char *const mysql_time_zone_transition_type_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_innodb_index_stats_columns[] =
    {
        {"database_name",
         NULL,
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(64)"},
        {"table_name",
         NULL,
         "NO",
         "varchar",
         "199",
         "597",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(199)"},
        {"index_name",
         NULL,
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(64)"},
        {"last_update",
         "CURRENT_TIMESTAMP",
         "NO",
         "timestamp",
         NULL,
         NULL,
         NULL,
         NULL,
         "0",
         NULL,
         NULL,
         "timestamp"},
        {"stat_name",
         NULL,
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(64)"},
        {"stat_value",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"sample_size",
         NULL,
         "YES",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"stat_description",
         NULL,
         "NO",
         "varchar",
         "1024",
         "3072",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(1024)"},
};

static const char *const mysql_innodb_index_stats_column_keys[] = {
    "PRI",
    "PRI",
    "PRI",
    "",
    "PRI",
    "",
    "",
    "",
};

static const char *const mysql_innodb_index_stats_column_extras[] = {
    "",
    "",
    "",
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
    "",
    "",
    "",
    "",
};

static const char *const mysql_innodb_index_stats_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_column_definition mysql_innodb_table_stats_columns[] =
    {
        {"database_name",
         NULL,
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(64)"},
        {"table_name",
         NULL,
         "NO",
         "varchar",
         "199",
         "597",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(199)"},
        {"last_update",
         "CURRENT_TIMESTAMP",
         "NO",
         "timestamp",
         NULL,
         NULL,
         NULL,
         NULL,
         "0",
         NULL,
         NULL,
         "timestamp"},
        {"n_rows", NULL, "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"
        },
        {"clustered_index_size",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"sum_of_other_index_sizes",
         NULL,
         "NO",
         "bigint",
         NULL,
         NULL,
         "20",
         "0",
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const char *const mysql_innodb_table_stats_column_keys[] = {
    "PRI",
    "PRI",
    "",
    "",
    "",
    "",
};

static const char *const mysql_innodb_table_stats_column_extras[] = {
    "",
    "",
    "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
    "",
    "",
    "",
};

static const char *const mysql_innodb_table_stats_column_privileges[] = {
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
    "select,insert,update,references",
};

static const struct mylite_execution_catalog_mysql_system_table
    mysql_misc_system_table_definitions[] = {
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_PLUGIN,
          "plugin",
          mysql_plugin_columns,
          sizeof(mysql_plugin_columns) / sizeof(mysql_plugin_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_plugin_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_plugin_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_plugin_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_SERVER_COST,
          "server_cost",
          mysql_server_cost_columns,
          sizeof(mysql_server_cost_columns) / sizeof(mysql_server_cost_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_server_cost_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_server_cost_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_server_cost_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_server_cost_column_generation_expressions),
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_SERVERS,
          "servers",
          mysql_servers_columns,
          sizeof(mysql_servers_columns) / sizeof(mysql_servers_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_servers_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_servers_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_servers_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_TIME_ZONE,
          "time_zone",
          mysql_time_zone_columns,
          sizeof(mysql_time_zone_columns) / sizeof(mysql_time_zone_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_TIME_ZONE_LEAP_SECOND,
          "time_zone_leap_second",
          mysql_time_zone_leap_second_columns,
          sizeof(mysql_time_zone_leap_second_columns) /
              sizeof(mysql_time_zone_leap_second_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_leap_second_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_leap_second_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_leap_second_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_TIME_ZONE_NAME,
          "time_zone_name",
          mysql_time_zone_name_columns,
          sizeof(mysql_time_zone_name_columns) / sizeof(mysql_time_zone_name_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_name_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_name_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_name_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_TIME_ZONE_TRANSITION,
          "time_zone_transition",
          mysql_time_zone_transition_columns,
          sizeof(mysql_time_zone_transition_columns) / sizeof(mysql_time_zone_transition_columns[0])
         },
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_transition_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_transition_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_transition_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_MYSQL_TIME_ZONE_TRANSITION_TYPE,
          "time_zone_transition_type",
          mysql_time_zone_transition_type_columns,
          sizeof(mysql_time_zone_transition_type_columns) /
              sizeof(mysql_time_zone_transition_type_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_transition_type_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_transition_type_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_time_zone_transition_type_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_INDEXES,
          "innodb_index_stats",
          mysql_innodb_index_stats_columns,
          sizeof(mysql_innodb_index_stats_columns) / sizeof(mysql_innodb_index_stats_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_innodb_index_stats_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_innodb_index_stats_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_innodb_index_stats_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
        {"mysql",
         {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_TABLESTATS,
          "innodb_table_stats",
          mysql_innodb_table_stats_columns,
          sizeof(mysql_innodb_table_stats_columns) / sizeof(mysql_innodb_table_stats_columns[0])},
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_innodb_table_stats_column_keys),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_innodb_table_stats_column_extras),
         MYLITE_EXECUTION_CATALOG_ARRAY(mysql_innodb_table_stats_column_privileges),
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U,
         MYLITE_EXECUTION_CATALOG_NO_ARRAY,
         NULL,
         0U},
};

size_t mylite_execution_catalog_mysql_misc_system_table_definition_count(void) {
    return sizeof(mysql_misc_system_table_definitions) /
           sizeof(mysql_misc_system_table_definitions[0]);
}

const struct mylite_execution_catalog_mysql_system_table *mylite_execution_catalog_mysql_misc_system_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_mysql_misc_system_table_definition_count()) {
        return NULL;
    }
    return &mysql_misc_system_table_definitions[index];
}
