#include "mylite_execution_catalog_information_schema_internal.h"

#include <stddef.h>

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_cmp_columns[] = {
        {"page_size", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"compress_ops", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"compress_ops_ok", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"compress_time", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"uncompress_ops", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"uncompress_time", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_cmpmem_columns[] = {
        {"page_size", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"buffer_pool_instance", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"pages_used", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"pages_free", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"relocation_ops", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint"},
        {"relocation_time", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_cmp_per_index_columns[] = {
        {"database_name",
         "",
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(192)"},
        {"table_name",
         "",
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(192)"},
        {"index_name",
         "",
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(192)"},
        {"compress_ops", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"compress_ops_ok", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"compress_time", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"uncompress_ops", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"uncompress_time", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_datafiles_columns[] = {
        {"SPACE",
         NULL,
         "YES",
         "varbinary",
         "256",
         "256",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "varbinary(256)"},
        {"PATH",
         NULL,
         "NO",
         "varchar",
         "512",
         "1536",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(512)"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_tablespaces_columns[] = {
        {"SPACE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"},
        {"NAME",
         "",
         "NO",
         "varchar",
         "218",
         "655",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(655)"},
        {"FLAG", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"},
        {"ROW_FORMAT",
         "",
         "YES",
         "varchar",
         "7",
         "22",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(22)"},
        {"PAGE_SIZE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"},
        {"ZIP_PAGE_SIZE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"
        },
        {"SPACE_TYPE",
         "",
         "YES",
         "varchar",
         "3",
         "10",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(10)"},
        {"FS_BLOCK_SIZE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"
        },
        {"FILE_SIZE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"ALLOCATED_SIZE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"AUTOEXTEND_SIZE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"SERVER_VERSION",
         "",
         "YES",
         "varchar",
         "3",
         "10",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(10)"},
        {"SPACE_VERSION", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"
        },
        {"ENCRYPTION",
         "",
         "YES",
         "varchar",
         "0",
         "1",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(1)"},
        {"STATE",
         "",
         "YES",
         "varchar",
         "3",
         "10",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(10)"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_metrics_columns[] = {
        {"NAME",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
        {"SUBSYSTEM",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
        {"COUNT", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint"},
        {"MAX_COUNT", "", "YES", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint"},
        {"MIN_COUNT", "", "YES", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint"},
        {"AVG_COUNT", "", "YES", "float", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "float(12,0)"},
        {"COUNT_RESET", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint"},
        {"MAX_COUNT_RESET", "", "YES", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint"
        },
        {"MIN_COUNT_RESET", "", "YES", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint"
        },
        {"AVG_COUNT_RESET",
         "",
         "YES",
         "float",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "float(12,0)"},
        {"TIME_ENABLED", "", "YES", "datetime", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "datetime"
        },
        {"TIME_DISABLED",
         "",
         "YES",
         "datetime",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "datetime"},
        {"TIME_ELAPSED", "", "YES", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint"},
        {"TIME_RESET", "", "YES", "datetime", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "datetime"},
        {"STATUS",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
        {"TYPE",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
        {"COMMENT",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_session_temp_tablespaces_columns[] = {
        {"ID", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"},
        {"SPACE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"},
        {"PATH",
         "",
         "NO",
         "varchar",
         "1333",
         "4001",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(4001)"},
        {"SIZE", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"},
        {"STATE",
         "",
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(192)"},
        {"PURPOSE",
         "",
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(192)"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_virtual_columns[] = {
        {"TABLE_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"POS", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"},
        {"BASE_POS", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_trx_columns[] = {
        {"trx_id", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"},
        {"trx_state",
         "",
         "NO",
         "varchar",
         "4",
         "13",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(13)"},
        {"trx_started", "", "NO", "datetime", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "datetime"},
        {"trx_requested_lock_id",
         "",
         "YES",
         "varchar",
         "42",
         "126",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(126)"},
        {"trx_wait_started",
         "",
         "YES",
         "datetime",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "datetime"},
        {"trx_weight",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"trx_mysql_thread_id",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"trx_query",
         "",
         "YES",
         "varchar",
         "341",
         "1024",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(1024)"},
        {"trx_operation_state",
         "",
         "YES",
         "varchar",
         "21",
         "64",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(64)"},
        {"trx_tables_in_use",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"trx_tables_locked",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"trx_lock_structs",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"trx_lock_memory_bytes",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"trx_rows_locked",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"trx_rows_modified",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"trx_concurrency_tickets",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"trx_isolation_level",
         "",
         "NO",
         "varchar",
         "5",
         "16",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(16)"},
        {"trx_unique_checks", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"trx_foreign_key_checks", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"
        },
        {"trx_last_foreign_key_error",
         "",
         "YES",
         "varchar",
         "85",
         "256",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(256)"},
        {"trx_adaptive_hash_latched",
         "",
         "NO",
         "int",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "int"},
        {"trx_adaptive_hash_timeout",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"trx_is_read_only", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"trx_autocommit_non_locking",
         "",
         "NO",
         "int",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "int"},
        {"trx_schedule_weight",
         "",
         "YES",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_buffer_page_columns[] = {
        {"POOL_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"BLOCK_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"SPACE", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"},
        {"PAGE_NUMBER",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PAGE_TYPE",
         "",
         "YES",
         "varchar",
         "21",
         "64",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(64)"},
        {"FLUSH_TYPE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"FIX_COUNT",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"IS_HASHED",
         "",
         "YES",
         "varchar",
         "1",
         "3",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(3)"},
        {"NEWEST_MODIFICATION",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"OLDEST_MODIFICATION",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"ACCESS_TIME",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"TABLE_NAME",
         "",
         "YES",
         "varchar",
         "341",
         "1024",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(1024)"},
        {"INDEX_NAME",
         "",
         "YES",
         "varchar",
         "341",
         "1024",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(1024)"},
        {"NUMBER_RECORDS",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"DATA_SIZE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"COMPRESSED_SIZE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PAGE_STATE",
         "",
         "YES",
         "varchar",
         "21",
         "64",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(64)"},
        {"IO_FIX",
         "",
         "YES",
         "varchar",
         "21",
         "64",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(64)"},
        {"IS_OLD",
         "",
         "YES",
         "varchar",
         "1",
         "3",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(3)"},
        {"FREE_PAGE_CLOCK",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"IS_STALE",
         "",
         "YES",
         "varchar",
         "1",
         "3",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(3)"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_buffer_page_lru_columns[] = {
        {"POOL_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"LRU_POSITION",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"SPACE", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"},
        {"PAGE_NUMBER",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PAGE_TYPE",
         "",
         "YES",
         "varchar",
         "21",
         "64",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(64)"},
        {"FLUSH_TYPE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"FIX_COUNT",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"IS_HASHED",
         "",
         "YES",
         "varchar",
         "1",
         "3",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(3)"},
        {"NEWEST_MODIFICATION",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"OLDEST_MODIFICATION",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"ACCESS_TIME",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"TABLE_NAME",
         "",
         "YES",
         "varchar",
         "341",
         "1024",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(1024)"},
        {"INDEX_NAME",
         "",
         "YES",
         "varchar",
         "341",
         "1024",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(1024)"},
        {"NUMBER_RECORDS",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"DATA_SIZE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"COMPRESSED_SIZE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"COMPRESSED",
         "",
         "YES",
         "varchar",
         "1",
         "3",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(3)"},
        {"IO_FIX",
         "",
         "YES",
         "varchar",
         "21",
         "64",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(64)"},
        {"IS_OLD",
         "",
         "YES",
         "varchar",
         "1",
         "3",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(3)"},
        {"FREE_PAGE_CLOCK",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_buffer_pool_stats_columns[] = {
        {"POOL_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"POOL_SIZE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"FREE_BUFFERS",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"DATABASE_PAGES",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"OLD_DATABASE_PAGES",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"MODIFIED_DATABASE_PAGES",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PENDING_DECOMPRESS",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PENDING_READS",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PENDING_FLUSH_LRU",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PENDING_FLUSH_LIST",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PAGES_MADE_YOUNG",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PAGES_NOT_MADE_YOUNG",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PAGES_MADE_YOUNG_RATE",
         "",
         "NO",
         "float",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "float(12,0)"},
        {"PAGES_MADE_NOT_YOUNG_RATE",
         "",
         "NO",
         "float",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "float(12,0)"},
        {"NUMBER_PAGES_READ",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"NUMBER_PAGES_CREATED",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"NUMBER_PAGES_WRITTEN",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"PAGES_READ_RATE",
         "",
         "NO",
         "float",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "float(12,0)"},
        {"PAGES_CREATE_RATE",
         "",
         "NO",
         "float",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "float(12,0)"},
        {"PAGES_WRITTEN_RATE",
         "",
         "NO",
         "float",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "float(12,0)"},
        {"NUMBER_PAGES_GET",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"HIT_RATE", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"YOUNG_MAKE_PER_THOUSAND_GETS",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"NOT_YOUNG_MAKE_PER_THOUSAND_GETS",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"NUMBER_PAGES_READ_AHEAD",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"NUMBER_READ_AHEAD_EVICTED",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"READ_AHEAD_RATE",
         "",
         "NO",
         "float",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "float(12,0)"},
        {"READ_AHEAD_EVICTED_RATE",
         "",
         "NO",
         "float",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "float(12,0)"},
        {"LRU_IO_TOTAL",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"LRU_IO_CURRENT",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"UNCOMPRESS_TOTAL",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"UNCOMPRESS_CURRENT",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_cached_indexes_columns[] = {
        {"SPACE_ID", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"},
        {"INDEX_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"N_CACHED_PAGES",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_fields_columns[] = {
        {"INDEX_ID",
         NULL,
         "YES",
         "varbinary",
         "256",
         "256",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "varbinary(256)"},
        {"NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_tolower_ci",
         "varchar(64)"},
        {"POS", "0", "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_foreign_columns[] = {
        {"ID",
         NULL,
         "YES",
         "varchar",
         "129",
         "387",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(129)"},
        {"FOR_NAME",
         NULL,
         "YES",
         "varchar",
         "129",
         "387",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(129)"},
        {"REF_NAME",
         NULL,
         "YES",
         "varchar",
         "129",
         "387",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(129)"},
        {"N_COLS", "0", "NO", "bigint", NULL, NULL, "19", "0", NULL, NULL, NULL, "bigint"},
        {"TYPE", "0", "NO", "bigint", NULL, NULL, "20", "0", NULL, NULL, NULL, "bigint unsigned"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_foreign_cols_columns[] = {
        {"ID",
         NULL,
         "YES",
         "varchar",
         "129",
         "387",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(129)"},
        {"FOR_COL_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_tolower_ci",
         "varchar(64)"},
        {"REF_COL_NAME",
         NULL,
         "NO",
         "varchar",
         "64",
         "192",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_tolower_ci",
         "varchar(64)"},
        {"POS", NULL, "NO", "int", NULL, NULL, "10", "0", NULL, NULL, NULL, "int unsigned"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_columns_columns[] = {
        {"TABLE_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"NAME",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
        {"POS", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"},
        {"MTYPE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"PRTYPE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"LEN", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"HAS_DEFAULT", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"DEFAULT_VALUE",
         "",
         "YES",
         "text",
         "65535",
         "65535",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "text"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_indexes_columns[] = {
        {"INDEX_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"NAME",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
        {"TABLE_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"TYPE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"N_FIELDS", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"PAGE_NO", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"SPACE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"MERGE_THRESHOLD", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_tables_columns[] = {
        {"TABLE_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"NAME",
         "",
         "NO",
         "varchar",
         "218",
         "655",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(655)"},
        {"FLAG", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"N_COLS", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"SPACE", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint"},
        {"ROW_FORMAT",
         "",
         "YES",
         "varchar",
         "4",
         "12",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(12)"},
        {"ZIP_PAGE_SIZE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"
        },
        {"SPACE_TYPE",
         "",
         "YES",
         "varchar",
         "3",
         "10",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(10)"},
        {"INSTANT_COLS", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
        {"TOTAL_ROW_VERSIONS", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_tablestats_columns[] = {
        {"TABLE_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"NAME",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
        {"STATS_INITIALIZED",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
        {"NUM_ROWS", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"CLUST_INDEX_SIZE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"OTHER_INDEX_SIZE",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"MODIFIED_COUNTER",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"AUTOINC", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"REF_COUNT", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_tablespaces_brief_columns[] = {
        {"SPACE",
         NULL,
         "YES",
         "varbinary",
         "256",
         "256",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "varbinary(256)"},
        {"NAME",
         NULL,
         "NO",
         "varchar",
         "268",
         "804",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(268)"},
        {"PATH",
         NULL,
         "NO",
         "varchar",
         "512",
         "1536",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_bin",
         "varchar(512)"},
        {"FLAG",
         NULL,
         "YES",
         "varbinary",
         "256",
         "256",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "varbinary(256)"},
        {"SPACE_TYPE",
         "",
         "NO",
         "varchar",
         "7",
         "21",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(7)"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_ft_default_stopword_columns[] = {
        {"value",
         "",
         "NO",
         "varchar",
         "6",
         "18",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(18)"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_ft_deleted_columns[] = {
        {"DOC_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_ft_config_columns[] = {
        {"KEY",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
        {"VALUE",
         "",
         "NO",
         "varchar",
         "64",
         "193",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(193)"},
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_ft_index_columns[] = {
        {"WORD",
         "",
         "NO",
         "varchar",
         "112",
         "337",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(337)"},
        {"FIRST_DOC_ID",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"LAST_DOC_ID",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"DOC_COUNT",
         "",
         "NO",
         "bigint",
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         NULL,
         "bigint unsigned"},
        {"DOC_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"},
        {"POSITION", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
};

static const struct mylite_execution_catalog_column_definition
    information_schema_innodb_temp_table_info_columns[] = {
        {"TABLE_ID", "", "NO", "bigint", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "bigint unsigned"
        },
        {"NAME",
         "",
         "YES",
         "varchar",
         "21",
         "64",
         NULL,
         NULL,
         NULL,
         "utf8mb3",
         "utf8mb3_general_ci",
         "varchar(64)"},
        {"N_COLS", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"},
        {"SPACE", "", "NO", "int", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "int unsigned"},
};

static const struct mylite_execution_catalog_table_definition
    information_schema_innodb_table_definitions[] = {
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_CMP,
         "INNODB_CMP",
         information_schema_innodb_cmp_columns,
         sizeof(information_schema_innodb_cmp_columns) /
             sizeof(information_schema_innodb_cmp_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_CMP_RESET,
         "INNODB_CMP_RESET",
         information_schema_innodb_cmp_columns,
         sizeof(information_schema_innodb_cmp_columns) /
             sizeof(information_schema_innodb_cmp_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_CMPMEM,
         "INNODB_CMPMEM",
         information_schema_innodb_cmpmem_columns,
         sizeof(information_schema_innodb_cmpmem_columns) /
             sizeof(information_schema_innodb_cmpmem_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_CMPMEM_RESET,
         "INNODB_CMPMEM_RESET",
         information_schema_innodb_cmpmem_columns,
         sizeof(information_schema_innodb_cmpmem_columns) /
             sizeof(information_schema_innodb_cmpmem_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_CMP_PER_INDEX,
         "INNODB_CMP_PER_INDEX",
         information_schema_innodb_cmp_per_index_columns,
         sizeof(information_schema_innodb_cmp_per_index_columns) /
             sizeof(information_schema_innodb_cmp_per_index_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_CMP_PER_INDEX_RESET,
         "INNODB_CMP_PER_INDEX_RESET",
         information_schema_innodb_cmp_per_index_columns,
         sizeof(information_schema_innodb_cmp_per_index_columns) /
             sizeof(information_schema_innodb_cmp_per_index_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_DATAFILES,
         "INNODB_DATAFILES",
         information_schema_innodb_datafiles_columns,
         sizeof(information_schema_innodb_datafiles_columns) /
             sizeof(information_schema_innodb_datafiles_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_TABLESPACES,
         "INNODB_TABLESPACES",
         information_schema_innodb_tablespaces_columns,
         sizeof(information_schema_innodb_tablespaces_columns) /
             sizeof(information_schema_innodb_tablespaces_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_FIELDS,
         "INNODB_FIELDS",
         information_schema_innodb_fields_columns,
         sizeof(information_schema_innodb_fields_columns) /
             sizeof(information_schema_innodb_fields_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_FOREIGN,
         "INNODB_FOREIGN",
         information_schema_innodb_foreign_columns,
         sizeof(information_schema_innodb_foreign_columns) /
             sizeof(information_schema_innodb_foreign_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_FOREIGN_COLS,
         "INNODB_FOREIGN_COLS",
         information_schema_innodb_foreign_cols_columns,
         sizeof(information_schema_innodb_foreign_cols_columns) /
             sizeof(information_schema_innodb_foreign_cols_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_COLUMNS,
         "INNODB_COLUMNS",
         information_schema_innodb_columns_columns,
         sizeof(information_schema_innodb_columns_columns) /
             sizeof(information_schema_innodb_columns_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_INDEXES,
         "INNODB_INDEXES",
         information_schema_innodb_indexes_columns,
         sizeof(information_schema_innodb_indexes_columns) /
             sizeof(information_schema_innodb_indexes_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_TABLES,
         "INNODB_TABLES",
         information_schema_innodb_tables_columns,
         sizeof(information_schema_innodb_tables_columns) /
             sizeof(information_schema_innodb_tables_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_TABLESTATS,
         "INNODB_TABLESTATS",
         information_schema_innodb_tablestats_columns,
         sizeof(information_schema_innodb_tablestats_columns) /
             sizeof(information_schema_innodb_tablestats_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_METRICS,
         "INNODB_METRICS",
         information_schema_innodb_metrics_columns,
         sizeof(information_schema_innodb_metrics_columns) /
             sizeof(information_schema_innodb_metrics_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_SESSION_TEMP_TABLESPACES,
         "INNODB_SESSION_TEMP_TABLESPACES",
         information_schema_innodb_session_temp_tablespaces_columns,
         sizeof(information_schema_innodb_session_temp_tablespaces_columns) /
             sizeof(information_schema_innodb_session_temp_tablespaces_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_VIRTUAL,
         "INNODB_VIRTUAL",
         information_schema_innodb_virtual_columns,
         sizeof(information_schema_innodb_virtual_columns) /
             sizeof(information_schema_innodb_virtual_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_TRX,
         "INNODB_TRX",
         information_schema_innodb_trx_columns,
         sizeof(information_schema_innodb_trx_columns) /
             sizeof(information_schema_innodb_trx_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_BUFFER_PAGE,
         "INNODB_BUFFER_PAGE",
         information_schema_innodb_buffer_page_columns,
         sizeof(information_schema_innodb_buffer_page_columns) /
             sizeof(information_schema_innodb_buffer_page_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_BUFFER_PAGE_LRU,
         "INNODB_BUFFER_PAGE_LRU",
         information_schema_innodb_buffer_page_lru_columns,
         sizeof(information_schema_innodb_buffer_page_lru_columns) /
             sizeof(information_schema_innodb_buffer_page_lru_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_BUFFER_POOL_STATS,
         "INNODB_BUFFER_POOL_STATS",
         information_schema_innodb_buffer_pool_stats_columns,
         sizeof(information_schema_innodb_buffer_pool_stats_columns) /
             sizeof(information_schema_innodb_buffer_pool_stats_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_CACHED_INDEXES,
         "INNODB_CACHED_INDEXES",
         information_schema_innodb_cached_indexes_columns,
         sizeof(information_schema_innodb_cached_indexes_columns) /
             sizeof(information_schema_innodb_cached_indexes_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_TABLESPACES_BRIEF,
         "INNODB_TABLESPACES_BRIEF",
         information_schema_innodb_tablespaces_brief_columns,
         sizeof(information_schema_innodb_tablespaces_brief_columns) /
             sizeof(information_schema_innodb_tablespaces_brief_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_FT_DEFAULT_STOPWORD,
         "INNODB_FT_DEFAULT_STOPWORD",
         information_schema_innodb_ft_default_stopword_columns,
         sizeof(information_schema_innodb_ft_default_stopword_columns) /
             sizeof(information_schema_innodb_ft_default_stopword_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_FT_CONFIG,
         "INNODB_FT_CONFIG",
         information_schema_innodb_ft_config_columns,
         sizeof(information_schema_innodb_ft_config_columns) /
             sizeof(information_schema_innodb_ft_config_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_FT_BEING_DELETED,
         "INNODB_FT_BEING_DELETED",
         information_schema_innodb_ft_deleted_columns,
         sizeof(information_schema_innodb_ft_deleted_columns) /
             sizeof(information_schema_innodb_ft_deleted_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_FT_DELETED,
         "INNODB_FT_DELETED",
         information_schema_innodb_ft_deleted_columns,
         sizeof(information_schema_innodb_ft_deleted_columns) /
             sizeof(information_schema_innodb_ft_deleted_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_FT_INDEX_CACHE,
         "INNODB_FT_INDEX_CACHE",
         information_schema_innodb_ft_index_columns,
         sizeof(information_schema_innodb_ft_index_columns) /
             sizeof(information_schema_innodb_ft_index_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_FT_INDEX_TABLE,
         "INNODB_FT_INDEX_TABLE",
         information_schema_innodb_ft_index_columns,
         sizeof(information_schema_innodb_ft_index_columns) /
             sizeof(information_schema_innodb_ft_index_columns[0])},
        {MYLITE_EXECUTION_CATALOG_TABLE_INNODB_TEMP_TABLE_INFO,
         "INNODB_TEMP_TABLE_INFO",
         information_schema_innodb_temp_table_info_columns,
         sizeof(information_schema_innodb_temp_table_info_columns) /
             sizeof(information_schema_innodb_temp_table_info_columns[0])},
};

size_t mylite_execution_catalog_information_schema_innodb_table_definition_count(void) {
    return sizeof(information_schema_innodb_table_definitions) /
           sizeof(information_schema_innodb_table_definitions[0]);
}

const struct mylite_execution_catalog_table_definition *mylite_execution_catalog_information_schema_innodb_table_definition_at(
    size_t index
) {
    if (index >= mylite_execution_catalog_information_schema_innodb_table_definition_count()) {
        return NULL;
    }
    return &information_schema_innodb_table_definitions[index];
}
