#!/usr/bin/env python3
import argparse
import subprocess


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--exe", default="build/mylite-parse")
    args = parser.parse_args()

    cases = [
        ("select 1;", 0, {"statements": "1", "select": "1"}),
        ("select ;", 1, {}),
        ("select from t;", 1, {}),
        ("select select;", 1, {}),
        ("select all;", 1, {}),
        ("select distinct;", 1, {}),
        ("select * from t;", 0, {"statements": "1", "select": "1"}),
        ("select charset(a) from t;", 0, {"statements": "1", "select": "1"}),
        ("select account from account.account where account = 'account';", 0, {"statements": "1", "select": "1"}),
        ("select distinct a from t;", 0, {"statements": "1", "select": "1"}),
        ("select distinct * from t;", 0, {"statements": "1", "select": "1"}),
        ("nonsense 1;", 1, {}),
        ("/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;", 0, {"utility": "1"}),
        (
            "create procedure p() begin select 1; select 2; end;",
            0,
            {"statements": "1", "ddl": "1"},
        ),
        ("create table t (a int);", 0, {"statements": "1", "ddl": "1"}),
        ("create temporary table t (a int);", 0, {"statements": "1", "ddl": "1"}),
        ("create database if not exists db1 default character set utf8mb4;", 0, {"statements": "1", "ddl": "1"}),
        ("create database db2 charset=utf8mb4;", 0, {"statements": "1", "ddl": "1"}),
        ("create database db3 encryption='Y';", 0, {"statements": "1", "ddl": "1"}),
        ("create database db4 default charset utf8mb4 default collate utf8mb4_0900_ai_ci default encryption='N';", 0, {"statements": "1", "ddl": "1"}),
        ("create schema tables collate binary;", 0, {"statements": "1", "ddl": "1"}),
        ("create unique index idx on t (a);", 0, {"statements": "1", "ddl": "1"}),
        ("create resource group rg type=user;", 0, {"statements": "1", "ddl": "1"}),
        ("create resource group rgp type=system vcpu=0-3,9-10 thread_priority=-20 disable;", 0, {"statements": "1", "ddl": "1"}),
        ("create server s foreign data wrapper mysql options (database 'test');", 0, {"statements": "1", "ddl": "1"}),
        ("create server 'srv' foreign data wrapper 'mysql' options (host 'localhost', database 'test');", 0, {"statements": "1", "ddl": "1"}),
        ("create tablespace ts engine innodb;", 0, {"statements": "1", "ddl": "1"}),
        ("create tablespace ts add datafile 'ts.ibd' engine innodb;", 0, {"statements": "1", "ddl": "1"}),
        ("create tablespace ts engine_attribute='{}';", 0, {"statements": "1", "ddl": "1"}),
        ("create tablespace ts file_block_size=8192;", 0, {"statements": "1", "ddl": "1"}),
        ("create tablespace ts encryption='Y';", 0, {"statements": "1", "ddl": "1"}),
        ("create undo tablespace u add datafile 'u.ibu' engine innodb;", 0, {"statements": "1", "ddl": "1"}),
        ("create logfile group lg add undofile 'u.dat' engine ndb;", 0, {"statements": "1", "ddl": "1"}),
        ("create spatial reference system 4120 name 'x' organization 'EPSG' identified by 4120 definition 'x';", 0, {"statements": "1", "ddl": "1"}),
        ("create spatial reference system if not exists 4120 name 'x' definition 'x';", 0, {"statements": "1", "ddl": "1"}),
        ("create or replace spatial reference system 4120 name 'x' definition 'x';", 0, {"statements": "1", "ddl": "1"}),
        ("create spatial reference system 4121 description 'demo';", 0, {"statements": "1", "ddl": "1"}),
        ("create index idx using btree on t (a);", 0, {"statements": "1", "ddl": "1"}),
        ("create index type type btree on t (a);", 0, {"statements": "1", "ddl": "1"}),
        ("create unique index idx on db1.t (a);", 0, {"statements": "1", "ddl": "1"}),
        ("create index idx2 on t ((a + b), c(5) desc) key_block_size=8 using hash with parser ngram comment 'x' invisible algorithm=inplace lock=none;", 0, {"statements": "1", "ddl": "1"}),
        ("create index idx3 on t (a) engine_attribute='{}' secondary_engine_attribute='{}' visible;", 0, {"statements": "1", "ddl": "1"}),
        ("create index idx4 on t (a) type btree;", 0, {"statements": "1", "ddl": "1"}),
        ("create role if not exists role, role@host.name;", 0, {"statements": "1", "ddl": "1"}),
        ("create user if not exists user@localhost identified by 'pw';", 0, {"statements": "1", "ddl": "1"}),
        ("create user 'u1'@'localhost', u2@host account lock;", 0, {"statements": "1", "ddl": "1"}),
        ("create user u1 identified by random password, u2 identified with mysql_native_password by 'pw' require ssl;", 0, {"statements": "1", "ddl": "1"}),
        ("create user u3 default role r1, r2 require cipher 'c' and issuer 'i' subject 's' with max_queries_per_hour 2 max_user_connections 3 password expire interval 4 day account unlock comment 'x';", 0, {"statements": "1", "ddl": "1"}),
        ("create user u4 password history default password reuse interval 1 day password require current optional failed_login_attempts 2 password_lock_time unbounded attribute '{}';", 0, {"statements": "1", "ddl": "1"}),
        ("create user u5 identified by 'pw' and identified by random password;", 0, {"statements": "1", "ddl": "1"}),
        ("create user u6 identified with mysql_native_password and identified with authentication_ldap_sasl as 'x';", 0, {"statements": "1", "ddl": "1"}),
        ("create user u7 identified with authentication_webauthn initial authentication identified by random password;", 0, {"statements": "1", "ddl": "1"}),
        ("create user u8 identified with authentication_webauthn initial authentication identified with mysql_native_password as 'x';", 0, {"statements": "1", "ddl": "1"}),
        ("create resource group rg2 type=system disable;", 0, {"statements": "1", "ddl": "1"}),
        ("create event if not exists db1.e1 on schedule every 1 second do select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create event e2 on schedule at current_timestamp on completion not preserve do begin end;", 0, {"statements": "1", "ddl": "1"}),
        ("create event e3 on schedule every 1 year on completion preserve disable on replica comment 'yearly' do select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create event e4 on schedule at current_timestamp + interval 1 hour enable do begin end;", 0, {"statements": "1", "ddl": "1"}),
        ("create trigger if not exists db1.tr1 before insert on t for each row set @a = 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create trigger tr_order before insert on t for each row follows tr0 begin end;", 0, {"statements": "1", "ddl": "1"}),
        ("create trigger tr_after after update on t for each row precedes tr0 set @a = 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create function if not exists db1.f1() returns int return 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create function f2() returns int deterministic reads sql data return 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create function udf1 returns integer soname 'x.so';", 0, {"statements": "1", "ddl": "1"}),
        ("create procedure if not exists p1() select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create procedure p_det() deterministic reads sql data select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create aggregate function agg returns int soname 'x.so';", 0, {"statements": "1", "ddl": "1"}),
        ("create aggregate function agg2 returns decimal soname 'x.so';", 0, {"statements": "1", "ddl": "1"}),
        ("create view db1.v1 as select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create view db1.v2 (a, b) as select 1, 2;", 0, {"statements": "1", "ddl": "1"}),
        ("create view db1.v3 as table t1 limit 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create view db1.v4 as values row(1);", 0, {"statements": "1", "ddl": "1"}),
        ("create view db1.v5 as with cte as (select 1) select * from cte;", 0, {"statements": "1", "ddl": "1"}),
        ("create view db1.v6 as (select 1);", 0, {"statements": "1", "ddl": "1"}),
        ("create or replace view v1 as select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create or replace algorithm=merge definer=u@localhost sql security invoker view v2 as select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create definer=current_user() event e1 on schedule every 1 day do select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create definer=u@localhost procedure p2() select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create definer=u@localhost function f2() returns int return 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create definer=u@localhost trigger tr2 before insert on t for each row set @a=1;", 0, {"statements": "1", "ddl": "1"}),
        ("create table if not exists db1.t1 (a int);", 0, {"statements": "1", "ddl": "1"}),
        ("create table t_like like t1;", 0, {"statements": "1", "ddl": "1"}),
        ("create table t3 engine=innodb as select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create table t4 select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create table t5 table t1 limit 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create table t6 values row(1);", 0, {"statements": "1", "ddl": "1"}),
        ("create table t7 with cte as (select 1) select * from cte;", 0, {"statements": "1", "ddl": "1"}),
        ("create table t8 as select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create table t9 as (select 1);", 0, {"statements": "1", "ddl": "1"}),
        ("create table t_opts auto_increment=10 max_rows=100 select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("create table t10 as ((values row(1) order by column_0 limit 1) order by column_0 limit 1);", 0, {"statements": "1", "ddl": "1"}),
        ("create temporary table if not exists t2 select * from t1;", 0, {"statements": "1", "ddl": "1"}),
        ("create temporary;", 1, {}),
        ("create table;", 1, {}),
        ("create table t1;", 1, {}),
        ("create table t1 bogus;", 1, {}),
        ("create table t1 select;", 1, {}),
        ("create table t1 as garbage;", 1, {}),
        ("create database;", 1, {}),
        ("create database db1 garbage;", 1, {}),
        ("create database db1 read only=1;", 1, {}),
        ("create database db1 default;", 1, {}),
        ("create schema if exists s;", 1, {}),
        ("create unique table t (a int);", 1, {}),
        ("create resource;", 1, {}),
        ("create resource rg type=user;", 1, {}),
        ("create resource group rg;", 1, {}),
        ("create resource group rg invalid=user;", 1, {}),
        ("create resource group rg type=user force;", 1, {}),
        ("create server;", 1, {}),
        ("create server s;", 1, {}),
        ("create server s data wrapper mysql options (database 'test');", 1, {}),
        ("create tablespace;", 1, {}),
        ("create tablespace ts garbage;", 1, {}),
        ("create undo tablespace u;", 1, {}),
        ("create index idx;", 1, {}),
        ("create index idx on;", 1, {}),
        ("create index idx on t;", 1, {}),
        ("create role if exists role;", 1, {}),
        ("create role;", 1, {}),
        ("create user;", 1, {}),
        ("create user if exists user@localhost;", 1, {}),
        ("create user u,;", 1, {}),
        ("create user u identified;", 1, {}),
        ("create user u identified by 'pw' and;", 1, {}),
        ("create user u identified with authentication_webauthn initial identified by 'pw';", 1, {}),
        ("create user u require;", 1, {}),
        ("create user u with max_queries_per_hour;", 1, {}),
        ("create user u password expire interval 4;", 1, {}),
        ("create user u account;", 1, {}),
        ("create user u \"extra\";", 1, {}),
        ("create index idx on t (a) algorithm;", 1, {}),
        ("create index idx on t (a) lock bogus;", 1, {}),
        ("create index idx on t (a) with parser;", 1, {}),
        ("create logfile group lg;", 1, {}),
        ("create logfile group lg add datafile 'u.dat';", 1, {}),
        ("create event if not exists;", 1, {}),
        ("create event e1 every 1 second do select 1;", 1, {}),
        ("create event e1 on schedule later do select 1;", 1, {}),
        ("create event e1 on schedule every 1 second select 1;", 1, {}),
        ("create event e1 on schedule every 1 second;", 1, {}),
        ("create event e1 on schedule every 1 second rename to e2 do select 1;", 1, {}),
        ("create event e1 on schedule every 1 second disable on source do select 1;", 1, {}),
        ("create trigger tr1;", 1, {}),
        ("create trigger tr1 before insert on t set @a=1;", 1, {}),
        ("create trigger tr1 before insert on t for each row garbage;", 1, {}),
        ("create function;", 1, {}),
        ("create function f returns int return 1;", 1, {}),
        ("create function f() returns int garbage;", 1, {}),
        ("create procedure if not exists;", 1, {}),
        ("create procedure p() garbage;", 1, {}),
        ("create aggregate function agg;", 1, {}),
        ("create aggregate function agg returns blob soname 'x.so';", 1, {}),
        ("create view;", 1, {}),
        ("create view v1;", 1, {}),
        ("create view v1 as select;", 1, {}),
        ("create view v1 as ();", 1, {}),
        ("create view v1 select 1;", 1, {}),
        ("create view v1 as garbage;", 1, {}),
        ("create or view v1 as select 1;", 1, {}),
        ("create algorithm view v1 as select 1;", 1, {}),
        ("create sql security view v1 as select 1;", 1, {}),
        ("create definer=u;", 1, {}),
        ("create definer=u table t (a int);", 1, {}),
        ("create undo;", 1, {}),
        ("create spatial reference system 4120;", 1, {}),
        ("create or replace spatial reference system if not exists 4120 name 'x' definition 'x';", 1, {}),
        ("create spatial reference system 4120 bogus 'x';", 1, {}),
        ("create nonsense;", 1, {}),
        ("drop table if exists t;", 0, {"statements": "1", "ddl": "1"}),
        ("drop table if exists db1.t1, t2;", 0, {"statements": "1", "ddl": "1"}),
        ("drop table variables;", 0, {"statements": "1", "ddl": "1"}),
        ("drop table full;", 0, {"statements": "1", "ddl": "1"}),
        ("drop temporary table if exists t;", 0, {"statements": "1", "ddl": "1"}),
        ("drop temporary tables if exists t1, t2;", 0, {"statements": "1", "ddl": "1"}),
        ("drop view if exists v1, db1.v2 restrict;", 0, {"statements": "1", "ddl": "1"}),
        ("drop view v2 cascade;", 0, {"statements": "1", "ddl": "1"}),
        ("drop user if exists u1@localhost, 'u2'@'127.0.0.1';", 0, {"statements": "1", "ddl": "1"}),
        ("drop user user@localhost;", 0, {"statements": "1", "ddl": "1"}),
        ("drop user u1@;", 0, {"statements": "1", "ddl": "1"}),
        ("drop user current_user();", 0, {"statements": "1", "ddl": "1"}),
        ("drop role if exists role, role@host.name;", 0, {"statements": "1", "ddl": "1"}),
        ("drop prepare stmt;", 0, {"statements": "1", "ddl": "1"}),
        ("drop index i on t;", 0, {"statements": "1", "ddl": "1"}),
        ("drop index i on t algorithm=default lock=none;", 0, {"statements": "1", "ddl": "1"}),
        ("drop index i on t algorithm inplace lock shared;", 0, {"statements": "1", "ddl": "1"}),
        ("drop database if exists db1;", 0, {"statements": "1", "ddl": "1"}),
        ("drop database first;", 0, {"statements": "1", "ddl": "1"}),
        ("drop schema db1;", 0, {"statements": "1", "ddl": "1"}),
        ("drop function if exists db1.f1;", 0, {"statements": "1", "ddl": "1"}),
        ("drop function if exists test.database;", 0, {"statements": "1", "ddl": "1"}),
        ("drop procedure count;", 0, {"statements": "1", "ddl": "1"}),
        ("drop event if exists db1.e1;", 0, {"statements": "1", "ddl": "1"}),
        ("drop trigger if exists db1.tr1;", 0, {"statements": "1", "ddl": "1"}),
        ("drop resource group rg;", 0, {"statements": "1", "ddl": "1"}),
        ("drop resource group rg force;", 0, {"statements": "1", "ddl": "1"}),
        ("drop logfile group lg engine ndb;", 0, {"statements": "1", "ddl": "1"}),
        ("drop spatial reference system 4120;", 0, {"statements": "1", "ddl": "1"}),
        ("drop spatial reference system if exists 4120;", 0, {"statements": "1", "ddl": "1"}),
        ("drop server if exists s1;", 0, {"statements": "1", "ddl": "1"}),
        ("drop tablespace ts engine innodb;", 0, {"statements": "1", "ddl": "1"}),
        ("drop undo tablespace u engine innodb;", 0, {"statements": "1", "ddl": "1"}),
        ("drop prepare stmt extra;", 1, {}),
        ("drop index i;", 1, {}),
        ("drop index i on;", 1, {}),
        ("drop index i on select;", 1, {}),
        ("drop index i on t algorithm;", 1, {}),
        ("drop index i on t lock bogus;", 1, {}),
        ("drop index i on t algorithm=instant;", 1, {}),
        ("drop database;", 1, {}),
        ("drop database db1 extra;", 1, {}),
        ("drop function if exists;", 1, {}),
        ("drop procedure p extra;", 1, {}),
        ("drop event if exists;", 1, {}),
        ("drop trigger tr extra;", 1, {}),
        ("drop table if exists;", 1, {}),
        ("drop table t1 t2;", 1, {}),
        ("drop temporary table;", 1, {}),
        ("drop view if exists;", 1, {}),
        ("drop user;", 1, {}),
        ("drop role current_user();", 1, {}),
        ("drop user u1 u2;", 1, {}),
        ("drop role if exists;", 1, {}),
        ("drop temporary;", 1, {}),
        ("drop resource;", 1, {}),
        ("drop resource group rg invalid;", 1, {}),
        ("drop logfile group;", 1, {}),
        ("drop spatial reference;", 1, {}),
        ("drop server;", 1, {}),
        ("drop tablespace;", 1, {}),
        ("drop undo;", 1, {}),
        ("drop nonsense;", 1, {}),
        ("alter table t add column a int;", 0, {"statements": "1", "ddl": "1"}),
        ("alter algorithm=merge view v as select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("alter logfile group lg add undofile 'u2.dat' engine ndb;", 0, {"statements": "1", "ddl": "1"}),
        ("alter undo tablespace u set active engine innodb;", 0, {"statements": "1", "ddl": "1"}),
        ("alter resource group rg vcpu=1;", 0, {"statements": "1", "ddl": "1"}),
        ("alter resource group rg vcpu 0 - 3,9-10 thread_priority = -5 disable force;", 0, {"statements": "1", "ddl": "1"}),
        ("alter resource group rg disable force;", 0, {"statements": "1", "ddl": "1"}),
        ("alter resource group rg thread_priority=10;", 0, {"statements": "1", "ddl": "1"}),
        ("alter server s options (user 'sally');", 0, {"statements": "1", "ddl": "1"}),
        ("alter server s options (host '127.0.0.1', database 'test');", 0, {"statements": "1", "ddl": "1"}),
        ("alter tablespace ts rename to ts2;", 0, {"statements": "1", "ddl": "1"}),
        ("alter tablespace ts add datafile 'x.dat' engine ndb;", 0, {"statements": "1", "ddl": "1"}),
        ("alter tablespace ts drop datafile 'x.dat' engine ndb;", 0, {"statements": "1", "ddl": "1"}),
        ("alter tablespace ts encryption='N';", 0, {"statements": "1", "ddl": "1"}),
        ("alter undo tablespace u set inactive engine innodb;", 0, {"statements": "1", "ddl": "1"}),
        ("alter view db1.v1 as select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("alter view db1.v2 (a, b) as select 1, 2;", 0, {"statements": "1", "ddl": "1"}),
        ("alter user if exists user@localhost account lock;", 0, {"statements": "1", "ddl": "1"}),
        ("alter user user() identified by 'pw';", 0, {"statements": "1", "ddl": "1"}),
        ("alter user user() identified by random password replace 'old' retain current password;", 0, {"statements": "1", "ddl": "1"}),
        ("alter user user() discard old password;", 0, {"statements": "1", "ddl": "1"}),
        ("alter user current_user() identified by random password replace 'old' retain current password;", 0, {"statements": "1", "ddl": "1"}),
        ("alter user u1 identified by 'pw' replace '', u2 discard old password password require current default;", 0, {"statements": "1", "ddl": "1"}),
        ("alter user u3 default role all require x509 with max_connections_per_hour 4 password_lock_time 6 account unlock attribute '{}';", 0, {"statements": "1", "ddl": "1"}),
        ("alter user u4 add 2 factor identified by 'otp';", 0, {"statements": "1", "ddl": "1"}),
        ("alter user u5 modify 2 factor identified with authentication_webauthn as 'x' modify 3 factor identified by random password;", 0, {"statements": "1", "ddl": "1"}),
        ("alter user u6 drop 2 factor drop 3 factor;", 0, {"statements": "1", "ddl": "1"}),
        ("alter user u7 2 factor initiate registration;", 0, {"statements": "1", "ddl": "1"}),
        ("alter user user() 2 factor finish registration set challenge_response as 'x';", 0, {"statements": "1", "ddl": "1"}),
        ("alter user u8 3 factor unregister;", 0, {"statements": "1", "ddl": "1"}),
        ("alter user user() 3 factor unregister;", 0, {"statements": "1", "ddl": "1"}),
        ("alter event db1.e1 rename to e2;", 0, {"statements": "1", "ddl": "1"}),
        ("alter event db1.e1 on schedule every 1 hour do select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("alter event db1.e1 on completion not preserve;", 0, {"statements": "1", "ddl": "1"}),
        ("alter event db1.e1 on completion preserve;", 0, {"statements": "1", "ddl": "1"}),
        ("alter event db1.e1 do begin end;", 0, {"statements": "1", "ddl": "1"}),
        ("alter event db1.e1 comment 'changed';", 0, {"statements": "1", "ddl": "1"}),
        ("alter event db1.e1 enable;", 0, {"statements": "1", "ddl": "1"}),
        ("alter event db1.e1 disable on replica;", 0, {"statements": "1", "ddl": "1"}),
        ("alter event db1.e1 disable on slave;", 0, {"statements": "1", "ddl": "1"}),
        ("alter event db1.e1 on schedule at current_timestamp + interval 1 hour comment 'changed';", 0, {"statements": "1", "ddl": "1"}),
        ("alter event event2 on schedule every 1 year on completion preserve rename to event3 enable comment \"new comment\" do begin end;", 0, {"statements": "1", "ddl": "1"}),
        ("alter function db1.f1 comment 'changed';", 0, {"statements": "1", "ddl": "1"}),
        ("alter function db1.f1 language sql reads sql data sql security invoker;", 0, {"statements": "1", "ddl": "1"}),
        ("alter function f1 no sql;", 0, {"statements": "1", "ddl": "1"}),
        ("alter procedure p1;", 0, {"statements": "1", "ddl": "1"}),
        ("alter procedure p1 comment 'changed' contains sql sql security definer;", 0, {"statements": "1", "ddl": "1"}),
        ("alter procedure p1 modifies sql data;", 0, {"statements": "1", "ddl": "1"}),
        ("alter database default character set latin2;", 0, {"statements": "1", "ddl": "1"}),
        ("alter database db1 encryption='N';", 0, {"statements": "1", "ddl": "1"}),
        ("alter database db1 collate utf8mb4_0900_ai_ci;", 0, {"statements": "1", "ddl": "1"}),
        ("alter schema s read only default;", 0, {"statements": "1", "ddl": "1"}),
        ("alter database read only=1 default collate utf8mb4_bin;", 0, {"statements": "1", "ddl": "1"}),
        ("alter database db1 default character set = utf8mb4 read only = 0;", 0, {"statements": "1", "ddl": "1"}),
        ("alter instance reload tls;", 0, {"statements": "1", "ddl": "1"}),
        ("alter instance reload tls for channel mysql_main no rollback on error;", 0, {"statements": "1", "ddl": "1"}),
        ("alter instance reload keyring;", 0, {"statements": "1", "ddl": "1"}),
        ("alter instance rotate innodb master key;", 0, {"statements": "1", "ddl": "1"}),
        ("alter instance rotate binlog master key;", 0, {"statements": "1", "ddl": "1"}),
        ("alter instance enable innodb redo_log;", 0, {"statements": "1", "ddl": "1"}),
        ("alter instance disable innodb redo_log;", 0, {"statements": "1", "ddl": "1"}),
        ("alter table db1.t1 add column c int;", 0, {"statements": "1", "ddl": "1"}),
        ("alter table t1;", 0, {"statements": "1", "ddl": "1"}),
        ("alter table t1 force;", 0, {"statements": "1", "ddl": "1"}),
        ("alter table t1 coalesce partition 1;", 0, {"statements": "1", "ddl": "1"}),
        ("alter algorithm=merge view v1 as select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("alter algorithm=temptable definer=u@localhost view v2 as select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("alter definer=u@localhost sql security invoker view v3 as select 1;", 0, {"statements": "1", "ddl": "1"}),
        ("alter definer=u@localhost event e1 on schedule every 1 hour;", 0, {"statements": "1", "ddl": "1"}),
        ("alter table;", 1, {}),
        ("alter table t1 bogus;", 1, {}),
        ("alter logfile group lg;", 1, {}),
        ("alter logfile group lg add datafile 'u2.dat';", 1, {}),
        ("alter undo;", 1, {}),
        ("alter resource;", 1, {}),
        ("alter resource group rg;", 1, {}),
        ("alter resource group rg force;", 1, {}),
        ("alter resource group rg enable force;", 1, {}),
        ("alter resource group rg unknown=1;", 1, {}),
        ("alter server;", 1, {}),
        ("alter server s;", 1, {}),
        ("alter server s wrapper mysql;", 1, {}),
        ("alter tablespace;", 1, {}),
        ("alter tablespace ts;", 1, {}),
        ("alter tablespace ts rename;", 1, {}),
        ("alter undo tablespace u;", 1, {}),
        ("alter undo tablespace u set unknown;", 1, {}),
        ("alter view;", 1, {}),
        ("alter view v1;", 1, {}),
        ("alter view v1 select 1;", 1, {}),
        ("alter user;", 1, {}),
        ("alter user if user@localhost;", 1, {}),
        ("alter user u identified;", 1, {}),
        ("alter user user() identified with mysql_native_password;", 1, {}),
        ("alter user user() account lock;", 1, {}),
        ("alter user u add factor identified by 'otp';", 1, {}),
        ("alter user user() add 2 factor identified by 'otp';", 1, {}),
        ("alter user u 2 initiate registration;", 1, {}),
        ("alter user u 2 factor finish registration challenge_response as 'x';", 1, {}),
        ("alter user u password require optional;", 1, {}),
        ("alter user u discard password;", 1, {}),
        ("alter event;", 1, {}),
        ("alter event e1;", 1, {}),
        ("alter event e1 bogus;", 1, {}),
        ("alter event e1 on schedule later;", 1, {}),
        ("alter event e1 do garbage;", 1, {}),
        ("alter event e1 rename e2;", 1, {}),
        ("alter event e1 comment;", 1, {}),
        ("alter event e1 disable on source;", 1, {}),
        ("alter function;", 1, {}),
        ("alter function f1 deterministic;", 1, {}),
        ("alter procedure p1 comment;", 1, {}),
        ("alter procedure p1 reads data;", 1, {}),
        ("alter procedure p1 sql security;", 1, {}),
        ("alter database;", 1, {}),
        ("alter database db1 garbage;", 1, {}),
        ("alter database db1 read;", 1, {}),
        ("alter database db1 encryption;", 1, {}),
        ("alter schema s;", 1, {}),
        ("alter instance;", 1, {}),
        ("alter instance reload;", 1, {}),
        ("alter instance reload tls rollback on error;", 1, {}),
        ("alter instance reload keyring for channel mysql_main;", 1, {}),
        ("alter instance rotate innodb key;", 1, {}),
        ("alter instance enable innodb;", 1, {}),
        ("alter algorithm view v1 as select 1;", 1, {}),
        ("alter definer=u;", 1, {}),
        ("alter definer=u table t add c int;", 1, {}),
        ("alter nonsense;", 1, {}),
        ("rename table a to b;", 0, {"statements": "1", "ddl": "1"}),
        ("rename tables a to b;", 0, {"statements": "1", "ddl": "1"}),
        ("rename table a to b, db.c to mysql.component;", 0, {"statements": "1", "ddl": "1"}),
        ("rename user a to b;", 0, {"statements": "1", "ddl": "1"}),
        ("rename user master@localhost to root@localhost;", 0, {"statements": "1", "ddl": "1"}),
        ("rename user 'a'@'%' to 'b'@'%', r1 to r2;", 0, {"statements": "1", "ddl": "1"}),
        ("rename user current_user() to u@localhost;", 0, {"statements": "1", "ddl": "1"}),
        ("rename table mysql.user to mysql.user_bak;", 0, {"statements": "1", "ddl": "1"}),
        ("rename table a b;", 1, {}),
        ("rename table a to b, c;", 1, {}),
        ("rename user user() to b;", 1, {}),
        ("rename user a to b, c;", 1, {}),
        ("rename nonsense;", 1, {}),
        ("truncate table t;", 0, {"statements": "1", "ddl": "1"}),
        ("truncate t;", 0, {"statements": "1", "ddl": "1"}),
        ("truncate mysql.general_log;", 0, {"statements": "1", "ddl": "1"}),
        ("truncate table mysql.user;", 0, {"statements": "1", "ddl": "1"}),
        ("truncate t extra;", 1, {}),
        ("truncate select;", 1, {}),
        ("load data infile 'x' into table t;", 0, {"statements": "1", "utility": "1"}),
        ("load data local infile 'x' ignore into table t;", 0, {"statements": "1", "utility": "1"}),
        ("load data concurrent infile 'x' replace into table t;", 0, {"statements": "1", "utility": "1"}),
        ("load xml infile 'x' into table t;", 0, {"statements": "1", "utility": "1"}),
        ("load data infile 'x' into table t ();", 0, {"statements": "1", "utility": "1"}),
        ("load data infile 'x' into table t partition (p0, p1) character set utf8mb4 fields terminated by ',' optionally enclosed by '\"' escaped by '\\\\' lines starting by '>' terminated by '\\n' ignore 1 lines (a, @b) set c=default;", 0, {"statements": "1", "utility": "1"}),
        ("load xml local infile 'x' replace into table db.t character set utf8mb4 rows identified by '<row>' ignore 2 rows (a, @b) set c=1;", 0, {"statements": "1", "utility": "1"}),
        ("load index into cache t;", 0, {"statements": "1", "utility": "1"}),
        ("load index into cache t key (primary), t2 key (b) ignore leaves;", 0, {"statements": "1", "utility": "1"}),
        ("load index into cache t partition (all);", 0, {"statements": "1", "utility": "1"}),
        ("load data;", 1, {}),
        ("load data garbage 'x' into table t;", 1, {}),
        ("load data infile 'x' into table;", 1, {}),
        ("load data infile 'x' into table select;", 1, {}),
        ("load data infile 'x' ignore into table;", 1, {}),
        ("load data infile 'x' into table t fields by ',';", 1, {}),
        ("load data infile 'x' into table t ignore lines;", 1, {}),
        ("load xml infile 'x' into table t partition (p0);", 1, {}),
        ("load index into cache t ignore branches;", 1, {}),
        ("load index into cache t partition all;", 1, {}),
        ("load index t;", 1, {}),
        ("load nonsense;", 1, {}),
        ("start transaction read only;", 0, {"statements": "1", "transaction": "1"}),
        ("start transaction with consistent snapshot, read write;", 0, {"statements": "1", "transaction": "1"}),
        ("set transaction isolation level repeatable read;", 0, {"statements": "1", "utility": "1"}),
        ("set transaction isolation level read committed, read only;", 0, {"statements": "1", "utility": "1"}),
        ("set global transaction isolation level serializable;", 0, {"statements": "1", "utility": "1"}),
        ("set session transaction read write;", 0, {"statements": "1", "utility": "1"}),
        ("set local transaction read only;", 0, {"statements": "1", "utility": "1"}),
        ("set transaction isolation level read uncommitted;", 0, {"statements": "1", "utility": "1"}),
        ("start replica;", 0, {"statements": "1", "transaction": "1"}),
        ("start replica io_thread, sql_thread for channel 'ch1';", 0, {"statements": "1", "transaction": "1"}),
        ("start replica until source_log_file = 'bin.000001', source_log_pos = 4;", 0, {"statements": "1", "transaction": "1"}),
        ("start replica until relay_log_file = 'relay.000001', relay_log_pos = 4;", 0, {"statements": "1", "transaction": "1"}),
        ("start replica until sql_before_gtids = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:1';", 0, {"statements": "1", "transaction": "1"}),
        ("start slave until sql_after_mts_gaps;", 0, {"statements": "1", "transaction": "1"}),
        ("start replica user = 'u' password = 'p' default_auth = 'mysql_native_password' plugin_dir = '/tmp' for channel 'ch1';", 0, {"statements": "1", "transaction": "1"}),
        ("start group_replication;", 0, {"statements": "1", "transaction": "1"}),
        ("start group_replication user = 'u', password = 'p', default_auth = 'plugin';", 0, {"statements": "1", "transaction": "1"}),
        ("stop replica;", 0, {"statements": "1", "replication": "1"}),
        ("stop slave sql_thread for channel 'ch1';", 0, {"statements": "1", "replication": "1"}),
        ("stop group_replication;", 0, {"statements": "1", "replication": "1"}),
        ("set transaction;", 1, {}),
        ("set transaction with consistent snapshot;", 1, {}),
        ("set transaction isolation repeatable read;", 1, {}),
        ("set transaction isolation level;", 1, {}),
        ("set persist transaction read only;", 1, {}),
        ("start transaction garbage;", 1, {}),
        ("start transaction read garbage;", 1, {}),
        ("start replica garbage;", 1, {}),
        ("start replica io_thread garbage;", 1, {}),
        ("start replica until source_log_file = 'bin.000001';", 1, {}),
        ("start replica until source_log_file = 'bin.000001', relay_log_pos = 4;", 1, {}),
        ("start group_replication user = 'u' password = 'p';", 1, {}),
        ("stop replica garbage;", 1, {}),
        ("stop group_replication garbage;", 1, {}),
        ("start nonsense;", 1, {}),
        ("savepoint s1;", 0, {"statements": "1", "transaction": "1"}),
        ("savepoint s1 extra;", 1, {}),
        ("savepoint select;", 1, {}),
        ("release savepoint s1;", 0, {"statements": "1", "transaction": "1"}),
        ("release savepoint s1 extra;", 1, {}),
        ("release nonsense;", 1, {}),
        ("lock tables t write;", 0, {"statements": "1", "transaction": "1"}),
        ("lock table mysql.user read;", 0, {"statements": "1", "transaction": "1"}),
        ("lock table db.t as a read local, t2 low_priority write;", 0, {"statements": "1", "transaction": "1"}),
        ("lock tables t1 b read;", 0, {"statements": "1", "transaction": "1"}),
        ("lock tables t;", 1, {}),
        ("lock tables t read local extra;", 1, {}),
        ("lock instance for backup;", 0, {"statements": "1", "transaction": "1"}),
        ("lock instance for bogus;", 1, {}),
        ("lock instance backup;", 1, {}),
        ("lock nonsense;", 1, {}),
        ("unlock tables;", 0, {"statements": "1", "transaction": "1"}),
        ("unlock instance;", 0, {"statements": "1", "transaction": "1"}),
        ("unlock tables t;", 1, {}),
        ("unlock nonsense;", 1, {}),
        ("analyze table t;", 0, {"statements": "1", "admin": "1"}),
        ("analyze tables t;", 0, {"statements": "1", "admin": "1"}),
        ("analyze table t1, t2 update histogram on a with 2 buckets;", 0, {"statements": "1", "admin": "1"}),
        ("analyze table t drop histogram on a, b;", 0, {"statements": "1", "admin": "1"}),
        ("analyze table t update histogram on a using data '{\"buckets\": []}';", 0, {"statements": "1", "admin": "1"}),
        ("check tables t;", 0, {"statements": "1", "admin": "1"}),
        ("check table t fast medium changed;", 0, {"statements": "1", "admin": "1"}),
        ("check table t for upgrade;", 0, {"statements": "1", "admin": "1"}),
        ("check table information_schema.processlist fast;", 0, {"statements": "1", "admin": "1"}),
        ("checksum table t;", 0, {"statements": "1", "admin": "1"}),
        ("checksum table t quick;", 0, {"statements": "1", "admin": "1"}),
        ("checksum tables t;", 1, {}),
        ("optimize local table t;", 0, {"statements": "1", "admin": "1"}),
        ("repair table t use_frm;", 0, {"statements": "1", "admin": "1"}),
        ("repair no_write_to_binlog table t;", 0, {"statements": "1", "admin": "1"}),
        ("analyze table t t2;", 1, {}),
        ("analyze table t update histogram on a with 2;", 1, {}),
        ("check table t garbage;", 1, {}),
        ("checksum table t garbage;", 1, {}),
        ("optimize table t quick;", 1, {}),
        ("repair table t garbage;", 1, {}),
        ("analyze nonsense;", 1, {}),
        ("install component 'file://x';", 0, {"statements": "1", "admin": "1"}),
        ("install component 'file://x', 'file://y' set length = 16;", 0, {"statements": "1", "admin": "1"}),
        ("install component 'file://x' set length = cast(rand() * 10 as signed);", 0, {"statements": "1", "admin": "1"}),
        ("install component 'file://x' set global validate_password.length = 16, persist validate_password.number_count = 13;", 0, {"statements": "1", "admin": "1"}),
        ("install plugin archive soname 'ha_archive.so';", 0, {"statements": "1", "admin": "1"}),
        ("uninstall plugin archive;", 0, {"statements": "1", "admin": "1"}),
        ("uninstall component 'file://x', 'file://y';", 0, {"statements": "1", "admin": "1"}),
        ("install plugin archive;", 1, {}),
        ("install component 'file://x' 'file://y';", 1, {}),
        ("install component 'file://x' set length;", 1, {}),
        ("install component 'file://x' set length =;", 1, {}),
        ("uninstall plugin archive extra;", 1, {}),
        ("install nonsense;", 1, {}),
        ("import table from 't.sdi';", 0, {"statements": "1", "utility": "1"}),
        ("import table from 't1.sdi', 't2.sdi';", 0, {"statements": "1", "utility": "1"}),
        ("import table 't.sdi';", 1, {}),
        ("import table from 't1.sdi' 't2.sdi';", 1, {}),
        ("import nonsense;", 1, {}),
        ("cache index t in k;", 0, {"statements": "1", "admin": "1"}),
        ("cache index t key (`primary`) in keycache1;", 0, {"statements": "1", "admin": "1"}),
        ("cache index t1, t2 in default;", 0, {"statements": "1", "admin": "1"}),
        ("cache index t key (a, b), db.t2 key (c) in k;", 0, {"statements": "1", "admin": "1"}),
        ("cache index t garbage;", 1, {}),
        ("cache index t key (a) garbage k;", 1, {}),
        ("cache nonsense;", 1, {}),
        ("kill query @id;", 0, {"statements": "1", "admin": "1"}),
        ("kill @id;", 0, {"statements": "1", "admin": "1"}),
        ("kill connection @id;", 0, {"statements": "1", "admin": "1"}),
        ("kill @id extra;", 1, {}),
        ("kill select;", 1, {}),
        ("deallocate prepare s;", 0, {"statements": "1", "prepared": "1"}),
        ("deallocate prepare s extra;", 1, {}),
        ("deallocate nonsense;", 1, {}),
        ("reset persist;", 0, {"statements": "1", "admin": "1"}),
        ("reset binary logs and gtids;", 0, {"statements": "1", "admin": "1"}),
        ("reset binary logs and gtids to 7;", 0, {"statements": "1", "admin": "1"}),
        ("reset replica all for channel 'ch1';", 0, {"statements": "1", "admin": "1"}),
        ("reset persist if exists default.key_buffer_size;", 0, {"statements": "1", "admin": "1"}),
        ("reset binary;", 1, {}),
        ("reset binary logs;", 1, {}),
        ("reset binary logs and bogus;", 1, {}),
        ("reset master extra;", 1, {}),
        ("reset slave all extra;", 1, {}),
        ("reset persist x y;", 1, {}),
        ("reset nonsense;", 1, {}),
        ("purge binary logs to 'bin.0001';", 0, {"statements": "1", "replication": "1"}),
        ("purge master logs before now();", 0, {"statements": "1", "replication": "1"}),
        ("purge binary logs garbage;", 1, {}),
        ("purge binary logs to;", 1, {}),
        ("purge binary logs to 'bin.0001' extra;", 1, {}),
        ("purge binary logs before;", 1, {}),
        ("purge binary;", 1, {}),
        ("purge nonsense;", 1, {}),
        ("change replication source to source_host='127.0.0.1';", 0, {"statements": "1", "replication": "1"}),
        ("change master to master_host='127.0.0.1';", 0, {"statements": "1", "replication": "1"}),
        ("change replication source to source_password='p', ignore_server_ids=(99,100) for channel 'c';", 0, {"statements": "1", "replication": "1"}),
        ("change replication filter replicate_do_db=(db1), replicate_ignore_db=();", 0, {"statements": "1", "replication": "1"}),
        ("change replication filter replicate_do_table=(db1.t1,db2.t2) for channel 'c';", 0, {"statements": "1", "replication": "1"}),
        ("change replication filter replicate_wild_do_table=('db1.old%');", 0, {"statements": "1", "replication": "1"}),
        ("change replication filter replicate_rewrite_db=((db1, db2), (db3, db4));", 0, {"statements": "1", "replication": "1"}),
        ("change replication bogus to source_host='127.0.0.1';", 1, {}),
        ("change replication filter;", 1, {}),
        ("change replication filter replicate_do_db;", 1, {}),
        ("change replication filter replicate_do_db=db1;", 1, {}),
        ("change replication filter unknown_filter=(db1);", 1, {}),
        ("change replication source;", 1, {}),
        ("change replication source to;", 1, {}),
        ("change replication source to source_host;", 1, {}),
        ("change nonsense;", 1, {}),
        ("xa start 'x';", 0, {"statements": "1", "replication": "1"}),
        ("xa start 'x','b',7;", 0, {"statements": "1", "replication": "1"}),
        ("xa start x'1A2B',x'B2A1',7;", 0, {"statements": "1", "replication": "1"}),
        ("xa start 'x' resume;", 0, {"statements": "1", "replication": "1"}),
        ("xa start 'x' join;", 0, {"statements": "1", "replication": "1"}),
        ("xa end 'x' suspend for migrate;", 0, {"statements": "1", "replication": "1"}),
        ("xa commit 'x' one phase;", 0, {"statements": "1", "replication": "1"}),
        ("xa recover;", 0, {"statements": "1", "replication": "1"}),
        ("xa recover convert xid;", 0, {"statements": "1", "replication": "1"}),
        ("xa start 'x' garbage;", 1, {}),
        ("xa end 'x' suspend for bogus;", 1, {}),
        ("xa commit 'x' one bogus;", 1, {}),
        ("xa recover garbage garbage;", 1, {}),
        ("xa recover garbage;", 1, {}),
        ("xa nonsense;", 1, {}),
        ("show tables;", 0, {"statements": "1", "show": "1"}),
        ("show extended full tables from test;", 0, {"statements": "1", "show": "1"}),
        ("show full tables like 't%';", 0, {"statements": "1", "show": "1"}),
        ("show table status from test where name like 't%';", 0, {"statements": "1", "show": "1"}),
        ("show open tables in mysql like 'user%';", 0, {"statements": "1", "show": "1"}),
        ("show events from test like 'e%';", 0, {"statements": "1", "show": "1"}),
        ("show triggers where name like 'trg%';", 0, {"statements": "1", "show": "1"}),
        ("show databases where `database` = 'test';", 0, {"statements": "1", "show": "1"}),
        ("show columns from db.t like 'c%';", 0, {"statements": "1", "show": "1"}),
        ("show full fields from t from db where field like 'c%';", 0, {"statements": "1", "show": "1"}),
        ("show keys in t where key_name like 'idx%';", 0, {"statements": "1", "show": "1"}),
        ("show character set like 'utf8%';", 0, {"statements": "1", "show": "1"}),
        ("show collation where collation like 'utf8%';", 0, {"statements": "1", "show": "1"}),
        ("show engine innodb status;", 0, {"statements": "1", "show": "1"}),
        ("show engine csv mutex;", 0, {"statements": "1", "show": "1"}),
        ("show binary logs;", 0, {"statements": "1", "show": "1"}),
        ("show master logs;", 0, {"statements": "1", "show": "1"}),
        ("show binlog events in 'bin.000001' from 4 limit 10;", 0, {"statements": "1", "show": "1"}),
        ("show function status where db = 'test';", 0, {"statements": "1", "show": "1"}),
        ("show function code testdb.func_root;", 0, {"statements": "1", "show": "1"}),
        ("show procedure status like 'p%';", 0, {"statements": "1", "show": "1"}),
        ("show procedure code p1;", 0, {"statements": "1", "show": "1"}),
        ("show storage engines;", 0, {"statements": "1", "show": "1"}),
        ("show parse_tree select * from t where id = 1;", 0, {"statements": "1", "show": "1"}),
        ("show parse_tree with cte as (select 1) select * from cte;", 0, {"statements": "1", "show": "1"}),
        ("show profile;", 0, {"statements": "1", "show": "1"}),
        ("show profile cpu, block io for query 15 limit 2 offset 2;", 0, {"statements": "1", "show": "1"}),
        ("show profile context switches;", 0, {"statements": "1", "show": "1"}),
        ("show profile memory, page faults, source, swaps, ipc;", 0, {"statements": "1", "show": "1"}),
        ("show extended index from t;", 0, {"statements": "1", "show": "1"}),
        ("show full processlist;", 0, {"statements": "1", "show": "1"}),
        ("show global status like 'Threads%';", 0, {"statements": "1", "show": "1"}),
        ("show session variables where variable_name like 'sql%';", 0, {"statements": "1", "show": "1"}),
        ("show variables;", 0, {"statements": "1", "show": "1"}),
        ("show count(*) warnings;", 0, {"statements": "1", "show": "1"}),
        ("show count(*) errors;", 0, {"statements": "1", "show": "1"}),
        ("show create database if not exists db1;", 0, {"statements": "1", "show": "1"}),
        ("show create schema if not exists db1;", 0, {"statements": "1", "show": "1"}),
        ("show create table db.t;", 0, {"statements": "1", "show": "1"}),
        ("show create user u@localhost;", 0, {"statements": "1", "show": "1"}),
        ("show create user current_user();", 0, {"statements": "1", "show": "1"}),
        ("show warnings limit 1;", 0, {"statements": "1", "show": "1"}),
        ("show errors limit 0, 10;", 0, {"statements": "1", "show": "1"}),
        ("show plugins;", 0, {"statements": "1", "show": "1"}),
        ("show privileges;", 0, {"statements": "1", "show": "1"}),
        ("show binary log status;", 0, {"statements": "1", "show": "1"}),
        ("show master status;", 0, {"statements": "1", "show": "1"}),
        ("show slave hosts;", 0, {"statements": "1", "show": "1"}),
        ("show slave status for channel 'ch1';", 0, {"statements": "1", "show": "1"}),
        ("show replica status;", 0, {"statements": "1", "show": "1"}),
        ("show replica status for channel 'ch1';", 0, {"statements": "1", "show": "1"}),
        ("show grants;", 0, {"statements": "1", "show": "1"}),
        ("show grants for current_user;", 0, {"statements": "1", "show": "1"}),
        ("show grants for current_user();", 0, {"statements": "1", "show": "1"}),
        ("show grants for u@localhost using r1, r2;", 0, {"statements": "1", "show": "1"}),
        ("show count warnings;", 1, {}),
        ("show count(*) tables;", 1, {}),
        ("show create;", 1, {}),
        ("show create table;", 1, {}),
        ("show create table if not exists t;", 1, {}),
        ("show create table t extra;", 1, {}),
        ("show create user user();", 1, {}),
        ("show warnings garbage;", 1, {}),
        ("show errors limit;", 1, {}),
        ("show plugins extra;", 1, {}),
        ("show parse_tree;", 1, {}),
        ("show parse_tree delete from t;", 1, {}),
        ("show master logs extra;", 1, {}),
        ("show replica;", 1, {}),
        ("show replica status garbage;", 1, {}),
        ("show grants for;", 1, {}),
        ("show grants garbage;", 1, {}),
        ("show variables like;", 1, {}),
        ("show status garbage;", 1, {}),
        ("show tables garbage;", 1, {}),
        ("show table status garbage;", 1, {}),
        ("show databases garbage;", 1, {}),
        ("show columns from;", 1, {}),
        ("show index from t extra;", 1, {}),
        ("show character set garbage;", 1, {}),
        ("show engine innodb;", 1, {}),
        ("show engine innodb garbage;", 1, {}),
        ("show binary log status garbage;", 1, {}),
        ("show binlog;", 1, {}),
        ("show binlog events garbage;", 1, {}),
        ("show function code;", 1, {}),
        ("show function status garbage;", 1, {}),
        ("show storage;", 1, {}),
        ("show profile garbage;", 1, {}),
        ("show profile cpu garbage;", 1, {}),
        ("show profile block;", 1, {}),
        ("show extended;", 1, {}),
        ("show full;", 1, {}),
        ("show full processlist garbage;", 1, {}),
        ("show global create table t;", 1, {}),
        ("show nonsense;", 1, {}),
        ("describe t;", 0, {"statements": "1", "show": "1"}),
        ("describe db.t;", 0, {"statements": "1", "show": "1"}),
        ("describe t c;", 0, {"statements": "1", "show": "1"}),
        ("describe select * from t;", 0, {"statements": "1", "show": "1"}),
        ("describe format=json select * from t;", 0, {"statements": "1", "show": "1"}),
        ("desc format=json into @plan select * from t;", 0, {"statements": "1", "show": "1"}),
        ("desc for schema db1 select * from t;", 0, {"statements": "1", "show": "1"}),
        ("describe for connection 1;", 0, {"statements": "1", "show": "1"}),
        ("describe select;", 1, {}),
        ("describe t c extra;", 1, {}),
        ("desc format=tree into @plan select * from t;", 1, {}),
        ("describe from;", 1, {}),
        ("explain select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain for schema db1 select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain format=json select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain format=json into @plan select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain format=json into @plan for database db1 select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain format=tree for schema db1 select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain format=tree select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain format=traditional select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain analyze select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain analyze update t set a = 1;", 0, {"statements": "1", "show": "1"}),
        ("explain analyze with cte as (select 1) select * from cte;", 0, {"statements": "1", "show": "1"}),
        ("explain analyze format=tree select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain analyze format=tree for schema db1 select * from t;", 0, {"statements": "1", "show": "1"}),
        ("desc analyze for database db1 select * from t;", 0, {"statements": "1", "show": "1"}),
        ("explain for connection 1;", 0, {"statements": "1", "show": "1"}),
        ("explain format;", 1, {}),
        ("explain format=bogus select * from t;", 1, {}),
        ("explain format=tree into @plan select * from t;", 1, {}),
        ("explain into @plan select * from t;", 1, {}),
        ("explain for schema select * from t;", 1, {}),
        ("explain for database select * from t;", 1, {}),
        ("explain analyze format=json select * from t;", 1, {}),
        ("desc analyze format=json select * from t;", 1, {}),
        ("explain format=tree;", 1, {}),
        ("explain for;", 1, {}),
        ("explain for connection;", 1, {}),
        ("explain for connection 1 extra;", 1, {}),
        ("explain for select;", 1, {}),
        ("explain from;", 1, {}),
        ("use test;", 0, {"statements": "1", "utility": "1"}),
        ("use test extra;", 1, {}),
        ("use select;", 1, {}),
        ("handler t open;", 0, {"statements": "1", "utility": "1"}),
        ("handler t open a;", 0, {"statements": "1", "utility": "1"}),
        ("handler t open as a;", 0, {"statements": "1", "utility": "1"}),
        ("handler s.t open;", 0, {"statements": "1", "utility": "1"}),
        ("handler t read first;", 0, {"statements": "1", "utility": "1"}),
        ("handler t read i next where a = 1 limit 5;", 0, {"statements": "1", "utility": "1"}),
        ("handler t read a=(49);", 0, {"statements": "1", "utility": "1"}),
        ("handler t close;", 0, {"statements": "1", "utility": "1"}),
        ("handler t open a b;", 1, {}),
        ("handler t open as a b;", 1, {}),
        ("handler t read first where;", 1, {}),
        ("handler t read first limit;", 1, {}),
        ("handler t read first limit 1 garbage;", 1, {}),
        ("handler t read;", 1, {}),
        ("handler t read a sideways;", 1, {}),
        ("handler t nonsense;", 1, {}),
        ("handler select open;", 1, {}),
        ("call p();", 0, {"statements": "1", "stored_program": "1"}),
        ("call p;", 0, {"statements": "1", "stored_program": "1"}),
        ("call p(1, now(), @a);", 0, {"statements": "1", "stored_program": "1"}),
        ("call $p(3);", 0, {"statements": "1", "stored_program": "1"}),
        ("call db.p();", 0, {"statements": "1", "stored_program": "1"}),
        ("call account.account(@account);", 0, {"statements": "1", "stored_program": "1"}),
        ("call p(1;", 1, {}),
        ("call p nonsense;", 1, {}),
        ("call select();", 1, {}),
        ("binlog 'abc';", 0, {"statements": "1", "replication": "1"}),
        ("binlog 'abc' extra;", 1, {}),
        ("binlog select;", 1, {}),
        ("clone local data directory = 'x';", 0, {"statements": "1", "admin": "1"}),
        ("clone local data directory 'x';", 0, {"statements": "1", "admin": "1"}),
        ("clone instance from 'u'@'h':3306 identified by 'p';", 0, {"statements": "1", "admin": "1"}),
        ("clone instance from 'u'@'h':3306 identified by 'p' data directory = 'x';", 0, {"statements": "1", "admin": "1"}),
        ("clone instance from 'u'@'h':3306 identified by 'p' require ssl;", 0, {"statements": "1", "admin": "1"}),
        ("clone instance from 'u'@'h':3306 identified by 'p' data directory 'x' require no ssl;", 0, {"statements": "1", "admin": "1"}),
        ("clone instance from u@h:3306 identified by 'p';", 0, {"statements": "1", "admin": "1"}),
        ("clone local;", 1, {}),
        ("clone local data file = 'x';", 1, {}),
        ("clone local data directory = 'x' extra;", 1, {}),
        ("clone instance;", 1, {}),
        ("clone instance from 'u'@'h' by 'p';", 1, {}),
        ("clone instance from 'u'@'h' identified by 'p';", 1, {}),
        ("clone instance from 'u'@'h': identified by 'p';", 1, {}),
        ("clone instance from 'u'@'h':3306 identified by 'p' data directory;", 1, {}),
        ("clone instance from 'u'@'h':3306 identified by 'p' require;", 1, {}),
        ("clone instance from 'u'@'h':3306 identified by 'p' require no;", 1, {}),
        ("clone nonsense;", 1, {}),
        ("flush tables;", 0, {"statements": "1", "admin": "1"}),
        ("flush local tables t for export;", 0, {"statements": "1", "admin": "1"}),
        ("flush binary logs;", 0, {"statements": "1", "admin": "1"}),
        ("flush engine logs;", 0, {"statements": "1", "admin": "1"}),
        ("flush general logs;", 0, {"statements": "1", "admin": "1"}),
        ("flush relay logs;", 0, {"statements": "1", "admin": "1"}),
        ("flush relay logs for channel 'ch1';", 0, {"statements": "1", "admin": "1"}),
        ("flush slow logs;", 0, {"statements": "1", "admin": "1"}),
        ("flush status,user_resources;", 0, {"statements": "1", "admin": "1"}),
        ("flush tables with read lock;", 0, {"statements": "1", "admin": "1"}),
        ("flush local;", 1, {}),
        ("flush binary;", 1, {}),
        ("flush binary logs now;", 1, {}),
        ("flush engine;", 1, {}),
        ("flush relay logs for;", 1, {}),
        ("flush status garbage;", 1, {}),
        ("flush tables t garbage;", 1, {}),
        ("flush nonsense;", 1, {}),
        ("restart;", 0, {"statements": "1", "admin": "1"}),
        ("restart now;", 1, {}),
        ("shutdown;", 0, {"statements": "1", "admin": "1"}),
        ("shutdown now;", 1, {}),
        ("insert into t values (1);", 0, {"statements": "1", "insert": "1"}),
        ("insert t values (1);", 0, {"statements": "1", "insert": "1"}),
        ("insert into t (a) values (1);", 0, {"statements": "1", "insert": "1"}),
        ("insert into t (select 1);", 0, {"statements": "1", "insert": "1"}),
        ("insert into t (select 1) union select 2;", 0, {"statements": "1", "insert": "1"}),
        ("insert into t (select 1) union (select 2) limit 1;", 0, {"statements": "1", "insert": "1"}),
        ("insert into t (select 1) union values row(2);", 0, {"statements": "1", "insert": "1"}),
        ("insert into t (select 1) order by 1;", 0, {"statements": "1", "insert": "1"}),
        ("insert into t (select 1) limit 1;", 0, {"statements": "1", "insert": "1"}),
        ("insert into t (select 1) on duplicate key update a=1;", 0, {"statements": "1", "insert": "1"}),
        ("insert into t (a) (select 1);", 0, {"statements": "1", "insert": "1"}),
        ("insert into t select 1;", 0, {"statements": "1", "insert": "1"}),
        ("insert into t table t1 limit 1;", 0, {"statements": "1", "insert": "1"}),
        ("insert into t with cte as (select 1) select * from cte;", 0, {"statements": "1", "insert": "1"}),
        ("insert into t partition (p0) values (1);", 0, {"statements": "1", "insert": "1"}),
        ("insert into t partition (p0) (a) values (1);", 0, {"statements": "1", "insert": "1"}),
        ("insert into t value (1);", 0, {"statements": "1", "insert": "1"}),
        ("insert into t set a = 1;", 0, {"statements": "1", "insert": "1"}),
        ("insert into t set t.a = 1, b = 2;", 0, {"statements": "1", "insert": "1"}),
        ("insert ignore into t values (1);", 0, {"statements": "1", "insert": "1"}),
        ("insert into values (1);", 1, {}),
        ("insert into t (a);", 1, {}),
        ("insert into t (a values (1);", 1, {}),
        ("insert into t bogus (1);", 1, {}),
        ("insert into t set a;", 1, {}),
        ("insert into t partition p0 values (1);", 1, {}),
        ("insert into t (select 1) union garbage;", 1, {}),
        ("insert into t (select 1) order by;", 1, {}),
        ("insert into t (select 1) limit;", 1, {}),
        ("insert into t (select 1) on duplicate key update;", 1, {}),
        ("insert ignore;", 1, {}),
        ("insert select;", 1, {}),
        ("insert into t select;", 1, {}),
        ("insert into t table;", 1, {}),
        ("replace into t values (1);", 0, {"statements": "1", "replace": "1"}),
        ("replace t values (1);", 0, {"statements": "1", "replace": "1"}),
        ("replace into t partition (p0) value (1);", 0, {"statements": "1", "replace": "1"}),
        ("replace into t set a = 1;", 0, {"statements": "1", "replace": "1"}),
        ("replace delayed into t values (1);", 0, {"statements": "1", "replace": "1"}),
        ("replace into values (1);", 1, {}),
        ("replace into t bogus (1);", 1, {}),
        ("replace into t set a;", 1, {}),
        ("replace delayed;", 1, {}),
        ("replace select;", 1, {}),
        ("update t set a = 1;", 0, {"statements": "1", "update": "1"}),
        ("update ignore t set a = 1;", 0, {"statements": "1", "update": "1"}),
        ("update mysql.user set plugin='mysql_native_password';", 0, {"statements": "1", "update": "1"}),
        ("update (select 1) as x, t set t.a=x.a;", 0, {"statements": "1", "update": "1"}),
        ("update t1 join t2 on t1.id=t2.id set t1.a=1;", 0, {"statements": "1", "update": "1"}),
        ("update t set t.a=1, b=2 where t.id=1;", 0, {"statements": "1", "update": "1"}),
        ("update ignore;", 1, {}),
        ("update select set a = 1;", 1, {}),
        ("update t where a = 1;", 1, {}),
        ("update t set a;", 1, {}),
        ("update t set = 1;", 1, {}),
        ("delete from t;", 0, {"statements": "1", "delete": "1"}),
        ("delete quick from t;", 0, {"statements": "1", "delete": "1"}),
        ("delete t1 from t1 inner join t2 on t1.id=t2.id;", 0, {"statements": "1", "delete": "1"}),
        ("delete from t1 using t1 inner join t2 on t1.id=t2.id;", 0, {"statements": "1", "delete": "1"}),
        ("delete from t1 using t1, t2 where t1.id=t2.id;", 0, {"statements": "1", "delete": "1"}),
        ("delete from t partition (p0, p1) where a=1;", 0, {"statements": "1", "delete": "1"}),
        ("delete from;", 1, {}),
        ("delete from t1 using;", 1, {}),
        ("delete from t1 using t1 where;", 1, {}),
        ("delete from t partition p0;", 1, {}),
        ("delete from t limit;", 1, {}),
        ("delete quick;", 1, {}),
        ("delete select;", 1, {}),
        ("with cte as (select 1) select * from cte;", 0, {"statements": "1", "select": "1"}),
        ("with recursive cte as (select 1) select * from cte;", 0, {"statements": "1", "select": "1"}),
        ("with cte(a, b) as (select 1, 2) select * from cte;", 0, {"statements": "1", "select": "1"}),
        ("with a as (select 1), b as (select 2) select * from a;", 0, {"statements": "1", "select": "1"}),
        ("with cte as (select 1) (select * from cte);", 0, {"statements": "1", "select": "1"}),
        ("with cte as (select 1) update t set a=1;", 0, {"statements": "1", "select": "1"}),
        ("with cte as (select 1) table cte limit 1;", 0, {"statements": "1", "select": "1"}),
        ("with cte as (select 1) values row(1);", 0, {"statements": "1", "select": "1"}),
        ("with cte as (select 1) insert into t values (1);", 0, {"statements": "1", "select": "1"}),
        ("with cte as (select 1) (select * from cte);", 0, {"statements": "1", "select": "1"}),
        ("with cte select 1;", 1, {}),
        ("with cte as () select 1;", 1, {}),
        ("with cte as (select 1 select 1;", 1, {}),
        ("with select;", 1, {}),
        ("table t;", 0, {"statements": "1", "select": "1"}),
        ("table db.t limit 5 offset 5;", 0, {"statements": "1", "select": "1"}),
        ("table t garbage;", 1, {}),
        ("table t limit;", 1, {}),
        ("table select;", 1, {}),
        ("values row(1);", 0, {"statements": "1", "select": "1"}),
        ("values row(1), row((select 2));", 0, {"statements": "1", "select": "1"}),
        ("values row(1) union select 2;", 0, {"statements": "1", "select": "1"}),
        ("values row(1) union all table t;", 0, {"statements": "1", "select": "1"}),
        ("values row(1) union table t limit 1;", 0, {"statements": "1", "select": "1"}),
        ("values row(1) union values row(2);", 0, {"statements": "1", "select": "1"}),
        ("values row(1) union with cte as (select 1) select * from cte;", 0, {"statements": "1", "select": "1"}),
        ("values row(1) union (select 2);", 0, {"statements": "1", "select": "1"}),
        ("values row(1) order by 1 desc;", 0, {"statements": "1", "select": "1"}),
        ("values row(1) order by (select 1) asc;", 0, {"statements": "1", "select": "1"}),
        ("values row(1, 2) order by column_0, column_1 desc;", 0, {"statements": "1", "select": "1"}),
        ("values row(1) limit 1;", 0, {"statements": "1", "select": "1"}),
        ("values row(1) limit 1 offset 2;", 0, {"statements": "1", "select": "1"}),
        ("values row 1;", 1, {}),
        ("values row(1;", 1, {}),
        ("values row(1) garbage;", 1, {}),
        ("values row(1) order by;", 1, {}),
        ("values row(1) order by 1 bogus;", 1, {}),
        ("values row(1) union garbage;", 1, {}),
        ("values row(1) union select;", 1, {}),
        ("values row(1) union values;", 1, {}),
        ("values row(1) limit;", 1, {}),
        ("values row(1) limit 1 garbage;", 1, {}),
        ("values select;", 1, {}),
        ("prepare s from 'select 1';", 0, {"statements": "1", "prepared": "1"}),
        ("prepare s from @sql;", 0, {"statements": "1", "prepared": "1"}),
        ("prepare s from 'select 1' extra;", 1, {}),
        ("prepare s;", 1, {}),
        ("prepare select from 'select 1';", 1, {}),
        ("execute s;", 0, {"statements": "1", "prepared": "1"}),
        ("execute s using @a;", 0, {"statements": "1", "prepared": "1"}),
        ("execute s using @a, @b;", 0, {"statements": "1", "prepared": "1"}),
        ("execute s using @a @b;", 1, {}),
        ("execute s extra;", 1, {}),
        ("execute select;", 1, {}),
        ("get diagnostics @n = number;", 0, {"statements": "1", "stored_program": "1"}),
        ("get diagnostics @n = number, @r = row_count;", 0, {"statements": "1", "stored_program": "1"}),
        ("get diagnostics condition 1 @errno = mysql_errno, @msg = message_text;", 0, {"statements": "1", "stored_program": "1"}),
        ("get diagnostics condition 1 @state = returned_sqlstate;", 0, {"statements": "1", "stored_program": "1"}),
        ("get diagnostics @n number;", 1, {}),
        ("get diagnostics condition 1;", 1, {}),
        ("get diagnostics condition 1 @msg = bogus;", 1, {}),
        ("get nonsense;", 1, {}),
        ("signal sqlstate '01000';", 0, {"statements": "1", "stored_program": "1"}),
        ("signal sqlstate '01000' set message_text = 'x';", 0, {"statements": "1", "stored_program": "1"}),
        ("signal sqlstate '01000' set message_text = 'x', mysql_errno = 1000;", 0, {"statements": "1", "stored_program": "1"}),
        ("signal sqlstate;", 1, {}),
        ("signal sqlstate '01000' garbage;", 1, {}),
        ("signal sqlstate '01000' set message_text =;", 1, {}),
        ("signal sqlstate '01000' set returned_sqlstate = '01000';", 1, {}),
        ("signal select;", 1, {}),
        ("begin;", 0, {"statements": "1", "transaction": "1"}),
        ("begin work;", 0, {"statements": "1", "transaction": "1"}),
        ("begin nonsense;", 1, {}),
        ("commit and no chain release;", 0, {"statements": "1", "transaction": "1"}),
        ("commit nonsense;", 1, {}),
        ("rollback to savepoint s1;", 0, {"statements": "1", "transaction": "1"}),
        ("rollback nonsense;", 1, {}),
        ("set names utf8mb4;", 0, {"statements": "1", "utility": "1"}),
        ("set names utf8mb4 collate utf8mb4_bin;", 0, {"statements": "1", "utility": "1"}),
        ("set names default;", 0, {"statements": "1", "utility": "1"}),
        ("set names utf8, @@character_set_results=null;", 0, {"statements": "1", "utility": "1"}),
        ("set names default, sql_mode=default;", 0, {"statements": "1", "utility": "1"}),
        ("set character set default;", 0, {"statements": "1", "utility": "1"}),
        ("set charset default, @dummy='A';", 0, {"statements": "1", "utility": "1"}),
        ("set global max_connections = 100;", 0, {"statements": "1", "utility": "1"}),
        ("set persist_only event_scheduler = disabled;", 0, {"statements": "1", "utility": "1"}),
        ("set @a := 1;", 0, {"statements": "1", "utility": "1"}),
        ("set password = 'secret';", 0, {"statements": "1", "utility": "1"}),
        ("set password to random;", 0, {"statements": "1", "utility": "1"}),
        ("set password for current_user() = 'secret';", 0, {"statements": "1", "utility": "1"}),
        ("set password for current_user() = 'secret' replace 'old' retain current password;", 0, {"statements": "1", "utility": "1"}),
        ("set role r1;", 0, {"statements": "1", "utility": "1"}),
        ("set role none;", 0, {"statements": "1", "utility": "1"}),
        ("set role all except r1, r2@localhost;", 0, {"statements": "1", "utility": "1"}),
        ("set default role all to u@localhost, u2;", 0, {"statements": "1", "utility": "1"}),
        ("set default role r1, r2 to u@localhost;", 0, {"statements": "1", "utility": "1"}),
        ("set resource group rg;", 0, {"statements": "1", "utility": "1"}),
        ("set resource group rg for 14,78,4;", 0, {"statements": "1", "utility": "1"}),
        ("set sql_buffer_result = on;", 0, {"statements": "1", "utility": "1"}),
        ("set select;", 1, {}),
        ("set global max_connections;", 1, {}),
        ("set names;", 1, {}),
        ("set names utf8mb4 extra;", 1, {}),
        ("set names utf8mb4 collate;", 1, {}),
        ("set names utf8mb4 collate utf8mb4_bin extra;", 1, {}),
        ("set names utf8mb4, sql_mode;", 1, {}),
        ("set character set utf8mb4 extra;", 1, {}),
        ("set password for u;", 1, {}),
        ("set password := 'secret';", 1, {}),
        ("set password replace 'old';", 1, {}),
        ("set password = 'secret' garbage;", 1, {}),
        ("set password retain current password;", 1, {}),
        ("set role all except;", 1, {}),
        ("set role none extra;", 1, {}),
        ("set default role all;", 1, {}),
        ("set default role all to;", 1, {}),
        ("set default role all except r1 to u;", 1, {}),
        ("set resource group rg for;", 1, {}),
        ("set resource group rg invalid;", 1, {}),
        ("grant select on *.* to u;", 0, {"statements": "1", "admin": "1"}),
        ("grant all on *.* to u;", 0, {"statements": "1", "admin": "1"}),
        ("grant backup_admin on *.* to u;", 0, {"statements": "1", "admin": "1"}),
        ("grant insert (a), update on db.t to u identified by 'p';", 0, {"statements": "1", "admin": "1"}),
        ("grant show databases on *.* to u;", 0, {"statements": "1", "admin": "1"}),
        ("grant select on *.* to u with grant option;", 0, {"statements": "1", "admin": "1"}),
        ("grant insert on *.* to current_user();", 0, {"statements": "1", "admin": "1"}),
        ("grant proxy on u1@localhost to u2@localhost with grant option;", 0, {"statements": "1", "admin": "1"}),
        ("grant select on *.* to u as current_user with role all except r1;", 0, {"statements": "1", "admin": "1"}),
        ("grant select on *.* to u identified by 'p' require ssl with max_queries_per_hour 1;", 0, {"statements": "1", "admin": "1"}),
        ("grant r1, r2 to u with admin option;", 0, {"statements": "1", "admin": "1"}),
        ("grant from;", 1, {}),
        ("grant select on to u;", 1, {}),
        ("grant select on *.* to u with admin;", 1, {}),
        ("grant select on *.* to u as;", 1, {}),
        ("revoke select on *.* from u;", 0, {"statements": "1", "admin": "1"}),
        ("revoke all on *.* from current_user();", 0, {"statements": "1", "admin": "1"}),
        ("revoke all on *.* from u;", 0, {"statements": "1", "admin": "1"}),
        ("revoke if exists r1 from u;", 0, {"statements": "1", "admin": "1"}),
        ("revoke if exists select on db.* from u ignore unknown user;", 0, {"statements": "1", "admin": "1"}),
        ("revoke proxy on u1@localhost from u2@localhost ignore unknown user;", 0, {"statements": "1", "admin": "1"}),
        ("revoke all privileges, grant option from u ignore unknown user;", 0, {"statements": "1", "admin": "1"}),
        ("revoke from;", 1, {}),
        ("revoke if exists select on from u;", 1, {}),
        ("revoke select on *.* from u ignore user;", 1, {}),
        ("block1: begin end;", 0, {"statements": "1", "stored_program": "1"}),
        ("block1: loop end loop;", 0, {"statements": "1", "stored_program": "1"}),
        ("block1: select 1;", 1, {}),
        ("leave block1;", 0, {"statements": "1", "stored_program": "1"}),
        ("leave select;", 1, {}),
        ("iterate block1;", 0, {"statements": "1", "stored_program": "1"}),
        ("iterate select;", 1, {}),
        ("help 'select';", 0, {"statements": "1", "utility": "1"}),
        ("help select;", 0, {"statements": "1", "utility": "1"}),
        ("help select extra;", 1, {}),
        ("help;", 1, {}),
        ("do 1 + 1;", 0, {"statements": "1", "utility": "1"}),
        ("do (select 1);", 0, {"statements": "1", "utility": "1"}),
        ("do select 1;", 1, {}),
        ("if a then select 1; end if;", 0, {"statements": "2", "stored_program": "2"}),
        ("if a and b then select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("if(a, b, c;", 0, {"statements": "1", "permissive": "1"}),
        ("if select then select 1; end if;", 1, {}),
        ("if a select 1;", 1, {}),
        ("elseif a then select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("elseif f(a) or b then select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("elseif select then select 1;", 1, {}),
        ("elseif a select 1;", 1, {}),
        ("return 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("return select;", 1, {}),
        ("resignal;", 0, {"statements": "1", "stored_program": "1"}),
        ("resignal set message_text = 'x';", 0, {"statements": "1", "stored_program": "1"}),
        ("resignal sqlstate '01000';", 0, {"statements": "1", "stored_program": "1"}),
        ("resignal sqlstate;", 1, {}),
        ("resignal set message_text =;", 1, {}),
        ("while a do select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("while a and b do select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("while f(a, b) or c do select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("while select do select 1;", 1, {}),
        ("while a select 1;", 1, {}),
        ("until a;", 0, {"statements": "1", "stored_program": "1"}),
        ("until select;", 1, {}),
        ("when a then select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("when a in (select 1) then select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("when select then select 1;", 1, {}),
        ("when a select 1;", 1, {}),
        ("open cur1;", 0, {"statements": "1", "stored_program": "1"}),
        ("open cur1 extra;", 1, {}),
        ("open select;", 1, {}),
        ("fetch cur1 into a;", 0, {"statements": "1", "stored_program": "1"}),
        ("fetch cur1 into a, b;", 0, {"statements": "1", "stored_program": "1"}),
        ("fetch cur1;", 1, {}),
        ("fetch cur1 into;", 1, {}),
        ("fetch cur1 into a + b;", 1, {}),
        ("fetch select into a;", 1, {}),
        ("close cur1;", 0, {"statements": "1", "stored_program": "1"}),
        ("close cur1 extra;", 1, {}),
        ("close select;", 1, {}),
        ("else;", 0, {"statements": "1", "stored_program": "1"}),
        ("loop select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("repeat select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("case when a then select 1; end case;", 0, {"statements": "2", "stored_program": "2"}),
        ("declare x int;", 0, {"statements": "1", "stored_program": "1"}),
        ("declare x, y int default 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("declare c condition for sqlstate '45000';", 0, {"statements": "1", "stored_program": "1"}),
        ("declare cur cursor for select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("declare continue handler for sqlexception select 1;", 0, {"statements": "1", "stored_program": "1"}),
        ("declare continue handler for not found begin end;", 0, {"statements": "1", "stored_program": "1"}),
        ("declare x;", 1, {}),
        ("declare c condition sqlstate '45000';", 1, {}),
        ("declare cur cursor select 1;", 1, {}),
        ("declare continue bogus for sqlexception select 1;", 1, {}),
        ("declare continue handler for select 1;", 1, {}),
        ("declare select int;", 1, {}),
        ("end loop;", 0, {"statements": "1", "stored_program": "1"}),
        ("end while loop_label;", 0, {"statements": "1", "stored_program": "1"}),
        ("end case;", 0, {"statements": "1", "stored_program": "1"}),
        ("end if label1;", 1, {}),
        ("end nonsense extra;", 1, {}),
        ("(select 1);", 0, {"statements": "1", "select": "1"}),
    ]

    for sql, expected_rc, expected_stats in cases:
        completed = subprocess.run(
            [args.exe, "--stats"],
            input=sql.encode(),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if completed.returncode != expected_rc:
            print(f"unexpected return code for {sql!r}: {completed.returncode}")
            print(completed.stdout.decode())
            print(completed.stderr.decode())
            return 1

        stats = parse_stats(completed.stdout.decode())
        for key, value in expected_stats.items():
            if stats.get(key) != value:
                print(f"unexpected stat for {sql!r}: {key}={stats.get(key)!r}")
                print(completed.stdout.decode())
                return 1

    print(f"passed {len(cases)} parser smoke cases")
    return 0


def parse_stats(output: str) -> dict[str, str]:
    stats: dict[str, str] = {}
    for line in output.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        stats[key] = value
    return stats


if __name__ == "__main__":
    raise SystemExit(main())
