get_property(mylite_registered_tests DIRECTORY PROPERTY TESTS)

foreach(test_name IN LISTS mylite_registered_tests)
  if(test_name MATCHES "^libmylite\\.runtime\\.")
    set(test_labels runtime)
    set(test_timeout 120)
  elseif(test_name MATCHES "^libmylite\\.(lexer|parser\\.)")
    set(test_labels "parser;unit")
    set(test_timeout 60)
  elseif(test_name MATCHES "^libmylite\\.benchmark\\.")
    set(test_labels "benchmark;unit")
    set(test_timeout 60)
  elseif(test_name MATCHES "^libmylite\\.(storage\\..*|file_format|sqlite)$")
    set(test_labels "storage;unit")
    set(test_timeout 60)
  else()
    set(test_labels unit)
    set(test_timeout 60)
  endif()

  set_property(TEST "${test_name}" APPEND PROPERTY LABELS "${test_labels}")
  get_property(test_has_timeout TEST "${test_name}" PROPERTY TIMEOUT SET)
  if(NOT test_has_timeout)
    set_property(TEST "${test_name}" PROPERTY TIMEOUT "${test_timeout}")
  endif()
endforeach()

unset(mylite_registered_tests)
unset(test_has_timeout)
unset(test_labels)
unset(test_name)
unset(test_timeout)
